/* Butterfly Word — bwd-meta-2.js (개념별 BWD_META: cefr/origin/syn/ant · 분할 2/2 · 자동생성) */
window.BWD_META = Object.assign(window.BWD_META||{}, {
  "abiding": {cefr:"C1",origin:"동사 abide에 -ing가 붙음",syn:["enduring","lasting","persistent"],ant:["transient","ephemeral","temporary"]},
  "abilities": {cefr:"A2",origin:"라틴어 habilitas(적합성, 능력)에서 유래한 ability의 복수형",syn:["talents","capabilities","skills"],ant:["inabilities","incapabilities","weaknesses"]},
  "ability": {cefr:"A2",origin:"라틴어 habilitas(적합성)에서",syn:["capability","talent","skill"],ant:["inability","incapacity","weakness"]},
  "abject": {cefr:"C2",origin:"라틴어 abicere(던져버리다)에서",syn:["miserable","wretched","deplorable"],ant:["proud","commendable"]},
  "abjectly": {cefr:"C2",origin:"라틴어 abicere(던져버리다)에서",syn:["miserably","wretchedly","submissively"],ant:["proudly"]},
  "abjure": {cefr:"C2",origin:"라틴어 abjurare(맹세로 부인하다)에서",syn:["renounce","forswear","retract"],ant:["adopt","embrace"]},
  "ablation": {cefr:"C2",origin:"라틴어 ablatio(제거)에서",syn:["removal","excision","erosion"],ant:[]},
  "ablaze": {cefr:"B2",origin:"고대영어 a-(강조)+blæse(불꽃)에서",syn:["flaming","burning","alight"],ant:["extinguished"]},
  "able": {cefr:"A1",origin:"라틴어 habilis(다룰 수 있는)에서",syn:["capable","competent","qualified"],ant:["incapable","incompetent"]},
  "ably": {cefr:"B2",origin:"라틴어 habilis(다룰 수 있는)에서",syn:["competently","capably","skillfully"],ant:["incompetently"]},
  "abnegation": {cefr:"C2",origin:"라틴어 abnegare(부인하다)에서",syn:["renunciation","denial","self-denial"],ant:["indulgence"]},
  "abnormal": {cefr:"B1",origin:"라틴어 ab-(벗어난)+norma(규범)에서",syn:["unusual","irregular","atypical"],ant:["normal","typical"]},
  "abnormalities": {cefr:"B2",origin:"라틴어 ab-(벗어난)+norma(규범)에서",syn:["irregularities","anomalies","deviations"],ant:["normalities"]},
  "abnormality": {cefr:"B2",origin:"라틴어 ab-(~에서 떨어져) + norma(규칙, 기준) + -ity(명사형 접미사)",syn:["deviation","anomaly","irregularity","peculiarity"],ant:["normality","regularity","typicality"]},
  "abnormally": {cefr:"B2",origin:"라틴어 ab-(~에서 떨어져) + norma(규칙, 기준) + -al(형용사형 접미사) + -ly(부사형 접미사)",syn:["unusually","exceptionally","strangely","uncommonly"],ant:["normally","regularly","typically"]},
  "aboard": {cefr:"A2",origin:"고대 프랑스어 a bord(배 옆에)에서",syn:["on board","on"],ant:["ashore","off"]},
  "abode": {cefr:"B2",origin:"고대 영어 abidan(머무르다)에서 파생",syn:["dwelling","residence","home","house"],ant:[]},
  "abolish": {cefr:"B1",origin:"라틴어 abolere(파괴하다, 폐지하다)에서",syn:["cancel","eliminate","repeal","annul"],ant:["establish","institute","create"]},
  "abolished": {cefr:"B1",origin:"라틴어 abolere(파괴하다, 폐지하다)에서",syn:["canceled","eliminated","repealed","annulled"],ant:["established","instituted","created"]},
  "abolishing": {cefr:"B1",origin:"라틴어 abolere(파괴하다, 폐지하다)에서",syn:["canceling","eliminating","repealing","annulling"],ant:["establishing","instituting","creating"]},
  "abolition": {cefr:"B2",origin:"라틴어 abolitio(폐지)에서",syn:["repeal","cancellation","elimination","annulment"],ant:["establishment","institution","creation"]},
  "abolitionist": {cefr:"C1",origin:"라틴어 abolitio(폐지)에서 + -ist(사람을 나타내는 접미사)",syn:["emancipator","reformer","liberator"],ant:["pro-slavery","supporter"]},
  "abolitionists": {cefr:"C1",origin:"라틴어 abolitio(폐지)에서 + -ist(사람을 나타내는 접미사)",syn:["emancipators","reformers","liberators"],ant:["pro-slavery","supporters"]},
  "abominable": {cefr:"C1",origin:"라틴어 abominabilis(혐오스러운)에서",syn:["terrible","loathsome","detestable","awful"],ant:["wonderful","delightful","excellent"]},
  "abomination": {cefr:"C2",origin:"라틴어 abominari(부정을 타서 꺼리다)에서",syn:["atrocity","disgrace","outrage","detestation"],ant:["delight","pride"]},
  "aboriginal": {cefr:"C1",origin:"라틴어 aborigines(태고의 주민)에서",syn:["indigenous","native","original"],ant:["exotic","foreign","imported"]},
  "aborigine": {cefr:"C1",origin:"라틴어 aborigines(태고의 주민)에서",syn:["native","indigene"],ant:["foreigner","immigrant"]},
  "aborigines": {cefr:"C1",origin:"라틴어 aborigines(태고의 주민)에서",syn:["natives","indigenes"],ant:["foreigners","immigrants"]},
  "abort": {cefr:"C1",origin:"라틴어 abortare(유산하다)에서",syn:["terminate","cancel","halt","stop"],ant:["continue","proceed","start"]},
  "aborted": {cefr:"C1",origin:"라틴어 abortare(유산하다)에서",syn:["terminated","cancelled","failed","halted"],ant:["completed","successful"]},
  "abortion": {cefr:"B2",origin:"라틴어 abortio(유산)에서",syn:["termination","miscarriage"],ant:["birth","childbirth"]},
  "abortions": {cefr:"B2",origin:"라틴어 abortio(유산)에서",syn:["terminations","miscarriages"],ant:["births"]},
  "abortive": {cefr:"C1",origin:"라틴어 abortivus(유산의)에서",syn:["unsuccessful","failed","futile","fruitless"],ant:["successful","fruitful","effective"]},
  "abound": {cefr:"B2",origin:"라틴어 abundare(넘쳐흐르다)에서",syn:["flourish","thrive","teem","proliferate"],ant:["lack","want"]},
  "abounds": {cefr:"B2",origin:"라틴어 abundare(넘쳐흐르다)에서",syn:["flourishes","thrives","teems","proliferates"],ant:["lacks","wants"]},
  "about": {cefr:"A1",origin:"고대영어 abutan(주변에, 주위에)에서",syn:["approximately","nearly","around","roughly"],ant:["exactly","precisely"]},
  "above": {cefr:"A1",origin:"고대영어 abufan(위에)에서",syn:["overhead","aloft","beyond"],ant:["below","beneath","under"]},
  "abrade": {cefr:"C1",origin:"라틴어 abradere(문질러 벗기다)에서",syn:["erode","wear","chafe","rub"],ant:["smooth","polish","restore"]},
  "abrasion": {cefr:"B2",origin:"라틴어 abradere(문질러 벗기다)에서 파생된 abrasio(문지름)에서",syn:["scrape","graze","scratch","rub"],ant:["smoothness","healing","repair"]},
  "abrasions": {cefr:"B2",origin:"라틴어 abradere(문질러 벗기다)에서 파생된 abrasio(문지름)에서",syn:["scrapes","grazes","scratches","rubs"],ant:["smoothness","healing","repairs"]},
  "abrasive": {cefr:"C1",origin:"라틴어 abradere(문질러 벗기다)에서 파생된 abrasivus(닳게 하는)에서",syn:["harsh","rough","coarse","caustic"],ant:["smooth","gentle","mild","pleasant"]}
});
