/* Butterfly Word — bwd-meta-1.js (개념별 BWD_META: cefr/origin/syn/ant · 분할 1/2 · 자동생성) */
window.BWD_META = Object.assign(window.BWD_META||{}, {
  "a": {cefr:"A1",origin:"고대영어 an(하나의)에서",syn:[],ant:[]},
  "aardvark": {cefr:"B2",origin:"아프리칸스어 aardvark(땅돼지)에서",syn:[],ant:[]},
  "aback": {cefr:"B2",origin:"고대영어 on bæc(뒤로)에서",syn:["backward","rearward"],ant:["forward"]},
  "abacus": {cefr:"B1",origin:"라틴어 abacus(계산판)에서",syn:[],ant:[]},
  "abandon": {cefr:"B1",origin:"고대 프랑스어 abandonner(포기하다)에서",syn:["desert","forsake","relinquish"],ant:["keep","maintain"]},
  "abandoned": {cefr:"B1",origin:"고대 프랑스어 abandonner(포기하다)에서",syn:["deserted","forsaken","neglected"],ant:["cherished","maintained","cared for"]},
  "abandoning": {cefr:"B2",origin:"고대 프랑스어 abandoner(방임하다)에서",syn:["deserting","forsaking","quitting"],ant:["maintaining","supporting"]},
  "abandonment": {cefr:"C1",origin:"고대 프랑스어 abandoner(방임하다)에서",syn:["desertion","forsaking","relinquishment"],ant:["retention","maintenance"]},
  "abandons": {cefr:"B2",origin:"고대 프랑스어 abandoner(방임하다)에서",syn:["deserts","forsakes","quits"],ant:["maintains","supports"]},
  "abate": {cefr:"C2",origin:"고대 프랑스어 abatre(쓰러뜨리다)에서",syn:["subside","diminish","lessen"],ant:["intensify","increase"]},
  "abated": {cefr:"C2",origin:"고대 프랑스어 abatre(쓰러뜨리다)에서",syn:["subsided","diminished","lessened"],ant:["intensified","increased"]},
  "abatement": {cefr:"C2",origin:"고대 프랑스어 abatre(쓰러뜨리다)에서",syn:["reduction","decrease","diminution"],ant:["increase","intensification"]},
  "abbey": {cefr:"B2",origin:"라틴어 abbatia(수도원)에서",syn:["monastery","convent","priory"],ant:[]},
  "abbot": {cefr:"B2",origin:"라틴어 abbas(아버지)에서",syn:["monk","priest"],ant:[]},
  "abbott": {cefr:"C2",syn:[],ant:[]},
  "abbreviate": {cefr:"B1",origin:"라틴어 breviare(짧게 하다)에서",syn:["shorten","condense"],ant:["lengthen","expand","extend"]},
  "abbreviated": {cefr:"B1",origin:"라틴어 breviare(짧게 하다)에서",syn:["shortened","condensed"],ant:["lengthened","expanded","extended"]},
  "abbreviation": {cefr:"B1",origin:"라틴어 breviare(짧게 하다)에서",syn:["shortening","acronym","contraction"],ant:["expansion","full name"]},
  "abbreviations": {cefr:"B1",origin:"라틴어 breviare(짧게 하다)에서",syn:["shortenings","acronyms","contractions"],ant:["expansions","full names"]},
  "abby": {cefr:"A1",syn:[],ant:[]},
  "abc": {cefr:"A1",origin:"알파벳(alphabet)의 첫 세 글자에서",syn:["basics","fundamentals"],ant:[]},
  "abdel": {cefr:"C2",syn:[],ant:[]},
  "abdicate": {cefr:"C1",origin:"라틴어 abdicare(부인하다, 사임하다)에서",syn:["renounce","step down","resign"],ant:["assume","take over","claim"]},
  "abdicated": {cefr:"B2",origin:"라틴어 ab-(떨어져) + dicare(선언하다, 바치다)에서",syn:["renounced","relinquished","resigned","stepped down"],ant:["assumed","accepted","claimed"]},
  "abdication": {cefr:"C1",origin:"라틴어 abdicatio(포기)에서",syn:["renunciation","resignation","relinquishment","surrender"],ant:["assumption","acceptance","accession"]},
  "abdomen": {cefr:"B1",origin:"라틴어 abdomen(배, 복부)에서",syn:["belly","stomach","gut"],ant:[]},
  "abdominal": {cefr:"B1",origin:"라틴어 abdominalis(복부의)에서",syn:["gastric","visceral","enteric"],ant:[]},
  "abduct": {cefr:"B2",origin:"라틴어 ab-(떨어져) + ducere(이끌다)에서",syn:["kidnap","seize","snatch","carry off"],ant:["release","free","liberate"]},
  "abducted": {cefr:"B2",origin:"라틴어 ab-(떨어져) + ducere(이끌다)에서",syn:["kidnapped","seized","snatched","taken"],ant:["released","freed","liberated"]},
  "abducting": {cefr:"B2",origin:"라틴어 ab-(떨어져) + ducere(이끌다)에서",syn:["kidnapping","seizing","snatching","taking"],ant:["releasing","freeing","liberating"]},
  "abduction": {cefr:"C1",origin:"라틴어 abductio(납치, 유괴)에서",syn:["kidnapping","seizure","snatching","capture"],ant:["release","liberation","freedom"]},
  "aberrant": {cefr:"B2",origin:"라틴어 ab-(떨어져) + errare(헤매다)에서",syn:["abnormal","deviant","atypical","peculiar"],ant:["normal","typical","standard"]},
  "aberration": {cefr:"C1",origin:"라틴어 ab-(떨어져) + errare(헤매다)에서",syn:["anomaly","deviation","abnormality","peculiarity"],ant:["normality","regularity","conformity"]},
  "aberrations": {cefr:"C1",origin:"라틴어 ab-(떨어져) + errare(헤매다)에서",syn:["anomalies","deviations","abnormalities","peculiarities"],ant:["normalities","regularities","conformities"]},
  "abetting": {cefr:"B2",origin:"고대 프랑스어 abeter(부추기다)에서",syn:["aiding","assisting","encouraging","supporting"],ant:["hindering","thwarting","deterring"]},
  "abeyance": {cefr:"C2",origin:"고대 프랑스어 abeance(갈망, 기대)에서",syn:["suspension","dormancy","inactivity"],ant:["continuation","activity"]},
  "abhor": {cefr:"C1",origin:"라틴어 abhorrere(몸서리치다)에서",syn:["detest","loathe","abominate"],ant:["love","admire","adore"]},
  "abhorrence": {cefr:"C2",origin:"라틴어 abhorrere에서 유래한 abhor에 접사 -ence가 붙음",syn:["detestation","loathing","abomination"],ant:["love","admiration","affection"]},
  "abhorrent": {cefr:"C1",origin:"라틴어 abhorrentem에서",syn:["detestable","loathsome","repugnant"],ant:["appealing","delightful","admirable"]},
  "abide": {cefr:"C1",origin:"고대 영어 abidan(기다리다, 머무르다)에서",syn:["remain","stay","persist"],ant:["leave","depart","perish"]},
  "abides": {cefr:"B2",origin:"고대 영어 abidan(기다리다, 머무르다)에서",syn:["complies","obeys","adheres"],ant:["violates","disobeys","breaks"]}
});
