/* Butterfly Word — 단어사전 이모지 + 5형식 예문 오버레이 (bwd-ex5.js)
 * BWD_DICT[word] 에 병합: { img:이모지, ex5:[{t,en,kr}×5] }
 * 이모지 = 단어와 모양·색이 닮은 것. 5형식 = 1~5형식 각 1문장, 단어가 문장에 등장.
 * bwd-dict.js 안 건드리는 별도 파일. 알파벳순. Claude 직접 작성.
 */
window.BWD_EX5 = Object.assign(window.BWD_EX5||{}, {
  "a": {img:"🅰️", ex5:[
    {t:1,en:"A bird sang.",kr:"한 마리 새가 노래했다."},
    {t:2,en:"It is a fact.",kr:"그것은 하나의 사실이다."},
    {t:3,en:"I have a pen.",kr:"나는 펜 한 자루를 가지고 있다."},
    {t:4,en:"She gave me a book.",kr:"그녀는 나에게 책 한 권을 주었다."},
    {t:5,en:"We call it a miracle.",kr:"우리는 그것을 하나의 기적이라고 부른다."}]},
  "aac": {img:"🔊", ex5:[
    {t:1,en:"The AAC file plays.",kr:"그 AAC 파일이 재생된다."},
    {t:2,en:"This AAC sounds clear.",kr:"이 AAC는 선명하게 들린다."},
    {t:3,en:"I opened an AAC file.",kr:"나는 AAC 파일을 열었다."},
    {t:4,en:"He sent me an AAC file.",kr:"그는 나에게 AAC 파일을 보내주었다."},
    {t:5,en:"We consider AAC efficient.",kr:"우리는 AAC가 효율적이라고 여긴다."}]},
  "aachen": {img:"🏛️", ex5:[
    {t:1,en:"Aachen lies in the west.",kr:"아헨은 서부에 있다."},
    {t:2,en:"Aachen is historic.",kr:"아헨은 역사적이다."},
    {t:3,en:"I visited Aachen.",kr:"나는 아헨을 방문했다."},
    {t:4,en:"The guide showed us Aachen.",kr:"가이드는 우리에게 아헨을 보여주었다."},
    {t:5,en:"People call Aachen a treasure.",kr:"사람들은 아헨을 보물이라고 부른다."}]},
  "aardvark": {img:"🐗", ex5:[
    {t:1,en:"The aardvark digs.",kr:"땅돼지가 땅을 판다."},
    {t:2,en:"The aardvark looks odd.",kr:"그 땅돼지는 이상하게 생겼다."},
    {t:3,en:"We saw an aardvark.",kr:"우리는 땅돼지를 보았다."},
    {t:4,en:"The zoo showed us an aardvark.",kr:"동물원은 우리에게 땅돼지를 보여주었다."},
    {t:5,en:"They named the aardvark Ari.",kr:"그들은 그 땅돼지를 아리라고 이름 지었다."}]},
  "aaron": {img:"🧑", ex5:[
    {t:1,en:"Aaron smiled.",kr:"아론이 미소 지었다."},
    {t:2,en:"Aaron is kind.",kr:"아론은 친절하다."},
    {t:3,en:"I met Aaron.",kr:"나는 아론을 만났다."},
    {t:4,en:"Aaron gave me a hand.",kr:"아론은 나를 도와주었다."},
    {t:5,en:"We named the baby Aaron.",kr:"우리는 아기를 아론이라고 이름 지었다."}]},
  "ababa": {img:"🏙️", ex5:[
    {t:1,en:"Ababa stands inland.",kr:"아바바는 내륙에 있다."},
    {t:2,en:"Addis Ababa is busy.",kr:"아디스아바바는 분주하다."},
    {t:3,en:"We toured Ababa.",kr:"우리는 아바바를 둘러보았다."},
    {t:4,en:"He showed me Ababa.",kr:"그는 나에게 아바바를 보여주었다."},
    {t:5,en:"They call Ababa the capital.",kr:"그들은 아바바를 수도라고 부른다."}]},
  "aback": {img:"😲", ex5:[
    {t:1,en:"He stepped aback.",kr:"그는 뒤로 물러섰다."},
    {t:2,en:"She stood aback, stunned.",kr:"그녀는 놀라서 움찔한 채 서 있었다."},
    {t:3,en:"The news took us aback.",kr:"그 소식은 우리를 깜짝 놀라게 했다."},
    {t:4,en:"It gave me an aback feeling.",kr:"그것은 나에게 움찔하는 기분을 주었다."},
    {t:5,en:"The shock left him taken aback.",kr:"그 충격은 그를 움찔하게 만들었다."}]},
  "abacus": {img:"🧮", ex5:[
    {t:1,en:"The abacus clicks.",kr:"주판이 딸깍거린다."},
    {t:2,en:"This abacus is old.",kr:"이 주판은 오래되었다."},
    {t:3,en:"I used an abacus.",kr:"나는 주판을 사용했다."},
    {t:4,en:"Grandpa gave me an abacus.",kr:"할아버지는 나에게 주판을 주셨다."},
    {t:5,en:"We found the abacus useful.",kr:"우리는 그 주판이 유용하다는 것을 알았다."}]},
  "abandon": {img:"🚷", ex5:[
    {t:1,en:"They abandoned and fled.",kr:"그들은 버리고 달아났다."},
    {t:2,en:"The plan seems abandoned.",kr:"그 계획은 버려진 것 같다."},
    {t:3,en:"We abandoned the plan.",kr:"우리는 그 계획을 포기했다."},
    {t:4,en:"He left me abandoned hope.",kr:"그는 나에게 버려진 희망만 남겼다."},
    {t:5,en:"They left the house abandoned.",kr:"그들은 그 집을 버려진 채로 두었다."}]},
  "abandoned": {img:"🏚️", ex5:[
    {t:1,en:"The abandoned dog wandered.",kr:"버려진 개가 떠돌았다."},
    {t:2,en:"The house looks abandoned.",kr:"그 집은 버려진 것처럼 보인다."},
    {t:3,en:"We explored the abandoned mill.",kr:"우리는 버려진 방앗간을 탐험했다."},
    {t:4,en:"Time gave the town an abandoned look.",kr:"세월은 그 마을에 버려진 모습을 주었다."},
    {t:5,en:"They left the factory abandoned.",kr:"그들은 그 공장을 버려진 채로 두었다."}]},
  "abandoning": {img:"🏃", ex5:[
    {t:1,en:"They keep abandoning.",kr:"그들은 계속 버리고 있다."},
    {t:2,en:"The act is abandoning by nature.",kr:"그 행위는 본질적으로 포기하는 것이다."},
    {t:3,en:"He is abandoning the ship.",kr:"그는 배를 버리고 있다."},
    {t:4,en:"Abandoning gave us no choice.",kr:"포기하는 것은 우리에게 선택의 여지를 주지 않았다."},
    {t:5,en:"We watched him abandoning the post.",kr:"우리는 그가 자리를 버리는 것을 지켜보았다."}]},
  "abandonment": {img:"🥀", ex5:[
    {t:1,en:"Abandonment hurts.",kr:"버림받음은 아프다."},
    {t:2,en:"The abandonment was total.",kr:"그 버림은 완전했다."},
    {t:3,en:"She feared abandonment.",kr:"그녀는 버림받는 것을 두려워했다."},
    {t:4,en:"Time gave the place an air of abandonment.",kr:"세월은 그곳에 버려진 분위기를 주었다."},
    {t:5,en:"The court called it child abandonment.",kr:"법원은 그것을 아동 유기라고 불렀다."}]},
  "abandons": {img:"🚪", ex5:[
    {t:1,en:"He often abandons.",kr:"그는 자주 포기한다."},
    {t:2,en:"His way abandons reason.",kr:"그의 방식은 이성을 저버린다."},
    {t:3,en:"She abandons the project.",kr:"그녀는 그 프로젝트를 포기한다."},
    {t:4,en:"He abandons us our hope.",kr:"그는 우리에게서 우리의 희망을 앗아간다."},
    {t:5,en:"He abandons the boat empty.",kr:"그는 배를 텅 빈 채로 버린다."}]},
  "abate": {img:"📉", ex5:[
    {t:1,en:"The storm abated.",kr:"폭풍이 잦아들었다."},
    {t:2,en:"The pain grew abated.",kr:"통증이 누그러진 상태가 되었다."},
    {t:3,en:"The law abates the noise.",kr:"그 법은 소음을 줄인다."},
    {t:4,en:"Rest gave the fever an abate.",kr:"휴식은 열을 가라앉혀 주었다."},
    {t:5,en:"We saw the wind abate calm.",kr:"우리는 바람이 잠잠히 잦아드는 것을 보았다."}]},
  "abated": {img:"🌥️", ex5:[
    {t:1,en:"The flood abated.",kr:"홍수가 가라앉았다."},
    {t:2,en:"The fever seemed abated.",kr:"열은 누그러진 것 같았다."},
    {t:3,en:"Medicine abated the pain.",kr:"약이 통증을 가라앉혔다."},
    {t:4,en:"Time gave us abated fears.",kr:"세월은 우리에게 누그러진 두려움을 주었다."},
    {t:5,en:"We found the storm abated.",kr:"우리는 폭풍이 잦아든 것을 알았다."}]},
  "abatement": {img:"🔇", ex5:[
    {t:1,en:"The abatement worked.",kr:"그 완화 조치는 효과가 있었다."},
    {t:2,en:"The abatement is partial.",kr:"그 경감은 부분적이다."},
    {t:3,en:"The city ordered noise abatement.",kr:"시는 소음 경감을 명령했다."},
    {t:4,en:"The plan gave us tax abatement.",kr:"그 계획은 우리에게 세금 감면을 주었다."},
    {t:5,en:"They consider the abatement necessary.",kr:"그들은 그 경감이 필요하다고 여긴다."}]},
  "abba": {img:"🎶", ex5:[
    {t:1,en:"ABBA performed.",kr:"아바가 공연했다."},
    {t:2,en:"ABBA is famous.",kr:"아바는 유명하다."},
    {t:3,en:"I love ABBA.",kr:"나는 아바를 좋아한다."},
    {t:4,en:"She played me ABBA.",kr:"그녀는 나에게 아바 노래를 틀어주었다."},
    {t:5,en:"Fans call ABBA legendary.",kr:"팬들은 아바를 전설적이라고 부른다."}]},
  "abbas": {img:"🧔", ex5:[
    {t:1,en:"Abbas arrived.",kr:"아바스가 도착했다."},
    {t:2,en:"Abbas is a leader.",kr:"아바스는 지도자이다."},
    {t:3,en:"Reporters interviewed Abbas.",kr:"기자들이 아바스를 인터뷰했다."},
    {t:4,en:"They asked Abbas a question.",kr:"그들은 아바스에게 질문을 했다."},
    {t:5,en:"People call Abbas a statesman.",kr:"사람들은 아바스를 정치가라고 부른다."}]},
  "abbey": {img:"⛪", ex5:[
    {t:1,en:"The abbey stands tall.",kr:"그 수도원이 높이 서 있다."},
    {t:2,en:"The abbey is ancient.",kr:"그 수도원은 아주 오래되었다."},
    {t:3,en:"We visited the abbey.",kr:"우리는 그 수도원을 방문했다."},
    {t:4,en:"The monk showed us the abbey.",kr:"수도사는 우리에게 수도원을 보여주었다."},
    {t:5,en:"They kept the abbey sacred.",kr:"그들은 그 수도원을 신성하게 지켰다."}]},
  "abbie": {img:"👧", ex5:[
    {t:1,en:"Abbie laughed.",kr:"애비가 웃었다."},
    {t:2,en:"Abbie is cheerful.",kr:"애비는 명랑하다."},
    {t:3,en:"I called Abbie.",kr:"나는 애비에게 전화했다."},
    {t:4,en:"Abbie gave me a gift.",kr:"애비는 나에게 선물을 주었다."},
    {t:5,en:"We named the kitten Abbie.",kr:"우리는 새끼 고양이를 애비라고 이름 지었다."}]},
  "abbot": {img:"⛪", ex5:[
    {t:1,en:"The abbot prayed.",kr:"수도원장이 기도했다."},
    {t:2,en:"The abbot is wise.",kr:"그 수도원장은 현명하다."},
    {t:3,en:"We met the abbot.",kr:"우리는 수도원장을 만났다."},
    {t:4,en:"The monk brought the abbot tea.",kr:"수도사는 수도원장에게 차를 가져다주었다."},
    {t:5,en:"They elected him abbot.",kr:"그들은 그를 수도원장으로 선출했다."}]},
  "abbott": {img:"🧑", ex5:[
    {t:1,en:"Abbott arrived early.",kr:"애벗이 일찍 도착했다."},
    {t:2,en:"Abbott is reliable.",kr:"애벗은 믿을 만하다."},
    {t:3,en:"I phoned Abbott.",kr:"나는 애벗에게 전화했다."},
    {t:4,en:"Abbott sent me a note.",kr:"애벗은 나에게 쪽지를 보냈다."},
    {t:5,en:"We call him Abbott.",kr:"우리는 그를 애벗이라고 부른다."}]},
  "abbreviate": {img:"✂️", ex5:[
    {t:1,en:"Editors abbreviate freely.",kr:"편집자들은 자유롭게 줄여 쓴다."},
    {t:2,en:"The word stays abbreviated.",kr:"그 단어는 줄여진 채로 있다."},
    {t:3,en:"We abbreviate long titles.",kr:"우리는 긴 제목을 줄인다."},
    {t:4,en:"He showed me how to abbreviate it.",kr:"그는 나에게 그것을 줄이는 법을 보여주었다."},
    {t:5,en:"They abbreviate the name short.",kr:"그들은 그 이름을 짧게 줄인다."}]},
  "abbreviated": {img:"🔡", ex5:[
    {t:1,en:"The list abbreviated nicely.",kr:"그 목록은 깔끔하게 줄었다."},
    {t:2,en:"The text looks abbreviated.",kr:"그 글은 축약된 것처럼 보인다."},
    {t:3,en:"I read the abbreviated version.",kr:"나는 축약본을 읽었다."},
    {t:4,en:"She gave me an abbreviated summary.",kr:"그녀는 나에게 축약된 요약을 주었다."},
    {t:5,en:"We kept the report abbreviated.",kr:"우리는 그 보고서를 축약된 채로 두었다."}]},
  "abbreviation": {img:"🔠", ex5:[
    {t:1,en:"The abbreviation stuck.",kr:"그 약어가 굳어졌다."},
    {t:2,en:"This abbreviation is common.",kr:"이 약어는 흔하다."},
    {t:3,en:"I learned the abbreviation.",kr:"나는 그 약어를 익혔다."},
    {t:4,en:"He taught me an abbreviation.",kr:"그는 나에게 약어 하나를 가르쳐 주었다."},
    {t:5,en:"We consider the abbreviation handy.",kr:"우리는 그 약어가 편리하다고 여긴다."}]},
  "abc": {img:"🔤", ex5:[
    {t:1,en:"The ABCs come first.",kr:"기초가 먼저 온다."},
    {t:2,en:"The ABC is simple.",kr:"기초는 간단하다."},
    {t:3,en:"Children learn the ABC.",kr:"아이들은 기초를 배운다."},
    {t:4,en:"The teacher taught us the ABC.",kr:"선생님은 우리에게 기초를 가르쳐 주셨다."},
    {t:5,en:"We call it as easy as ABC.",kr:"우리는 그것을 아주 쉽다고 말한다."}]},
  "abdomen": {img:"🫃", ex5:[
    {t:1,en:"The abdomen aches.",kr:"배가 아프다."},
    {t:2,en:"The abdomen feels tight.",kr:"배가 단단하게 느껴진다."},
    {t:3,en:"The doctor examined the abdomen.",kr:"의사가 복부를 진찰했다."},
    {t:4,en:"Exercise gave me a firm abdomen.",kr:"운동은 나에게 탄탄한 배를 주었다."},
    {t:5,en:"We found the abdomen swollen.",kr:"우리는 복부가 부어 있는 것을 발견했다."}]},
  "abdominal": {img:"🩻", ex5:[
    {t:1,en:"Abdominal pains spread.",kr:"복부 통증이 퍼졌다."},
    {t:2,en:"The abdominal area is sore.",kr:"복부 부위가 쓰리다."},
    {t:3,en:"She does abdominal exercises.",kr:"그녀는 복근 운동을 한다."},
    {t:4,en:"The trainer taught me abdominal moves.",kr:"트레이너는 나에게 복근 동작을 가르쳐 주었다."},
    {t:5,en:"Doctors keep the abdominal wall stable.",kr:"의사들은 복벽을 안정되게 유지한다."}]},
  "abduct": {img:"🚨", ex5:[
    {t:1,en:"The kidnappers abduct and vanish.",kr:"납치범들은 납치하고 사라진다."},
    {t:2,en:"To abduct is criminal.",kr:"납치하는 것은 범죄이다."},
    {t:3,en:"They tried to abduct the child.",kr:"그들은 그 아이를 납치하려 했다."},
    {t:4,en:"The threat gave us an abduct warning.",kr:"그 위협은 우리에게 납치 경고를 주었다."},
    {t:5,en:"Police feared they would abduct her gone.",kr:"경찰은 그들이 그녀를 납치해 사라지게 할까 봐 두려워했다."}]},
  "abduction": {img:"🆘", ex5:[
    {t:1,en:"The abduction shocked all.",kr:"그 납치 사건은 모두를 충격에 빠뜨렸다."},
    {t:2,en:"The abduction was sudden.",kr:"그 납치는 갑작스러웠다."},
    {t:3,en:"Police investigated the abduction.",kr:"경찰이 그 납치 사건을 수사했다."},
    {t:4,en:"The case gave the town an abduction scare.",kr:"그 사건은 마을에 납치 공포를 안겼다."},
    {t:5,en:"The court called it an abduction.",kr:"법원은 그것을 납치라고 불렀다."}]},
  "abe": {img:"🎩", ex5:[
    {t:1,en:"Abe spoke up.",kr:"에이브가 말을 꺼냈다."},
    {t:2,en:"Abe was honest.",kr:"에이브는 정직했다."},
    {t:3,en:"History remembers Abe.",kr:"역사는 에이브를 기억한다."},
    {t:4,en:"They gave Abe a nickname.",kr:"그들은 에이브에게 별명을 지어주었다."},
    {t:5,en:"People called Abe honest.",kr:"사람들은 에이브를 정직하다고 불렀다."}]},
  "abel": {img:"🧑", ex5:[
    {t:1,en:"Abel worked hard.",kr:"아벨은 열심히 일했다."},
    {t:2,en:"Abel was a shepherd.",kr:"아벨은 양치기였다."},
    {t:3,en:"The story names Abel.",kr:"그 이야기는 아벨을 언급한다."},
    {t:4,en:"They offered Abel a gift.",kr:"그들은 아벨에게 선물을 바쳤다."},
    {t:5,en:"They named the boy Abel.",kr:"그들은 그 소년을 아벨이라고 이름 지었다."}]},
  "aberdeen": {img:"🏴", ex5:[
    {t:1,en:"Aberdeen lies on the coast.",kr:"애버딘은 해안에 있다."},
    {t:2,en:"Aberdeen is gray and grand.",kr:"애버딘은 잿빛이고 웅장하다."},
    {t:3,en:"We visited Aberdeen.",kr:"우리는 애버딘을 방문했다."},
    {t:4,en:"The guide showed us Aberdeen.",kr:"가이드는 우리에게 애버딘을 보여주었다."},
    {t:5,en:"They call Aberdeen the granite city.",kr:"사람들은 애버딘을 화강암 도시라고 부른다."}]},
  "aberration": {img:"🌀", ex5:[
    {t:1,en:"The aberration passed.",kr:"그 이상 현상은 지나갔다."},
    {t:2,en:"The result seems an aberration.",kr:"그 결과는 이례적인 것처럼 보인다."},
    {t:3,en:"Scientists noted the aberration.",kr:"과학자들이 그 이상 현상을 기록했다."},
    {t:4,en:"The data gave us one aberration.",kr:"그 데이터는 우리에게 한 가지 이상치를 주었다."},
    {t:5,en:"We consider the spike an aberration.",kr:"우리는 그 급등을 이례적인 것으로 여긴다."}]},
  "abes": {img:"🎩", ex5:[
    {t:1,en:"The Abes gathered.",kr:"에이브 가족이 모였다."},
    {t:2,en:"The Abes are famous.",kr:"그 에이브 가문은 유명하다."},
    {t:3,en:"We invited the Abes.",kr:"우리는 에이브 가족을 초대했다."},
    {t:4,en:"He showed the Abes the house.",kr:"그는 에이브 가족에게 그 집을 보여주었다."},
    {t:5,en:"People call them the Abes.",kr:"사람들은 그들을 에이브 가족이라고 부른다."}]},
  "abide": {img:"🪨", ex5:[
    {t:1,en:"Old customs abide.",kr:"오랜 관습이 지속된다."},
    {t:2,en:"The rule stays abiding.",kr:"그 규칙은 변함없이 남는다."},
    {t:3,en:"I cannot abide rudeness.",kr:"나는 무례함을 참을 수 없다."},
    {t:4,en:"Faith gave us an abide-by code.",kr:"믿음은 우리에게 지켜야 할 규범을 주었다."},
    {t:5,en:"We abide the rules firm.",kr:"우리는 그 규칙을 굳게 지킨다."}]},
  "abiding": {img:"♾️", ex5:[
    {t:1,en:"Her love abiding stays.",kr:"그녀의 변치 않는 사랑이 남는다."},
    {t:2,en:"The faith is abiding.",kr:"그 믿음은 변함없다."},
    {t:3,en:"He kept an abiding hope.",kr:"그는 변치 않는 희망을 품었다."},
    {t:4,en:"Time gave them an abiding bond.",kr:"세월은 그들에게 변치 않는 유대를 주었다."},
    {t:5,en:"We found their friendship abiding.",kr:"우리는 그들의 우정이 변함없음을 알았다."}]},
  "abigail": {img:"👩", ex5:[
    {t:1,en:"Abigail sang.",kr:"애비게일이 노래했다."},
    {t:2,en:"Abigail is graceful.",kr:"애비게일은 우아하다."},
    {t:3,en:"I greeted Abigail.",kr:"나는 애비게일에게 인사했다."},
    {t:4,en:"Abigail gave me advice.",kr:"애비게일은 나에게 조언을 해주었다."},
    {t:5,en:"We named the girl Abigail.",kr:"우리는 그 소녀를 애비게일이라고 이름 지었다."}]},
  "abilities": {img:"🧠", ex5:[
    {t:1,en:"Her abilities shine.",kr:"그녀의 능력이 빛난다."},
    {t:2,en:"His abilities are rare.",kr:"그의 능력은 드물다."},
    {t:3,en:"We test their abilities.",kr:"우리는 그들의 능력을 시험한다."},
    {t:4,en:"Training gave us new abilities.",kr:"훈련은 우리에게 새로운 능력을 주었다."},
    {t:5,en:"We consider her abilities exceptional.",kr:"우리는 그녀의 능력이 뛰어나다고 여긴다."}]},
  "ability": {img:"💪", ex5:[
    {t:1,en:"His ability stands out.",kr:"그의 능력이 두드러진다."},
    {t:2,en:"Her ability is remarkable.",kr:"그녀의 능력은 놀랍다."},
    {t:3,en:"I admire your ability.",kr:"나는 너의 능력에 감탄한다."},
    {t:4,en:"Practice gave me the ability.",kr:"연습은 나에게 그 능력을 주었다."},
    {t:5,en:"We consider ability essential.",kr:"우리는 능력이 필수적이라고 여긴다."}]},
  "ablaze": {img:"🔥", ex5:[
    {t:1,en:"The barn was ablaze.",kr:"헛간이 불타올랐다."},
    {t:2,en:"The sky looked ablaze.",kr:"하늘이 불타는 듯 보였다."},
    {t:3,en:"The torch set the field ablaze.",kr:"횃불이 들판을 불바다로 만들었다."},
    {t:4,en:"Sunset gave the hills an ablaze glow.",kr:"노을은 언덕에 불타는 듯한 빛을 주었다."},
    {t:5,en:"The flames left the house ablaze.",kr:"불길은 그 집을 활활 타오르게 했다."}]},
  "able": {img:"💪", ex5:[
    {t:1,en:"The able worker excels.",kr:"유능한 일꾼이 뛰어나다."},
    {t:2,en:"She is able.",kr:"그녀는 유능하다."},
    {t:3,en:"We need able hands.",kr:"우리는 유능한 일손이 필요하다."},
    {t:4,en:"Training made him an able pilot.",kr:"훈련은 그를 유능한 조종사로 만들었다."},
    {t:5,en:"We consider her able and ready.",kr:"우리는 그녀가 유능하고 준비됐다고 여긴다."}]},
  "ably": {img:"👍", ex5:[
    {t:1,en:"She performed ably.",kr:"그녀는 훌륭히 해냈다."},
    {t:2,en:"His work seems ably done.",kr:"그의 작업은 능숙하게 된 것 같다."},
    {t:3,en:"He led the team ably.",kr:"그는 팀을 능숙하게 이끌었다."},
    {t:4,en:"She ably gave us guidance.",kr:"그녀는 우리에게 능숙하게 지도를 해주었다."},
    {t:5,en:"They kept the project ably managed.",kr:"그들은 그 프로젝트를 능숙하게 관리되도록 유지했다."}]},
  "abnormal": {img:"⚠️", ex5:[
    {t:1,en:"The readings turned abnormal.",kr:"수치가 비정상이 되었다."},
    {t:2,en:"The result looks abnormal.",kr:"그 결과는 비정상으로 보인다."},
    {t:3,en:"Doctors found abnormal cells.",kr:"의사들이 비정상 세포를 발견했다."},
    {t:4,en:"The test gave us abnormal numbers.",kr:"그 검사는 우리에게 비정상적인 수치를 주었다."},
    {t:5,en:"We consider the pattern abnormal.",kr:"우리는 그 패턴을 비정상이라고 여긴다."}]},
  "abnormalities": {img:"🧬", ex5:[
    {t:1,en:"Abnormalities appeared.",kr:"이상들이 나타났다."},
    {t:2,en:"The abnormalities are minor.",kr:"그 이상들은 경미하다."},
    {t:3,en:"Scans revealed abnormalities.",kr:"검사는 이상들을 드러냈다."},
    {t:4,en:"The report gave us several abnormalities.",kr:"그 보고서는 우리에게 여러 이상을 알려주었다."},
    {t:5,en:"Doctors found the abnormalities harmless.",kr:"의사들은 그 이상들이 무해하다는 것을 알았다."}]},
  "abnormality": {img:"🔬", ex5:[
    {t:1,en:"An abnormality showed up.",kr:"이상 하나가 나타났다."},
    {t:2,en:"The abnormality is slight.",kr:"그 이상은 미미하다."},
    {t:3,en:"The scan detected an abnormality.",kr:"검사가 이상을 감지했다."},
    {t:4,en:"The test gave us an abnormality alert.",kr:"그 검사는 우리에게 이상 경고를 주었다."},
    {t:5,en:"We found the abnormality treatable.",kr:"우리는 그 이상이 치료 가능하다는 것을 알았다."}]},
  "abnormally": {img:"📈", ex5:[
    {t:1,en:"Prices rose abnormally.",kr:"가격이 비정상적으로 올랐다."},
    {t:2,en:"The day felt abnormally warm.",kr:"그날은 비정상적으로 따뜻하게 느껴졌다."},
    {t:3,en:"He showed abnormally fast growth.",kr:"그는 비정상적으로 빠른 성장을 보였다."},
    {t:4,en:"The heat gave us an abnormally long summer.",kr:"더위는 우리에게 비정상적으로 긴 여름을 안겼다."},
    {t:5,en:"We found the engine running abnormally hot.",kr:"우리는 엔진이 비정상적으로 뜨겁게 도는 것을 발견했다."}]},
  "aboard": {img:"🚢", ex5:[
    {t:1,en:"Passengers climbed aboard.",kr:"승객들이 올라탔다."},
    {t:2,en:"Everyone is aboard.",kr:"모두가 탑승해 있다."},
    {t:3,en:"We welcomed them aboard.",kr:"우리는 그들의 탑승을 환영했다."},
    {t:4,en:"The captain gave us an aboard signal.",kr:"선장은 우리에게 탑승 신호를 주었다."},
    {t:5,en:"We had everyone aboard safe.",kr:"우리는 모두를 안전하게 탑승시켰다."}]},
  "abode": {img:"🏠", ex5:[
    {t:1,en:"The abode stands quiet.",kr:"그 거처는 고요히 서 있다."},
    {t:2,en:"This abode is humble.",kr:"이 거처는 소박하다."},
    {t:3,en:"They built an abode.",kr:"그들은 거처를 지었다."},
    {t:4,en:"He offered us his abode.",kr:"그는 우리에게 자기 거처를 내주었다."},
    {t:5,en:"We kept the abode warm.",kr:"우리는 그 거처를 따뜻하게 유지했다."}]},
  "abolish": {img:"🚫", ex5:[
    {t:1,en:"Reformers abolish and rebuild.",kr:"개혁가들은 폐지하고 다시 세운다."},
    {t:2,en:"The law is hard to abolish.",kr:"그 법은 폐지하기 어렵다."},
    {t:3,en:"They voted to abolish the tax.",kr:"그들은 그 세금을 폐지하기로 표결했다."},
    {t:4,en:"The reform gave us a chance to abolish slavery.",kr:"그 개혁은 우리에게 노예제를 폐지할 기회를 주었다."},
    {t:5,en:"They abolish the rule dead.",kr:"그들은 그 규칙을 완전히 폐지한다."}]},
  "abolished": {img:"⛓️", ex5:[
    {t:1,en:"Slavery was abolished.",kr:"노예제가 폐지되었다."},
    {t:2,en:"The custom seems abolished.",kr:"그 관습은 폐지된 것 같다."},
    {t:3,en:"They abolished the old law.",kr:"그들은 낡은 법을 폐지했다."},
    {t:4,en:"Reform gave us an abolished tax.",kr:"개혁은 우리에게 폐지된 세금을 안겼다."},
    {t:5,en:"They left the rule abolished.",kr:"그들은 그 규칙을 폐지된 채로 두었다."}]},
  "abolishing": {img:"🗳️", ex5:[
    {t:1,en:"They keep abolishing.",kr:"그들은 계속 폐지하고 있다."},
    {t:2,en:"The act is abolishing by design.",kr:"그 행위는 의도적으로 폐지하는 것이다."},
    {t:3,en:"They are abolishing the fee.",kr:"그들은 그 수수료를 폐지하고 있다."},
    {t:4,en:"Abolishing gave us new freedom.",kr:"폐지는 우리에게 새로운 자유를 주었다."},
    {t:5,en:"We watched them abolishing the ban.",kr:"우리는 그들이 그 금지를 폐지하는 것을 지켜보았다."}]},
  "abolition": {img:"📜", ex5:[
    {t:1,en:"Abolition arrived.",kr:"폐지가 이루어졌다."},
    {t:2,en:"The abolition was historic.",kr:"그 폐지는 역사적이었다."},
    {t:3,en:"They demanded abolition.",kr:"그들은 폐지를 요구했다."},
    {t:4,en:"The movement gave us abolition.",kr:"그 운동은 우리에게 폐지를 가져다주었다."},
    {t:5,en:"History calls it the abolition.",kr:"역사는 그것을 폐지라고 부른다."}]},
  "abolitionist": {img:"✊", ex5:[
    {t:1,en:"The abolitionist spoke.",kr:"폐지론자가 연설했다."},
    {t:2,en:"The abolitionist was brave.",kr:"그 폐지론자는 용감했다."},
    {t:3,en:"History honors the abolitionist.",kr:"역사는 그 폐지론자를 기린다."},
    {t:4,en:"They gave the abolitionist a platform.",kr:"그들은 그 폐지론자에게 발언대를 주었다."},
    {t:5,en:"People called him an abolitionist.",kr:"사람들은 그를 폐지론자라고 불렀다."}]},
  "abominable": {img:"🥶", ex5:[
    {t:1,en:"The weather turned abominable.",kr:"날씨가 끔찍해졌다."},
    {t:2,en:"The food was abominable.",kr:"그 음식은 형편없었다."},
    {t:3,en:"We endured abominable cold.",kr:"우리는 끔찍한 추위를 견뎠다."},
    {t:4,en:"The storm gave us an abominable night.",kr:"폭풍은 우리에게 끔찍한 밤을 안겼다."},
    {t:5,en:"We found the service abominable.",kr:"우리는 그 서비스가 형편없다는 것을 알았다."}]},
  "abomination": {img:"😖", ex5:[
    {t:1,en:"The abomination spread.",kr:"그 혐오스러운 것이 퍼졌다."},
    {t:2,en:"The act is an abomination.",kr:"그 행위는 혐오스러운 짓이다."},
    {t:3,en:"They condemned the abomination.",kr:"그들은 그 혐오스러운 행위를 규탄했다."},
    {t:4,en:"The deed gave the town an abomination to face.",kr:"그 짓은 마을에 마주할 혐오스러운 일을 안겼다."},
    {t:5,en:"They called the crime an abomination.",kr:"그들은 그 범죄를 혐오스러운 짓이라고 불렀다."}]},
  "aboriginal": {img:"🪃", ex5:[
    {t:1,en:"Aboriginal traditions endure.",kr:"원주민 전통이 이어진다."},
    {t:2,en:"The art is aboriginal.",kr:"그 예술은 원주민의 것이다."},
    {t:3,en:"We studied aboriginal culture.",kr:"우리는 원주민 문화를 공부했다."},
    {t:4,en:"The elder taught us aboriginal lore.",kr:"어르신은 우리에게 원주민 전승을 가르쳐 주었다."},
    {t:5,en:"We consider aboriginal art priceless.",kr:"우리는 원주민 예술을 값을 매길 수 없다고 여긴다."}]},
  "aborigine": {img:"🌏", ex5:[
    {t:1,en:"The aborigine danced.",kr:"원주민이 춤을 췄다."},
    {t:2,en:"The aborigine is proud.",kr:"그 원주민은 자긍심이 있다."},
    {t:3,en:"We met an aborigine.",kr:"우리는 한 원주민을 만났다."},
    {t:4,en:"The aborigine taught us a song.",kr:"그 원주민은 우리에게 노래를 가르쳐 주었다."},
    {t:5,en:"We found the aborigine welcoming.",kr:"우리는 그 원주민이 친절하다는 것을 알았다."}]},
  "abort": {img:"🛑", ex5:[
    {t:1,en:"The engines abort.",kr:"엔진이 작동을 중단한다."},
    {t:2,en:"The launch went abort.",kr:"발사가 중단되었다."},
    {t:3,en:"They had to abort the mission.",kr:"그들은 임무를 중단해야 했다."},
    {t:4,en:"Control gave us an abort order.",kr:"관제소는 우리에게 중단 명령을 내렸다."},
    {t:5,en:"They abort the flight grounded.",kr:"그들은 그 비행을 중단해 지상에 묶어 두었다."}]},
  "aborted": {img:"❌", ex5:[
    {t:1,en:"The mission aborted.",kr:"임무가 중단되었다."},
    {t:2,en:"The plan looks aborted.",kr:"그 계획은 중단된 것처럼 보인다."},
    {t:3,en:"They aborted the takeoff.",kr:"그들은 이륙을 중단했다."},
    {t:4,en:"The fault gave us an aborted launch.",kr:"그 결함은 우리에게 중단된 발사를 안겼다."},
    {t:5,en:"We found the attempt aborted.",kr:"우리는 그 시도가 중단된 것을 알았다."}]},
});
