// ── ButterFly Word Dictionary : 한국어 뜻 + 예문 (검수 코어, 다의어) ──
// key=영단어, value={kr,ex}. 발음은 bwd-pron.js가 채움. ';'로 의미 묶음, ','로 유사 뜻.
const BWD_DICT = {
  "time": {kr:"시간, 때; 시각; ~번, 회; 시대", ex:"What time is it now?"},
  "people": {kr:"사람들; 국민, 민족; 일반 대중", ex:"Many people came."},
  "way": {kr:"방법, 방식; 길, 도로; 방향, 쪽", ex:"This is the best way."},
  "day": {kr:"날, 하루; 낮, 주간; 시절, 시대", ex:"Have a nice day!"},
  "man": {kr:"남자; 인간, 사람; 인류", ex:"The man is reading."},
  "thing": {kr:"것, 물건; 일, 사건; 상황; 소지품", ex:"That is a strange thing."},
  "woman": {kr:"여자; 여성", ex:"The woman works here."},
  "life": {kr:"삶, 인생; 생명; 생활; 활기, 생기", ex:"Life is full of surprises."},
  "child": {kr:"아이, 어린이; 자식", ex:"The child is playing."},
  "world": {kr:"세계, 세상; 지구; ~계, 분야", ex:"Travel the world."},
  "school": {kr:"학교; 수업; 학파; (물고기) 떼", ex:"He goes to school."},
  "family": {kr:"가족; 가문; (생물) 과", ex:"I love my family."},
  "student": {kr:"학생; 연구자", ex:"She is a good student."},
  "country": {kr:"나라, 국가; 시골; 지역; 국민", ex:"A beautiful country."},
  "problem": {kr:"문제, 어려움", ex:"Solve this problem."},
  "question": {kr:"질문; 문제, 사안; 의문; 심문하다", ex:"Ask a question."},
  "work": {kr:"일하다; (기계가) 작동하다; 효과가 있다; 일, 노동; 직장; 작품", ex:"I work from nine to six."},
  "place": {kr:"장소, 곳; 자리; 입장; 순위; 놓다", ex:"A quiet place."},
  "week": {kr:"주, 일주일; 주중", ex:"See you next week."},
  "year": {kr:"해, 연도; 1년; 오랜 세월; 학년", ex:"Last year was busy."},
  "money": {kr:"돈, 금전; 재산; 통화", ex:"He saved money."},
  "story": {kr:"이야기, 소설; 줄거리; 기사; (건물) 층", ex:"A funny story."},
  "month": {kr:"달, 월; 한 달", ex:"Last month it rained."},
  "book": {kr:"책; 권, 편; 예약하다; 장부", ex:"I read a book."},
  "water": {kr:"물; 수면; 물을 주다", ex:"Drink more water."},
  "room": {kr:"방, 실; 공간, 여지", ex:"My room is cozy."},
  "friend": {kr:"친구, 벗; 지지자; 동료", ex:"My best friend."},
  "house": {kr:"집, 주택; 가정; 의회; 관객", ex:"A big house."},
  "city": {kr:"도시, 시; 금융 중심지", ex:"Seoul is busy."},
  "name": {kr:"이름; 명칭; 명성; 이름을 짓다", ex:"What is your name?"},
  "night": {kr:"밤, 야간; 저녁; 어둠", ex:"Late at night."},
  "food": {kr:"음식, 식품; 먹이; 양식", ex:"Korean food is great."},
  "car": {kr:"자동차; (기차) 객차, 칸", ex:"She drives a car."},
  "word": {kr:"단어; 말, 이야기; 약속; 한마디; 소식", ex:"I don't know this word."},
  "company": {kr:"회사, 기업; 동행, 함께 있음; 일행, 동료; (군대) 중대", ex:"He works for a company."},
  "number": {kr:"숫자, 수; 번호; 수량, 다수; (잡지) 호", ex:"Call this number."},
  "group": {kr:"집단, 무리; (회사) 그룹; 무리 짓다", ex:"A small group."},
  "part": {kr:"부분, 일부; 부품; 역할, 배역; 편, 권; 갈라지다", ex:"The hardest part."},
  "case": {kr:"경우, 사례; 사건, 소송; 환자; 주장; 상자, 케이스", ex:"In that case."},
  "point": {kr:"점, 지점; 요점, 핵심; 시점; 점수; 가리키다", ex:"A good point."},
  "government": {kr:"정부, 행정부; 정치, 통치; 내각", ex:"The government acts."},
  "right": {kr:"옳은, 올바른; 정확한; 오른쪽(의); 권리; 바로, 즉시", ex:"The right choice."},
  "study": {kr:"공부하다; 연구하다; 자세히 살피다; 연구; 서재", ex:"I study English."},
  "job": {kr:"일자리, 직업; 일, 업무; 책무, 역할", ex:"She got a new job."},
  "business": {kr:"사업, 장사; 회사; 업무; 관심사, 소관; 거래", ex:"His own business."},
  "system": {kr:"체계, 시스템; 제도; 조직; (신체) 계통", ex:"The new system works."},
  "program": {kr:"프로그램; 계획, 일정; (방송) 프로; 프로그램을 짜다", ex:"A useful program."},
  "service": {kr:"서비스, 접대; 봉사, 근무; 예배; (테니스) 서브; 점검", ex:"Great service."},
  "health": {kr:"건강; 보건, 의료; 상태", ex:"Good for your health."},
  "history": {kr:"역사; 내력, 경력; 병력; 사학", ex:"I enjoy history."},
  "music": {kr:"음악; 악보; 음악 작품", ex:"She loves music."},
  "art": {kr:"예술, 미술; 작품; 기술, 기예; (arts) 인문학", ex:"Modern art."},
  "love": {kr:"사랑; 애정; 연인; (테니스) 무득점; 사랑하다", ex:"They fell in love."},
  "power": {kr:"힘, 능력; 권력; 세력, 강대국; 전력, 동력; (수학) 거듭제곱", ex:"The storm cut the power."},
  "war": {kr:"전쟁; 싸움; 투쟁; 경쟁", ex:"The war lasted years."},
  "team": {kr:"팀, 단체; 조; 한 무리; 팀을 짜다", ex:"Our team won."},
  "game": {kr:"경기, 시합; 놀이, 게임; 사냥감; 술수, 책략", ex:"Let's play a game."},
  "head": {kr:"머리; 우두머리, 책임자; 앞부분; ~당; 향하다; 이끌다", ex:"My head hurts."},
  "hand": {kr:"손; (시계) 바늘; 일손; 도움; 건네주다", ex:"Raise your hand."},
  "eye": {kr:"눈; 시력; 안목; (태풍의) 눈; 바늘귀", ex:"Blue eyes."},
  "face": {kr:"얼굴; 표정; 표면, 정면; 체면; 직면하다", ex:"Wash your face."},
  "body": {kr:"몸, 신체; 시체; 본체; 단체, 집단; 차체", ex:"Stretch your body."},
  "heart": {kr:"심장; 마음, 가슴; 애정; 용기; 핵심; (카드) 하트", ex:"My heart was racing."},
  "mother": {kr:"어머니, 엄마; 근원; 어머니처럼 돌보다", ex:"My mother cooks well."},
  "father": {kr:"아버지, 아빠; 창시자; 신부; 조상", ex:"His father is a teacher."},
  "parent": {kr:"부모; 모체, 근원", ex:"My parents live in Busan."},
  "baby": {kr:"아기; 막내; 응석받이; 애지중지하다", ex:"The baby is sleeping."},
  "girl": {kr:"소녀, 여자아이; 딸; 젊은 여성", ex:"The girl is drawing."},
  "boy": {kr:"소년, 남자아이; 아들; 젊은 남성", ex:"The boy kicked the ball."},
  "morning": {kr:"아침, 오전; 새벽; 초기", ex:"Every morning."},
  "today": {kr:"오늘; 현재, 오늘날", ex:"Today is my birthday."},
  "tomorrow": {kr:"내일; 미래", ex:"See you tomorrow."},
  "yesterday": {kr:"어제; 과거", ex:"It rained yesterday."},
  "hour": {kr:"시간(60분); 시각; 시기; 근무 시간", ex:"Two hours."},
  "minute": {kr:"분; 잠깐, 순간; 회의록; 미세한", ex:"Wait a minute."},
  "light": {kr:"빛, 광선; 전등, 불; 가벼운; 밝은; (색이) 연한; 불을 켜다", ex:"Turn off the light."},
  "color": {kr:"색, 색깔; 안색; 물감; 생기; 색칠하다", ex:"My favorite color."},
  "door": {kr:"문, 출입구; 문간; 입구", ex:"Close the door."},
  "window": {kr:"창문, 창; (컴퓨터) 창; 진열창; 짧은 시기", ex:"Open the window."},
  "table": {kr:"탁자, 식탁; 표, 도표; 사람들; 미루다", ex:"On the table."},
  "phone": {kr:"전화(기); 수화기; 전화하다", ex:"My phone is dead."},
  "computer": {kr:"컴퓨터; 전산기", ex:"He fixed my computer."},
  "street": {kr:"거리, 도로; 일반 대중; ~가(街)", ex:"The street is full of cars."},
  "tree": {kr:"나무, 수목; 계통도, 트리", ex:"A bird sat on the tree."},
  "animal": {kr:"동물, 짐승; 짐승 같은 사람; 동물의", ex:"My favorite animal."},
  "dog": {kr:"개; 수캐; 끈질기게 따라다니다", ex:"The dog is barking."},
  "cat": {kr:"고양이; 고양잇과 동물", ex:"The cat is sleeping."},
  "fish": {kr:"물고기, 생선; 어류; 낚시하다", ex:"We had fish for dinner."},
  "bird": {kr:"새, 조류", ex:"A bird is singing."},
  "flower": {kr:"꽃; 개화; 정수; 꽃이 피다", ex:"She gave me a flower."},
  "sun": {kr:"태양, 해; 햇빛, 양지; 항성", ex:"The sun is bright."},
  "moon": {kr:"달; 위성; 멍하니 보내다", ex:"The moon is full."},
  "sea": {kr:"바다, 해양; 파도; 다량", ex:"We swam in the sea."},
  "river": {kr:"강, 하천; 강물", ex:"The river flows."},
  "mountain": {kr:"산; 산더미, 다량", ex:"They climbed the mountain."},
  "sky": {kr:"하늘, 공중; 날씨", ex:"The sky is blue."},
  "rain": {kr:"비; 빗물; 비가 오다; 쏟아지다", ex:"The rain stopped."},
  "snow": {kr:"눈; 적설; 눈이 오다", ex:"Play in the snow."},
  "wind": {kr:"바람; 입김; 낌새; 관악기; 감다", ex:"The wind is strong."},
  "fire": {kr:"불, 화재; 발포, 사격; 열정; 불을 지르다; 발사하다; 해고하다", ex:"Around the fire."},
  "make": {kr:"만들다; ~하게 하다; (돈을) 벌다; (총계가) 되다; 도달하다", ex:"Let's make a cake."},
  "take": {kr:"가지다, 잡다; 데려가다; (시간이) 걸리다; 받아들이다; (교통수단을) 타다; 복용하다", ex:"Take an umbrella."},
  "give": {kr:"주다, 건네다; 제공하다; (행사를) 열다; 양보하다, 휘다", ex:"Give me a hand."},
  "get": {kr:"얻다, 받다; 가져오다; ~되다; 이해하다; 도착하다; (병에) 걸리다", ex:"Get some sleep."},
  "go": {kr:"가다, 향하다; 진행되다; (기계가) 작동하다; (상태가) 되다; 사라지다", ex:"Let's go."},
  "come": {kr:"오다, 도착하다; (상태가) 되다; 떠오르다; 유래하다", ex:"Come here."},
  "see": {kr:"보다; 알다, 이해하다; 만나다; 확인하다; 배웅하다", ex:"I see the mountain."},
  "look": {kr:"보다, 바라보다; ~처럼 보이다; 향하다; 찾아보다; 표정; 외모", ex:"Look at the sky."},
  "know": {kr:"알다; 이해하다; 식별하다; 친분이 있다", ex:"I know the answer."},
  "think": {kr:"생각하다; ~라고 여기다; 상상하다; 기억해 내다", ex:"I think you are right."},
  "want": {kr:"원하다; 필요로 하다; ~해 주길 바라다; 부족", ex:"I want tea."},
  "need": {kr:"필요하다; ~해야 한다; 필요, 요구; 곤궁", ex:"You need rest."},
  "find": {kr:"찾다, 발견하다; 알아내다; ~라고 여기다; 판결하다", ex:"I can't find my keys."},
  "tell": {kr:"말하다; 알려주다; 구별하다; 명령하다", ex:"Tell me the truth."},
  "ask": {kr:"묻다, 질문하다; 부탁하다; 청하다, 초대하다", ex:"May I ask a favor?"},
  "say": {kr:"말하다; (글에) ~라고 적혀 있다; 표현하다; 가령", ex:"What did you say?"},
  "talk": {kr:"이야기하다; 대화하다; 의논하다; 대화; 강연; 소문", ex:"Let's talk."},
  "speak": {kr:"말하다; (언어를) 구사하다; 연설하다; 통화하다", ex:"Do you speak English?"},
  "read": {kr:"읽다; 낭독하다; 이해하다; (계기가) 표시하다; 전공하다", ex:"She reads daily."},
  "write": {kr:"쓰다, 적다; 집필하다; 작곡하다; 편지를 쓰다", ex:"Write your name."},
  "learn": {kr:"배우다; 알게 되다; 외우다", ex:"Learn Spanish."},
  "teach": {kr:"가르치다; 깨우치다; 길들이다", ex:"She teaches math."},
  "play": {kr:"놀다; (경기를) 하다; (악기를) 연주하다; (역을) 연기하다; 재생하다; 연극", ex:"The kids play."},
  "run": {kr:"달리다; 운영하다, 경영하다; (기계가) 작동하다; (액체가) 흐르다; 출마하다; 운행하다", ex:"He runs every morning."},
  "walk": {kr:"걷다, 산책하다; 데리고 걷다; 걸음; 산책", ex:"Let's walk."},
  "eat": {kr:"먹다, 식사하다; 침식하다; 잠식하다", ex:"What did you eat?"},
  "drink": {kr:"마시다; 술을 마시다; 흡수하다; 음료; 술", ex:"Drink water."},
  "sleep": {kr:"자다; 숙박하다; 잠; 수면", ex:"I didn't sleep well."},
  "buy": {kr:"사다, 구입하다; 믿다; 매수하다; 싼 물건", ex:"Buy a new phone."},
  "sell": {kr:"팔다; 팔리다; 설득하다; 납득시키다", ex:"They sell fruit."},
  "pay": {kr:"지불하다; (대가를) 치르다; 이익이 되다; 급여; 관심을 기울이다", ex:"I'll pay by card."},
  "open": {kr:"열다, 펼치다; 개업하다; 열려 있는; 개방적인; 미해결의; 공개의", ex:"The store opens at nine."},
  "close": {kr:"닫다; 끝내다; 가까운, 친밀한; 면밀한; 아슬아슬한; 가까이", ex:"Close the door."},
  "start": {kr:"시작하다, 출발하다; (기계를) 작동시키다; 깜짝 놀라다; 시작; 우위", ex:"The movie starts at seven."},
  "stop": {kr:"멈추다; 막다, 방해하다; 머물다; 정지; 정류장", ex:"The bus stopped."},
  "help": {kr:"돕다; (음식을) 덜다; 도움; 가사 도우미", ex:"Can you help me?"},
  "use": {kr:"사용하다; 소비하다; 다루다; 사용; 용도; 효용", ex:"May I use your pen?"},
  "call": {kr:"부르다; 전화하다; ~라고 칭하다; 방문하다; 소집하다; 전화; 결정", ex:"Call me tonight."},
  "feel": {kr:"느끼다; (감정을) 갖다; 만져보다; ~라고 생각하다; 감촉", ex:"I feel happy."},
  "keep": {kr:"유지하다, 계속하다; 보관하다; (약속을) 지키다; 기르다; 부양하다", ex:"Keep the change."},
  "let": {kr:"~하게 하다, 허락하다; ~하자; 세놓다", ex:"Let me think."},
  "live": {kr:"살다, 거주하다; 생존하다; 생활하다; 살아 있는; 생방송의", ex:"I live near the beach."},
  "move": {kr:"움직이다, 이동하다; 이사하다; 감동시키다; 제안하다; 조치; 차례", ex:"They moved to a new city."},
  "turn": {kr:"돌다; (방향을) 바꾸다; ~으로 변하다; 모퉁이를 돌다; 차례, 순번", ex:"Turn left."},
  "change": {kr:"바꾸다, 변하다; 갈아입다; 환승하다; (돈을) 바꾸다; 변화; 잔돈; 거스름돈", ex:"Change our plan."},
  "happen": {kr:"일어나다, 발생하다; 우연히 ~하다; 우연히 마주치다", ex:"What happened?"},
  "meet": {kr:"만나다; 모이다; 맞이하다; (요구를) 충족하다; 만남, 대회", ex:"Let's meet at noon."},
  "wait": {kr:"기다리다; 대기하다; 시중들다; 기다림", ex:"Please wait."},
  "remember": {kr:"기억하다; 잊지 않다; 명심하다; (안부를) 전하다", ex:"I can't remember her name."},
  "forget": {kr:"잊다; 깜빡하다; (걱정을) 떨치다", ex:"Don't forget your umbrella."},
  "understand": {kr:"이해하다; 알아듣다; ~라고 짐작하다", ex:"I understand."},
  "believe": {kr:"믿다; 신뢰하다; ~라고 생각하다; 신앙을 갖다", ex:"I believe you."},
  "hope": {kr:"바라다, 희망하다; 기대하다; 희망, 소망", ex:"I hope you feel better."},
  "enjoy": {kr:"즐기다, 만끽하다; 누리다", ex:"Enjoy your meal."},
  "win": {kr:"이기다, 승리하다; 획득하다; (호감을) 얻다; 승리, 우승", ex:"Our team will win."},
  "lose": {kr:"잃다; (경기에) 지다; (기회를) 놓치다; (시계가) 늦다; 손해 보다", ex:"Don't lose your ticket."},
  "build": {kr:"짓다, 건설하다; 쌓다; 키우다, 늘리다; 체격", ex:"Build a bridge."},
  "break": {kr:"깨다, 부수다; 고장 나다; (약속을) 어기다; 중단하다; 휴식; 틈; 기회", ex:"Don't break it."},
  "carry": {kr:"나르다; 들고 다니다; 지니다; (병을) 옮기다; (가게가) 취급하다", ex:"Carry this bag."},
  "bring": {kr:"가져오다, 데려오다; 가져다주다; 초래하다; (소송을) 제기하다", ex:"Bring your friend."},
  "send": {kr:"보내다, 부치다; 파견하다; 발송하다; ~하게 만들다", ex:"I'll send an email."},
  "show": {kr:"보여주다; 나타내다; 안내하다; 상영하다; 쇼, 공연; 전시회", ex:"Show me your photos."},
  "good": {kr:"좋은, 훌륭한; 착한, 선한; 능숙한; 유익한; 상당한; 선(善)", ex:"A good idea."},
  "bad": {kr:"나쁜; 불량한; 심한, 심각한; (음식이) 상한; 서투른", ex:"The weather is bad."},
  "big": {kr:"큰, 거대한; 중요한; (나이가) 많은; 인기 있는; 관대한", ex:"A big house."},
  "small": {kr:"작은; 적은; 사소한; 소규모의; 어린", ex:"A small car."},
  "new": {kr:"새로운; 최근의; 신임의; 처음 접하는; 갱신된", ex:"A new bag."},
  "old": {kr:"늙은; 오래된, 낡은; ~살의; 예전의; 익숙한", ex:"An old building."},
  "long": {kr:"긴; (시간이) 오랜; 장황한; 오래; 갈망하다", ex:"A long trip."},
  "short": {kr:"짧은; 키가 작은; 부족한; 간결한; 갑자기", ex:"A short break."},
  "high": {kr:"높은; 고위의; (값이) 비싼; 심한; 높이", ex:"The price is high."},
  "low": {kr:"낮은; (값이) 싼; 저조한; 기운 없는; 천한", ex:"The shelf is low."},
  "hot": {kr:"뜨거운, 더운; 매운; 인기 있는; 격렬한; 최신의", ex:"The soup is hot."},
  "cold": {kr:"차가운, 추운; 냉정한; 식은; 감기; 추위", ex:"It's cold outside."},
  "happy": {kr:"행복한, 기쁜; 만족하는; 다행한; 적절한", ex:"She looks happy."},
  "sad": {kr:"슬픈; 안타까운; 한심한", ex:"He felt sad."},
  "easy": {kr:"쉬운; 편안한; 느긋한; 너그러운", ex:"The test was easy."},
  "hard": {kr:"어려운, 힘든; 단단한; 가혹한; 열심히; 세게; (술이) 독한", ex:"This problem is hard."},
  "fast": {kr:"빠른; (시계가) 빠른; 단단한; 빨리", ex:"A fast runner."},
  "slow": {kr:"느린; (시계가) 늦은; 둔한; 한산한; 천천히", ex:"The internet is slow."},
  "early": {kr:"이른; 초기의; 조기의; 일찍", ex:"I woke up early."},
  "late": {kr:"늦은; 말기의; 고(故); 최근의; 늦게", ex:"Sorry, I'm late."},
  "important": {kr:"중요한, 중대한; 영향력 있는; 유력한", ex:"An important meeting."},
  "beautiful": {kr:"아름다운, 예쁜; 훌륭한, 멋진", ex:"What a beautiful view!"},
  "different": {kr:"다른, 상이한; 별개의; 독특한", ex:"Different opinions."},
  "same": {kr:"같은, 동일한; 마찬가지의; 같은 것", ex:"The same school."},
  "true": {kr:"사실인, 참된; 진실한; 진짜의; 충실한; 정확한", ex:"Is it true?"},
  "free": {kr:"자유로운; 무료의; 한가한; 비어 있는; ~이 없는; 풀어주다", ex:"The event is free."},
  "full": {kr:"가득 찬; 배부른; 완전한; 최대한의; 풍부한", ex:"The bus was full."},
  "empty": {kr:"빈; 공허한; 무의미한; 비우다", ex:"The box is empty."},
  "clean": {kr:"깨끗한; 결백한; 깔끔한; 청소하다", ex:"Keep your room clean."},
  "dark": {kr:"어두운; (색이) 짙은; 우울한; 사악한; 비밀의; 어둠", ex:"The room was dark."},
  "young": {kr:"젊은, 어린; 초기의; 경험이 적은; 새끼", ex:"She is young."},
  "strong": {kr:"강한, 튼튼한; (힘이) 센; (맛이) 진한; 유력한; 확고한", ex:"He is strong."},
  "weak": {kr:"약한; (실력이) 부족한; (맛이) 연한; 설득력 없는", ex:"I feel weak."},
  "rich": {kr:"부유한; 풍부한; (맛이) 진한; 비옥한; (색이) 짙은", ex:"A rich man."},
  "poor": {kr:"가난한; 부족한; 형편없는; 불쌍한; 서투른", ex:"They were poor."},
  "safe": {kr:"안전한, 무사한; 확실한; 신중한; 금고", ex:"This area is safe."},
  "ready": {kr:"준비된; ~할 용의가 있는; 즉각적인", ex:"Are you ready?"},
  "sure": {kr:"확신하는; 확실한; 믿을 만한; 물론", ex:"I'm not sure."},
  "nice": {kr:"좋은, 멋진; 친절한; 즐거운; 정교한", ex:"A nice person."},
  "kind": {kr:"친절한, 다정한; 종류, 유형; 일종의; 본질", ex:"You're so kind."},
  "great": {kr:"훌륭한, 멋진; 거대한; 위대한; 대단한", ex:"A great idea."},
  "next": {kr:"다음의; 옆의; 다음에; 그러고 나서", ex:"See you next time."},
  "last": {kr:"마지막의; 지난; 최근의; 최후로; 지속되다, 견디다", ex:"The last chance."},
  "first": {kr:"첫 번째의; 최초의; 처음으로; 일등, 수석; 우선", ex:"He came first."},
  "able": {kr:"~할 수 있는; 유능한", ex:"She is able to speak."},
  "set": {kr:"놓다, 두다; 설정하다; (해가) 지다; 굳다; 한 벌, 세트; 무대 장치; 고정된", ex:"Set the alarm."},
  "line": {kr:"선, 줄; 노선; 대사; (전화) 회선; 한 줄로 세우다", ex:"Draw a line."},
  "hold": {kr:"잡다, 들다; 유지하다; 개최하다; 수용하다; (직책을) 맡다; 보류", ex:"Hold my hand."},
  "side": {kr:"쪽, 측면; 옆구리; 편, 측; 경사면; 부수적인", ex:"By my side."},
  "matter": {kr:"문제, 사안; 물질; 중요하다; 탈, 이상", ex:"It doesn't matter."},
  "mean": {kr:"의미하다; 의도하다; 중요하다; 인색한; 심술궂은; 평균", ex:"What do you mean?"},
  "fall": {kr:"떨어지다, 넘어지다; (값이) 내리다; 함락되다; 가을; 낙하; 폭포", ex:"Leaves fall in autumn."},
  "stand": {kr:"서다; 견디다, 참다; (입장을) 취하다; 가판대; 관중석; 태도", ex:"Please stand up."},
  "lead": {kr:"이끌다; 선두를 달리다; (생활을) 보내다; 통하다; 선두; 단서; 납(금속)", ex:"Lead the team."},
  "follow": {kr:"따라가다; (규칙을) 따르다; 이해하다; 주시하다; (결과로) 일어나다", ex:"Follow me."},
  "leave": {kr:"떠나다, 출발하다; 남기다, 두고 가다; 그만두다; 맡기다; 휴가", ex:"I leave at eight."},
  "begin": {kr:"시작하다; 비롯되다; 발단이 되다", ex:"The class begins."},
  "end": {kr:"끝나다, 끝내다; 끝, 마지막; 목적; 결말; 가장자리", ex:"A happy ending."},
  "grow": {kr:"자라다, 성장하다; 늘다; 재배하다; (점점) ~해지다", ex:"Plants grow."},
  "raise": {kr:"올리다; 인상하다; 기르다; 모금하다; (문제를) 제기하다; 인상", ex:"Raise your hand."},
  "watch": {kr:"보다, 지켜보다; 감시하다; 조심하다; 손목시계; 경계", ex:"Watch movies."},
  "listen": {kr:"듣다, 귀 기울이다; 경청하다; (충고를) 따르다", ex:"Listen to music."},
  "drive": {kr:"운전하다; 몰다; 추진하다; 내몰다; 드라이브; 추진력; 충동", ex:"She drives to work."},
  "cut": {kr:"자르다, 베다; 삭감하다; 줄이다; (수업을) 빼먹다; 상처; 한 조각", ex:"Cut the paper."},
  "wear": {kr:"입다, 착용하다; (표정을) 짓다; 닳다, 해지다; 마모", ex:"She wears glasses."},
  "spend": {kr:"(돈을) 쓰다; (시간을) 보내다; 다 써버리다", ex:"Spend money."},
  "save": {kr:"구하다; 저축하다; 아끼다, 절약하다; 저장하다; (골을) 막다", ex:"Save your money."},
  "draw": {kr:"그리다; 끌다, 당기다; 인출하다; 끌어내다; 비기다; 무승부; 추첨", ex:"Draw a picture."},
  "fly": {kr:"날다; 비행하다; 조종하다; (시간이) 빨리 가다; 휘날리다; 파리", ex:"Birds fly."},
  "fill": {kr:"채우다, 가득 차다; (자리를) 메우다; (서류를) 작성하다", ex:"Fill the glass."},
  "kill": {kr:"죽이다; (시간을) 때우다; 없애다; (고통을) 가라앉히다", ex:"Don't kill it."},
  "die": {kr:"죽다; 시들다; 소멸하다; (기계가) 멎다; 주사위", ex:"The flowers will die."},
  "pull": {kr:"당기다, 끌다; 잡아 뽑다; 끌어들이다; (근육을) 삐다; 영향력", ex:"Pull the door."},
  "push": {kr:"밀다; 누르다; 밀어붙이다; 강요하다; (상품을) 팔다", ex:"Push the button."},
  "throw": {kr:"던지다; 내던지다; (빛을) 비추다; 당황하게 하다", ex:"Throw the ball."},
  "catch": {kr:"잡다; (병에) 걸리다; (열차를) 잡아타다; 알아듣다; 목격하다", ex:"Catch the ball!"},
  "hit": {kr:"치다, 때리다; 부딪치다; (목표를) 맞히다; 도달하다; 강타; 히트작", ex:"Don't hit him."},
  "pick": {kr:"고르다, 선택하다; 따다, 꺾다; 집어 들다; (자물쇠를) 따다; 정선품", ex:"Pick a card."},
  "drop": {kr:"떨어뜨리다; 떨어지다; 그만두다; 내려주다; 방울; 하락; 소량", ex:"Don't drop it."},
  "stay": {kr:"머무르다; 그대로 있다; 숙박하다; (상태를) 유지하다; 체류", ex:"Stay here."},
  "rise": {kr:"오르다; 일어서다; (해가) 뜨다; 봉기하다; 상승; 증가; 인상", ex:"Prices keep rising."},
  "join": {kr:"가입하다, 합류하다; 연결하다, 잇다; 함께하다; 입대하다; 접합", ex:"Join our club!"},
  "create": {kr:"창조하다, 만들다; (일자리를) 창출하다; 야기하다", ex:"Artists create beauty."},
  "develop": {kr:"발전시키다, 개발하다; 성장하다; (병이) 생기다; (사진을) 현상하다", ex:"Develop software."},
  "produce": {kr:"생산하다; 낳다, 야기하다; 제시하다; 제작하다; 농산물", ex:"Produce cars."},
  "provide": {kr:"제공하다, 공급하다; 대비하다; 규정하다", ex:"We provide coffee."},
  "offer": {kr:"제공하다, 제안하다; 권하다; (값을) 부르다; 제안; 할인", ex:"He offered a job."},
  "receive": {kr:"받다, 수령하다; 받아들이다; 맞이하다; 수신하다", ex:"I received your letter."},
  "accept": {kr:"받아들이다, 수락하다; 인정하다; (책임을) 지다", ex:"She accepted the offer."},
  "agree": {kr:"동의하다, 찬성하다; 합의하다; 일치하다", ex:"I agree with you."},
  "decide": {kr:"결정하다, 결심하다; 판결하다; 좌우하다", ex:"We decided to go."},
  "explain": {kr:"설명하다, 해명하다; (이유를) 밝히다", ex:"Explain the rule."},
  "describe": {kr:"묘사하다, 서술하다; 설명하다; ~라고 표현하다", ex:"Describe what you saw."},
  "consider": {kr:"고려하다, 숙고하다; ~라고 여기다; 참작하다", ex:"Consider my idea."},
  "expect": {kr:"기대하다, 예상하다; 요구하다; (아이를) 임신 중이다", ex:"I expect good news."},
  "increase": {kr:"늘다, 증가하다; 늘리다, 인상하다; 증가, 인상", ex:"Prices will increase."},
  "reduce": {kr:"줄이다; 인하하다; (~으로) 만들다; 졸이다", ex:"Reduce waste."},
  "improve": {kr:"개선하다, 향상시키다; 나아지다; 호전되다", ex:"Improve my English."},
  "continue": {kr:"계속하다, 지속하다; 이어지다; 재개하다", ex:"Continue your story."},
  "remain": {kr:"남다, 남아 있다; 머무르다; (여전히) ~인 채로 있다", ex:"Few people remained."},
  "return": {kr:"돌아오다; 반환하다, 돌려주다; 답례하다; 귀환; 반납; 수익", ex:"I will return."},
  "appear": {kr:"나타나다, 출현하다; ~처럼 보이다; 출연하다; 출간되다", ex:"A star appeared."},
  "seem": {kr:"~인 것 같다, ~처럼 보이다", ex:"You seem tired."},
  "become": {kr:"~이 되다, ~해지다; 어울리다", ex:"She became a doctor."},
  "allow": {kr:"허락하다, 허용하다; (시간·돈을) 잡다; 인정하다", ex:"Smoking is not allowed."},
  "include": {kr:"포함하다; 넣다", ex:"The price includes tax."},
  "contain": {kr:"포함하다, 담고 있다; 억제하다, 억누르다", ex:"It contains sugar."},
  "support": {kr:"지지하다; 지탱하다; 부양하다; 뒷받침하다; 지지; 지원", ex:"I support you."},
  "report": {kr:"보고하다, 보도하다; 신고하다; 출두하다; 보고서; 소문", ex:"Report the news."},
  "realize": {kr:"깨닫다, 알아차리다; 실현하다; (자산을) 현금화하다", ex:"I realized my mistake."},
  "suggest": {kr:"제안하다, 권하다; 암시하다; 시사하다", ex:"I suggest a break."},
  "mention": {kr:"언급하다, 말하다; 거론하다; 언급", ex:"He mentioned your name."},
  "answer": {kr:"대답하다; (전화를) 받다; 해결하다; 대답; 해답; 정답", ex:"Answer my question."},
  "wonder": {kr:"궁금해하다; 놀라워하다; ~일까 생각하다; 경이", ex:"I wonder what time it is."},
  "worry": {kr:"걱정하다; 괴롭히다; 걱정, 근심", ex:"Don't worry."},
  "care": {kr:"돌보다, 보살피다; 마음 쓰다, 관심 갖다; 좋아하다; 돌봄; 주의", ex:"Take care."},
  "miss": {kr:"놓치다; 그리워하다; (목표를) 빗나가다; 빠뜨리다; 결석하다", ex:"I miss my family."},
  "wish": {kr:"바라다, 소망하다; (~이면) 좋겠다; 기원하다; 소원", ex:"I wish you luck."},
  "thank": {kr:"감사하다, 고마워하다; 사례하다", ex:"Thank you."},
  "smile": {kr:"미소 짓다, 웃다; 미소; (운이) 따르다", ex:"A warm smile."},
  "laugh": {kr:"웃다; 비웃다; 웃음", ex:"We laughed."},
  "cry": {kr:"울다; 외치다, 소리치다; 부르짖다; 외침; 울음", ex:"The baby began to cry."},
  "price": {kr:"값, 가격; 물가; 대가, 희생; 값을 매기다", ex:"The price is high."},
  "cost": {kr:"(비용이) 들다; 희생시키다; 비용, 원가; 대가", ex:"How much does it cost?"},
  "value": {kr:"가치, 값어치; 액수; 가치관; 소중히 여기다; 평가하다", ex:"Great value."},
  "market": {kr:"시장; 장; 수요; 주식시장; (상품을) 팔다", ex:"Buy fruit at the market."},
  "store": {kr:"가게, 상점; 저장; 비축; 저장하다, 보관하다", ex:"The store is closed."},
  "order": {kr:"주문하다; 명령하다; 정리하다; 순서; 질서; 명령; 주문", ex:"Take your order."},
  "plan": {kr:"계획하다, 기획하다; 설계하다; 계획; 방안; 설계도", ex:"What's your plan?"},
  "idea": {kr:"생각, 아이디어; 발상; 개념; 짐작; 의도", ex:"A good idea."},
  "fact": {kr:"사실; 실제; 진상", ex:"A known fact."},
  "reason": {kr:"이유, 까닭; 이성, 사고력; 분별; 추론하다; 설득하다", ex:"Give me a reason."},
  "result": {kr:"결과, 성과; 결말; (results) 성적; (~의 결과로) 생기다", ex:"A surprising result."},
  "cause": {kr:"원인, 이유; 대의, 명분; 사건; 야기하다, 일으키다", ex:"What caused it?"},
  "effect": {kr:"효과, 영향; 결과; 취지; (effects) 소지품", ex:"A strong effect."},
  "example": {kr:"예, 보기; 사례; 본보기, 모범; 예제", ex:"Give an example."},
  "type": {kr:"유형, 종류; 활자; 타자 치다, 입력하다; 전형", ex:"What type of music?"},
  "form": {kr:"형태, 모양; 양식, 서식; 종류; 형성하다; 컨디션", ex:"Fill out this form."},
  "level": {kr:"수준, 정도; 단계; 높이; 수평의; 평평하게 하다; 겨누다", ex:"A high level."},
  "rate": {kr:"비율, 율; 속도; 요금; 등급; 평가하다; 간주하다", ex:"The success rate."},
  "amount": {kr:"양, 액수; 총액; (양이) ~에 달하다", ex:"A large amount."},
  "size": {kr:"크기, 규모; 치수, 사이즈; 분량", ex:"What size?"},
  "piece": {kr:"조각, 부분; 한 점, 한 개; 작품; (장기) 말; 기사", ex:"A piece of cake."},
  "half": {kr:"절반, 반; 30분; 후반전; 반의; 절반쯤", ex:"Half of the cake."},
  "whole": {kr:"전체의, 전부의; 온전한; 전체; 모두", ex:"The whole pizza."},
  "main": {kr:"주된, 주요한; 가장 중요한; (수도·전기) 본관, 간선", ex:"The main point."},
  "real": {kr:"진짜의, 실제의; 현실의; 진정한; 부동산의", ex:"A real diamond?"},
  "sense": {kr:"감각; 느낌; 의미; 분별, 판단력; 감지하다", ex:"A sense of humor."},
  "mind": {kr:"마음, 정신; 생각, 의향; 지성; 꺼리다, 신경 쓰다; 조심하다; 돌보다", ex:"What's on your mind?"},
  "language": {kr:"언어, 말; 말씨, 어법; (특정) 언어; (컴퓨터) 언어", ex:"A global language."},
  "voice": {kr:"목소리, 음성; 발언권; 의견; (문법) 태; 표명하다", ex:"A beautiful voice."},
  "sound": {kr:"소리, 음; 음향; ~처럼 들리다; 울리다; 건전한, 타당한", ex:"A strange sound."},
  "picture": {kr:"그림, 사진; 영상; 상황, 정황; 묘사하다, 상상하다; 영화", ex:"Take a picture."},
  "image": {kr:"이미지, 인상; 영상, 화상; 모습; 형상; 꼭 닮은 것", ex:"A clear image."},
  "view": {kr:"전망, 경관; 견해, 관점; 시야; 바라보다; ~라고 여기다", ex:"An amazing view."},
  "area": {kr:"지역, 구역; 분야, 영역; 면적; 부위", ex:"A quiet area."},
  "field": {kr:"들판, 밭; 경기장; 분야, 영역; 현장", ex:"Cows in the field."},
  "ground": {kr:"땅, 지면; 운동장; 근거, 이유; 영역; 외출 금지하다", ex:"Sit on the ground."},
  "space": {kr:"공간, 자리; 우주; 여백; 사이, 간격; (시간적) 동안", ex:"No space left."},
  "road": {kr:"길, 도로; 진로, 방향; 여정", ex:"This road leads to town."},
  "center": {kr:"중심, 가운데; 중심지; 센터, 회관; (정치) 중도; 집중시키다", ex:"The city center."},
  "top": {kr:"꼭대기, 정상; 맨 위; 상의; 최고의; 능가하다; 팽이", ex:"On top of the box."},
  "edge": {kr:"가장자리, 끝; 날(칼날); 우위; 모서리", ex:"Near the edge."},
  "front": {kr:"앞, 정면; 전선; 최전선; 앞쪽의; (~을) 마주하다", ex:"The front row."},
  "back": {kr:"등; 뒤, 뒤쪽; (책의) 뒷부분; 뒤로; 후원하다; 후진하다", ex:"My back hurts."},
  "person": {kr:"사람, 개인; (문법) 인칭", ex:"A kind person."},
  "information": {kr:"정보, 자료; 안내", ex:"Useful information."},
  "education": {kr:"교육; 교양", ex:"Higher education."},
  "experience": {kr:"경험, 체험; 경력; 경험하다, 겪다", ex:"Work experience."},
  "society": {kr:"사회; 단체, 협회; 사교계", ex:"Modern society."},
  "member": {kr:"회원, 일원; 구성원; (신체) 부위", ex:"A club member."},
  "project": {kr:"프로젝트, 계획; 과제; 투영하다; 예상하다", ex:"A school project."},
  "news": {kr:"소식; 뉴스, 보도", ex:"Good news!"},
  "paper": {kr:"종이; 신문; 논문; 서류; 시험지", ex:"A sheet of paper."},
  "page": {kr:"페이지, 쪽; (웹) 페이지", ex:"Turn the page."},
  "list": {kr:"목록, 명단; 리스트; 열거하다", ex:"A shopping list."},
  "note": {kr:"메모, 쪽지; 음, 음표; 주석; 지폐; 적어두다; 주목하다", ex:"Take notes."},
  "sign": {kr:"표지판, 간판; 징후, 조짐; 신호; 기호; 서명하다", ex:"A road sign."},
  "hospital": {kr:"병원", ex:"She is in the hospital."},
  "doctor": {kr:"의사; 박사", ex:"See a doctor."},
  "office": {kr:"사무실; 관청; 직책, 공직", ex:"I work at an office."},
  "bank": {kr:"은행; 둑, 제방; 모래톱; 예금하다", ex:"I went to the bank."},
  "hotel": {kr:"호텔", ex:"A nice hotel."},
  "park": {kr:"공원; 주차장; 주차하다", ex:"Walk in the park."},
  "building": {kr:"건물, 빌딩; 건축", ex:"A tall building."},
  "floor": {kr:"바닥; (건물) 층; 발언권", ex:"The first floor."},
  "wall": {kr:"벽, 담; 장벽", ex:"A brick wall."},
  "town": {kr:"읍, 시내; 도회지; (the town) 시민", ex:"A small town."},
  "village": {kr:"마을, 촌락", ex:"A quiet village."},
  "beach": {kr:"해변, 바닷가", ex:"A day at the beach."},
  "farm": {kr:"농장, 농가; 양식장; 경작하다", ex:"They live on a farm."},
  "arm": {kr:"팔; (의자) 팔걸이; (the arms) 무기; 무장하다", ex:"He broke his arm."},
  "leg": {kr:"다리; (가구) 다리; (여정) 구간", ex:"My legs are tired."},
  "foot": {kr:"발; 기슭, 맨 아래; 피트(단위)", ex:"My foot hurts."},
  "finger": {kr:"손가락; 가리키다", ex:"Point your finger."},
  "ear": {kr:"귀; 청력; (옥수수) 이삭", ex:"Cover your ears."},
  "nose": {kr:"코; 후각; 기수; 냄새 맡다", ex:"A runny nose."},
  "mouth": {kr:"입; 입구; 강어귀", ex:"Open your mouth."},
  "hair": {kr:"머리카락, 털", ex:"She has long hair."},
  "skin": {kr:"피부; 가죽; 껍질; 표면", ex:"Soft skin."},
  "blood": {kr:"피, 혈액; 혈통", ex:"He lost a lot of blood."},
  "bone": {kr:"뼈; 골격", ex:"A broken bone."},
  "bread": {kr:"빵; (속어) 돈, 생계", ex:"Fresh bread."},
  "rice": {kr:"쌀, 밥; 벼", ex:"A bowl of rice."},
  "meat": {kr:"고기, 육류; 알맹이, 핵심", ex:"I don't eat meat."},
  "egg": {kr:"달걀, 알; 난자", ex:"Boil an egg."},
  "milk": {kr:"우유, 젖; (젖을) 짜다; 착취하다", ex:"A glass of milk."},
  "coffee": {kr:"커피", ex:"A cup of coffee."},
  "tea": {kr:"차; 홍차; 다과", ex:"Green tea."},
  "sugar": {kr:"설탕; 당분", ex:"No sugar, please."},
  "salt": {kr:"소금; 소금에 절이다", ex:"Add some salt."},
  "fruit": {kr:"과일, 열매; 성과, 결실", ex:"Fresh fruit."},
  "apple": {kr:"사과", ex:"An apple a day."},
  "meal": {kr:"식사, 끼니", ex:"A healthy meal."},
  "breakfast": {kr:"아침 식사", ex:"Eat breakfast."},
  "lunch": {kr:"점심 식사", ex:"Let's have lunch."},
  "dinner": {kr:"저녁 식사; 만찬", ex:"Dinner is ready."},
  "moment": {kr:"순간, 잠깐; 시점; 중요성", ex:"Wait a moment."},
  "second": {kr:"초; 둘째의; 잠깐; 지지하다", ex:"Wait a second."},
  "century": {kr:"세기, 100년", ex:"The 21st century."},
  "season": {kr:"계절; 철, 시즌; (양념으로) 간을 하다", ex:"My favorite season."},
  "spring": {kr:"봄; 용수철, 스프링; 샘; 튀어 오르다", ex:"Flowers bloom in spring."},
  "summer": {kr:"여름", ex:"A hot summer."},
  "winter": {kr:"겨울; 겨울을 나다", ex:"A cold winter."},
  "weekend": {kr:"주말", ex:"Have a nice weekend."},
  "holiday": {kr:"휴일, 명절; 휴가", ex:"A national holiday."},
  "future": {kr:"미래, 장래; 선물(거래); 미래의", ex:"Plan for the future."},
  "past": {kr:"과거; 지난; ~을 지나; (시간이) 지나서", ex:"In the past."},
  "age": {kr:"나이, 연령; 시대; 노년; 나이를 먹다", ex:"What is your age?"},
  "star": {kr:"별; 스타, 인기인; 별표; 주연하다", ex:"A bright star."},
  "cloud": {kr:"구름; (먼지) 자욱함; 흐리게 하다", ex:"A dark cloud."},
  "stone": {kr:"돌; 보석; 씨, 핵", ex:"A stone wall."},
  "rock": {kr:"바위, 암석; 록 음악; 흔들다, 흔들리다", ex:"A big rock."},
  "grass": {kr:"풀, 잔디; 목초지", ex:"Don't step on the grass."},
  "leaf": {kr:"잎; (책) 한 장", ex:"A green leaf."},
  "weather": {kr:"날씨, 기상; (역경을) 견뎌내다", ex:"Nice weather today."},
  "storm": {kr:"폭풍, 폭풍우; 격노; 급습하다", ex:"A big storm is coming."},
  "ice": {kr:"얼음; 얼리다; (케이크에) 당의를 입히다", ex:"Ice in my drink."},
  "husband": {kr:"남편", ex:"Her husband is kind."},
  "wife": {kr:"아내, 부인", ex:"His wife is a teacher."},
  "son": {kr:"아들", ex:"My son is five."},
  "daughter": {kr:"딸", ex:"My daughter loves books."},
  "brother": {kr:"형, 오빠, 남동생; 형제", ex:"My older brother."},
  "sister": {kr:"누나, 언니, 여동생; 자매; 수녀", ex:"My little sister."},
  "neighbor": {kr:"이웃; 옆자리 사람", ex:"A friendly neighbor."},
  "guest": {kr:"손님, 하객; 투숙객; 초대 손님", ex:"We have guests."},
  "leader": {kr:"지도자, 대표; 선두; 리더", ex:"A great leader."},
  "king": {kr:"왕, 국왕; 일인자; (체스) 킹", ex:"The king ruled wisely."},
  "queen": {kr:"여왕; 왕비; (체스) 퀸", ex:"The queen smiled."},
  "soldier": {kr:"군인, 병사", ex:"A brave soldier."},
  "customer": {kr:"고객, 손님", ex:"The customer is happy."},
  "owner": {kr:"주인, 소유주", ex:"The shop owner."},
  "manager": {kr:"관리자, 책임자; 감독; 경영자", ex:"Talk to the manager."},
  "worker": {kr:"노동자, 근로자; 일꾼", ex:"A hard worker."},
  "writer": {kr:"작가, 저술가; 필자", ex:"A famous writer."},
  "player": {kr:"선수; 연주자; 재생기; (게임) 플레이어", ex:"A soccer player."},
  "dream": {kr:"꿈; 이상, 소망; 꿈꾸다; 상상하다", ex:"Follow your dream."},
  "goal": {kr:"목표; 골; 득점", ex:"Reach your goal."},
  "chance": {kr:"기회; 가능성; 우연; 운", ex:"Give me a chance."},
  "choice": {kr:"선택; 선택권; 선택 대상; 엄선된", ex:"A hard choice."},
  "rule": {kr:"규칙, 규정; 지배, 통치; 지배하다; 판결하다", ex:"Follow the rules."},
  "law": {kr:"법, 법률; 법칙; 법조계", ex:"Obey the law."},
  "peace": {kr:"평화; 평온; 화해", ex:"World peace."},
  "success": {kr:"성공; 성공한 사람·것", ex:"Wish you success."},
  "mistake": {kr:"실수, 잘못; 오해하다; 착각하다", ex:"A small mistake."},
  "advice": {kr:"조언, 충고", ex:"Good advice."},
  "opinion": {kr:"의견, 견해; 여론; 평가", ex:"In my opinion."},
  "skill": {kr:"기술, 솜씨; 숙련", ex:"A useful skill."},
  "culture": {kr:"문화; 교양; 배양(균)", ex:"Korean culture."},
  "science": {kr:"과학; 학문, 학(學)", ex:"I love science."},
  "nature": {kr:"자연; 천성, 본성; 종류, 성질", ex:"The beauty of nature."},
  "energy": {kr:"에너지; 활력, 기운; 정력", ex:"Full of energy."},
  "machine": {kr:"기계; 조직, 기구", ex:"A washing machine."},
  "key": {kr:"열쇠; 비결; (컴퓨터) 키, 건반; 조(調); 핵심적인", ex:"I lost my key."},
  "glass": {kr:"유리; 유리잔; (glasses) 안경", ex:"A glass of water."},
  "cup": {kr:"컵, 잔; 우승컵; 한 컵(분량)", ex:"A cup of tea."},
  "bottle": {kr:"병; 한 병(분량); 병에 담다", ex:"A bottle of water."},
  "box": {kr:"상자, 박스; 칸막이석; 권투하다", ex:"A cardboard box."},
  "bag": {kr:"가방, 봉지; 자루; 한 봉지", ex:"A paper bag."},
  "pen": {kr:"펜; 우리, 축사", ex:"Write with a pen."},
  "letter": {kr:"편지; 글자, 문자", ex:"Write a letter."},
  "card": {kr:"카드; 엽서; 명함; (카드) 패", ex:"A birthday card."},
  "map": {kr:"지도; 지도를 만들다", ex:"Look at the map."},
  "gift": {kr:"선물; 재능, 천부적 재능", ex:"A birthday gift."},

  "add": {kr:"더하다, 추가하다; 합하다; 덧붙여 말하다", ex:"Add some salt."},
  "remove": {kr:"제거하다, 없애다; 치우다; 해임하다; 벗다", ex:"Remove your shoes."},
  "choose": {kr:"고르다, 선택하다; 결정하다", ex:"Choose a color."},
  "prepare": {kr:"준비하다; 대비하다; 조리하다", ex:"Prepare for the test."},
  "manage": {kr:"관리하다, 운영하다; 가까스로 해내다; 다루다", ex:"She manages a team."},
  "control": {kr:"통제하다, 지배하다; 조절하다; 통제; 조종 장치", ex:"Control your anger."},
  "guide": {kr:"안내하다, 인도하다; 지도하다; 안내원; 지침서", ex:"A tour guide."},
  "train": {kr:"훈련하다, 교육하다; 연습시키다; 기차", ex:"Train every day."},
  "practice": {kr:"연습하다; 실천하다; (의사로) 개업하다; 연습; 관행", ex:"Practice the piano."},
  "repeat": {kr:"반복하다; 따라 하다; 재방송하다; 반복", ex:"Please repeat that."},
  "check": {kr:"확인하다, 점검하다; 저지하다; 수표; 계산서; (체스) 장군", ex:"Check your answers."},
  "test": {kr:"시험하다, 검사하다; 시험; 검사; 시련", ex:"Take a test."},
  "count": {kr:"(수를) 세다; 중요하다; ~로 여기다; 계산; (귀족) 백작", ex:"Count to ten."},
  "compare": {kr:"비교하다; 비유하다; 견주다", ex:"Compare the prices."},
  "match": {kr:"어울리다, 맞다; 필적하다; 성냥; 경기, 시합; 짝", ex:"The colors match."},
  "fit": {kr:"맞다, 적합하다; (옷이) 맞다; 건강한; 발작", ex:"These shoes fit well."},
  "judge": {kr:"판단하다; 재판하다; 심사하다; 판사; 심판", ex:"Don't judge me."},
  "guess": {kr:"추측하다, 짐작하다; ~인 것 같다; 추측", ex:"Guess my age."},
  "imagine": {kr:"상상하다; 짐작하다; ~라고 생각하다", ex:"Imagine the future."},
  "suppose": {kr:"가정하다; ~라고 생각하다; (be supposed to) ~하기로 되어 있다", ex:"I suppose so."},
  "discuss": {kr:"논의하다, 토론하다; 거론하다", ex:"Let's discuss it."},
  "complain": {kr:"불평하다, 항의하다; (병을) 호소하다", ex:"Don't complain."},
  "promise": {kr:"약속하다; 가능성이 있다; 약속; 장래성", ex:"I promise to help."},
  "refuse": {kr:"거절하다, 거부하다; 폐기물, 쓰레기", ex:"She refused the offer."},
  "deny": {kr:"부인하다, 부정하다; 거부하다", ex:"He denied the charge."},
  "admit": {kr:"인정하다; 시인하다; 입장을 허락하다; 수용하다", ex:"Admit your mistake."},
  "reject": {kr:"거절하다, 거부하다; 불합격시키다; 불량품", ex:"They rejected the plan."},
  "prevent": {kr:"막다, 예방하다; 방해하다", ex:"Prevent accidents."},
  "avoid": {kr:"피하다, 회피하다; 막다", ex:"Avoid the traffic."},
  "escape": {kr:"탈출하다, 달아나다; 모면하다; 새다; 탈출; 도피", ex:"They escaped the fire."},
  "hide": {kr:"숨다, 숨기다; 감추다; (동물) 가죽", ex:"Hide and seek."},
  "search": {kr:"찾다, 수색하다; 검색하다; 탐구하다; 수색; 검색", ex:"Search the web."},
  "discover": {kr:"발견하다; 알아내다; 깨닫다", ex:"Discover new places."},
  "explore": {kr:"탐험하다, 탐구하다; 살펴보다", ex:"Explore the cave."},
  "examine": {kr:"조사하다, 검토하다; 진찰하다; 시험하다", ex:"Examine the evidence."},
  "notice": {kr:"알아채다, 주목하다; 공지, 안내문; 통지; 주목", ex:"I didn't notice you."},
  "recognize": {kr:"알아보다, 인식하다; 인정하다; 승인하다", ex:"I recognize her."},
  "recall": {kr:"기억해 내다, 상기하다; 소환하다; 회수하다; 기억력", ex:"I can't recall it."},
  "remind": {kr:"상기시키다, 일깨우다; (~을) 연상시키다", ex:"Remind me later."},
  "prove": {kr:"증명하다, 입증하다; ~으로 판명되다", ex:"Prove it."},
  "express": {kr:"표현하다, 나타내다; 급행의; 신속한; 급행열차; 속달", ex:"Express your feelings."},
  "recommend": {kr:"추천하다, 권하다; 권고하다", ex:"I recommend this book."},
  "advise": {kr:"조언하다, 충고하다; 권하다; 알리다", ex:"She advised me to rest."},
  "warn": {kr:"경고하다, 주의를 주다; 미리 알리다", ex:"I warned you."},
  "encourage": {kr:"격려하다, 북돋우다; 장려하다", ex:"Encourage your children."},
  "require": {kr:"필요로 하다; 요구하다; 규정하다", ex:"This requires effort."},
  "demand": {kr:"요구하다; 강력히 묻다; 요구; 수요", ex:"They demand answers."},
  "request": {kr:"요청하다, 부탁하다; 요청; 요구사항", ex:"Request permission."},
  "obey": {kr:"복종하다, 따르다; (법을) 지키다", ex:"Obey the rules."},
  "succeed": {kr:"성공하다; 뒤를 잇다, 계승하다", ex:"You will succeed."},
  "fail": {kr:"실패하다; 낙제하다; (기능이) 멈추다; 저버리다", ex:"Don't fail the test."},
  "achieve": {kr:"달성하다, 이루다; 성취하다", ex:"Achieve your goals."},
  "complete": {kr:"완료하다, 끝마치다; 완전한; 완벽한; (서류를) 작성하다", ex:"Complete the form."},
  "finish": {kr:"끝내다, 마치다; 다 먹다; 마무리; 끝", ex:"Finish your homework."},
  "hurry": {kr:"서두르다; 재촉하다; 서두름, 급함", ex:"Hurry up!"},
  "relax": {kr:"휴식하다, 긴장을 풀다; 완화하다", ex:"Relax and breathe."},
  "rest": {kr:"쉬다, 휴식하다; 기대다; 놓이다; 휴식; 나머지", ex:"Get some rest."},
  "celebrate": {kr:"축하하다, 기념하다; 거행하다; 기리다", ex:"Celebrate your birthday."},
  "cook": {kr:"요리하다, 조리하다; 익히다; 요리사", ex:"I cook dinner."},
  "mix": {kr:"섞다, 혼합하다; 어울리다; 혼합; 혼합물", ex:"Mix the colors."},
  "wash": {kr:"씻다, 빨다; (파도가) 밀려오다; 세탁물", ex:"Wash your hands."},
  "fix": {kr:"고치다, 수리하다; 고정하다; 정하다; 준비하다; 곤경", ex:"Fix the car."},
  "repair": {kr:"수리하다, 고치다; 바로잡다; 수리, 보수", ex:"Repair the roof."},
  "paint": {kr:"칠하다; 그림을 그리다; 페인트, 물감", ex:"Paint the wall."},
  "plant": {kr:"심다; (씨를) 뿌리다; 식물; 공장; 설비", ex:"Plant a tree."},
  "feed": {kr:"먹이다, 먹이를 주다; 공급하다; 먹이; 사료", ex:"Feed the dog."},
  "ride": {kr:"타다, 타고 가다; 승마하다; 타기; 놀이기구", ex:"Ride a bike."},
  "swim": {kr:"헤엄치다, 수영하다; 수영", ex:"I can swim."},
  "dance": {kr:"춤추다; 춤; 무도회", ex:"Let's dance."},
  "sing": {kr:"노래하다; 지저귀다", ex:"Sing a song."},
  "climb": {kr:"오르다, 등반하다; 상승하다; 등반", ex:"Climb the mountain."},
  "jump": {kr:"뛰다, 점프하다; 급등하다; 건너뛰다; 점프; 급등", ex:"Jump over it."},
  "kick": {kr:"차다; 발길질하다; (총이) 반동하다; 발차기; 짜릿함", ex:"Kick the ball."},
  "shoot": {kr:"쏘다, 발사하다; 촬영하다; 슛하다; 쏜살같이 가다; 새싹", ex:"Don't shoot!"},
  "fight": {kr:"싸우다, 다투다; 맞서 싸우다; 싸움; 투쟁; 경기", ex:"Don't fight."},
  "protect": {kr:"보호하다, 지키다; 막아 주다", ex:"Protect the children."},
  "marry": {kr:"결혼하다; 주례를 서다; 결합시키다", ex:"Will you marry me?"},
  "cheap": {kr:"싼, 저렴한; 값싼, 질 낮은; 인색한", ex:"A cheap ticket."},
  "expensive": {kr:"비싼, 값비싼", ex:"An expensive car."},
  "heavy": {kr:"무거운; (양이) 많은; (정도가) 심한; 힘든", ex:"A heavy bag."},
  "deep": {kr:"깊은; (색·소리가) 짙은/낮은; 심오한; 깊이; 깊게", ex:"A deep river."},
  "wide": {kr:"넓은; 폭이 ~인; (차이가) 큰; 활짝", ex:"A wide road."},
  "narrow": {kr:"좁은; 한정된; 가까스로의; 좁히다", ex:"A narrow path."},
  "thick": {kr:"두꺼운; (액체가) 진한; 빽빽한; 두께가 ~인", ex:"A thick book."},
  "thin": {kr:"얇은; 가는; 마른; (액체가) 묽은; 드문드문한", ex:"A thin slice."},
  "flat": {kr:"평평한; 납작한; (타이어가) 펑크 난; (음이) 반음 낮은; 아파트", ex:"A flat surface."},
  "round": {kr:"둥근; 통통한; ~을 돌아; 한 차례; 회전; 반올림하다", ex:"A round table."},
  "sharp": {kr:"날카로운; 뾰족한; 급격한; 예리한; 정각; (음이) 반음 높은", ex:"A sharp knife."},
  "smooth": {kr:"매끄러운; 순조로운; (맛이) 부드러운; 매끈하게 하다", ex:"Smooth skin."},
  "rough": {kr:"거친; 대략의; 힘든; 험한; 거칠게", ex:"A rough road."},
  "soft": {kr:"부드러운; 푹신한; (소리가) 조용한; 온화한; 마음 약한", ex:"A soft pillow."},
  "wet": {kr:"젖은; 비 오는; 축축한; 적시다", ex:"The grass is wet."},
  "dry": {kr:"마른, 건조한; (술이) 드라이한; 무미건조한; 말리다", ex:"Dry weather."},
  "clear": {kr:"맑은, 투명한; 분명한; (장애물이) 없는; 치우다; 맑게 개다", ex:"A clear sky."},
  "bright": {kr:"밝은; 선명한; 영리한; 밝게", ex:"A bright light."},
  "loud": {kr:"(소리가) 큰, 시끄러운; (색이) 요란한; 큰 소리로", ex:"A loud noise."},
  "quiet": {kr:"조용한; 한적한; 차분한; 고요; 조용히 시키다", ex:"A quiet room."},
  "calm": {kr:"침착한, 차분한; (날씨가) 고요한; 진정시키다; 고요", ex:"Stay calm."},
  "busy": {kr:"바쁜; 분주한; (전화가) 통화 중인; (장소가) 붐비는", ex:"I'm very busy."},
  "lazy": {kr:"게으른; 나른한", ex:"A lazy afternoon."},
  "brave": {kr:"용감한; 용감히 맞서다", ex:"A brave soldier."},
  "honest": {kr:"정직한, 솔직한; 성실한", ex:"An honest answer."},
  "polite": {kr:"예의 바른, 공손한", ex:"Be polite."},
  "rude": {kr:"무례한, 버릇없는; 거친", ex:"Don't be rude."},
  "gentle": {kr:"온화한, 다정한; 부드러운; (경사가) 완만한", ex:"A gentle touch."},
  "wild": {kr:"야생의; 거친; 격렬한; 무모한; 황야", ex:"Wild animals."},
  "fresh": {kr:"신선한; 새로운; 상쾌한; (물이) 민물의", ex:"Fresh air."},
  "dirty": {kr:"더러운; 부정한; 추잡한; 더럽히다", ex:"Dirty hands."},
  "sweet": {kr:"달콤한, 단; 향긋한; 상냥한; 사탕, 단것", ex:"A sweet cake."},
  "sour": {kr:"신, 시큼한; 상한; 불쾌한; 시큼해지다", ex:"A sour lemon."},
  "bitter": {kr:"쓴; 쓰라린; 격렬한; 혹독한", ex:"Bitter coffee."},
  "tasty": {kr:"맛있는", ex:"A tasty meal."},
  "healthy": {kr:"건강한; 건강에 좋은; 건전한", ex:"A healthy diet."},
  "sick": {kr:"아픈, 병든; 메스꺼운; 진저리 나는", ex:"I feel sick."},
  "tired": {kr:"피곤한, 지친; 싫증 난", ex:"I'm tired."},
  "hungry": {kr:"배고픈; 갈망하는", ex:"I'm hungry."},
  "thirsty": {kr:"목마른; 갈망하는", ex:"I'm thirsty."},
  "angry": {kr:"화난, 성난; (날씨가) 험악한", ex:"He looks angry."},
  "afraid": {kr:"두려워하는, 무서워하는; 걱정하는; 유감스러운", ex:"I'm afraid of dogs."},
  "nervous": {kr:"긴장한, 초조한; 신경의; 신경질적인", ex:"I feel nervous."},
  "proud": {kr:"자랑스러운; 자존심 있는; 거만한", ex:"I'm proud of you."},
  "curious": {kr:"호기심 많은; 기이한, 묘한", ex:"A curious child."},
  "serious": {kr:"진지한; 심각한; 중대한", ex:"A serious problem."},
  "funny": {kr:"웃기는, 재미있는; 이상한; 묘한", ex:"A funny story."},
  "boring": {kr:"지루한, 따분한", ex:"A boring movie."},
  "interesting": {kr:"흥미로운, 재미있는", ex:"An interesting idea."},
  "exciting": {kr:"흥미진진한, 신나는", ex:"An exciting game."},
  "simple": {kr:"간단한, 단순한; 소박한; 순진한", ex:"A simple plan."},
  "common": {kr:"흔한; 공통의; 일반적인; 평범한", ex:"A common mistake."},
  "rare": {kr:"드문, 희귀한; (고기가) 덜 익은", ex:"A rare bird."},
  "normal": {kr:"정상의; 보통의, 평범한; 표준", ex:"A normal day."},
  "usual": {kr:"평소의, 보통의; 일상적인", ex:"The usual time."},
  "special": {kr:"특별한; 전문의; 특별한 것", ex:"A special day."},
  "public": {kr:"공공의; 공개적인; 대중의; 대중", ex:"Public transport."},
  "private": {kr:"사적인; 개인의; 비공개의; 사병", ex:"A private matter."},
  "local": {kr:"지역의, 현지의; 동네의; 현지인; 완행의", ex:"A local market."},
  "modern": {kr:"현대의, 근대의; 현대적인", ex:"Modern technology."},
  "possible": {kr:"가능한; 있을 수 있는", ex:"Is it possible?"},
  "necessary": {kr:"필요한; 필연적인", ex:"Sleep is necessary."},
  "useful": {kr:"유용한, 쓸모 있는", ex:"A useful tool."},
  "dangerous": {kr:"위험한", ex:"A dangerous road."},

  "about": {kr:"~에 관하여, ~에 대해; 약, 대략; 여기저기; 막 ~하려는", ex:"A book about birds."},
  "above": {kr:"~위에, ~보다 위에; 앞서 말한; 위에", ex:"The sky above us."},
  "across": {kr:"~을 가로질러, 건너서; 맞은편에; 가로질러", ex:"Walk across the street."},
  "after": {kr:"~후에, 뒤에; ~을 쫓아; ~을 따라; 그 후", ex:"After lunch we left."},
  "against": {kr:"~에 반대하여; ~에 맞서; ~에 기대어; ~에 대비하여", ex:"Vote against the plan."},
  "along": {kr:"~을 따라; ~을 끼고; 앞으로; 함께", ex:"Walk along the river."},
  "among": {kr:"~사이에, ~중에; ~에 둘러싸여", ex:"Among friends."},
  "around": {kr:"~주위에; ~여기저기; 약, 대략; 빙 둘러", ex:"Look around the room."},
  "before": {kr:"~전에; ~앞에; 이전에; ~하기 전에", ex:"Wash your hands before eating."},
  "behind": {kr:"~뒤에; ~에 뒤져; 배후에; 늦어", ex:"Behind the door."},
  "below": {kr:"~아래에, ~보다 아래; 이하의; 아래에", ex:"Below zero."},
  "beside": {kr:"~옆에, ~곁에; ~와 비교하여", ex:"Sit beside me."},
  "between": {kr:"~사이에; ~중에서; 그 사이에", ex:"Between you and me."},
  "beyond": {kr:"~너머; ~을 넘어서; ~이상; 저편에", ex:"Beyond the mountains."},
  "during": {kr:"~동안, ~중에; ~내내", ex:"During the summer."},
  "except": {kr:"~을 제외하고; ~외에는; 제외하다", ex:"Everyone except me."},
  "inside": {kr:"~안에, 내부에; 안쪽; 내부의; 안에", ex:"Inside the box."},
  "outside": {kr:"~밖에, 외부에; 바깥; 외부의; 밖에", ex:"Wait outside."},
  "toward": {kr:"~쪽으로, ~을 향하여; ~에 대하여; ~즈음", ex:"Walk toward the door."},
  "through": {kr:"~을 통하여, 관통하여; ~내내; ~덕분에; 끝까지", ex:"Go through the tunnel."},
  "throughout": {kr:"~전체에 걸쳐; ~내내; 도처에", ex:"Throughout the year."},
  "until": {kr:"~까지; ~할 때까지", ex:"Wait until tomorrow."},
  "within": {kr:"~이내에; ~안에서; 내부에", ex:"Within an hour."},
  "without": {kr:"~없이; ~하지 않고; 밖에", ex:"Coffee without sugar."},
  "upon": {kr:"~위에; ~하자마자; ~에 근거하여", ex:"Once upon a time."},
  "although": {kr:"비록 ~이지만, ~임에도", ex:"Although it rained, we went."},
  "though": {kr:"~이지만, ~인데도; 그렇지만", ex:"It's hard, though."},
  "because": {kr:"~때문에, ~이므로", ex:"I stayed because of the rain."},
  "unless": {kr:"~하지 않는 한; ~이 아니면", ex:"Unless you hurry, we'll be late."},
  "while": {kr:"~하는 동안; ~인 반면; 잠깐", ex:"Read while you wait."},
  "whether": {kr:"~인지 아닌지; ~이든 (아니든)", ex:"I don't know whether to go."},
  "since": {kr:"~이래로, ~이후; ~때문에; 그 이후로", ex:"Since last year."},
  "however": {kr:"그러나, 하지만; 아무리 ~해도", ex:"It's late; however, I'll stay."},
  "therefore": {kr:"그러므로, 따라서", ex:"I think, therefore I am."},
  "moreover": {kr:"게다가, 더욱이", ex:"Moreover, it's cheaper."},
  "instead": {kr:"대신에; 그 대신", ex:"Stay home instead."},
  "besides": {kr:"게다가, 그 외에; ~외에", ex:"Besides, it's too late."},
  "otherwise": {kr:"그렇지 않으면; 그 외에는; 다르게", ex:"Hurry, otherwise we'll miss it."},
  "meanwhile": {kr:"그동안에; 한편", ex:"Meanwhile, I waited."},
  "perhaps": {kr:"아마, 어쩌면", ex:"Perhaps she forgot."},
  "maybe": {kr:"아마, 어쩌면; 혹시", ex:"Maybe tomorrow."},
  "probably": {kr:"아마도, 십중팔구", ex:"It will probably rain."},
  "certainly": {kr:"확실히, 틀림없이; 물론", ex:"I'll certainly come."},
  "actually": {kr:"실제로; 사실은", ex:"Actually, I agree."},
  "usually": {kr:"보통, 대개", ex:"I usually walk to work."},
  "often": {kr:"자주, 흔히", ex:"We often meet here."},
  "always": {kr:"항상, 늘; 언제나", ex:"She is always kind."},
  "never": {kr:"결코 ~않다; 한 번도 ~않다", ex:"I never lie."},
  "sometimes": {kr:"때때로, 가끔", ex:"Sometimes I cook."},
  "already": {kr:"이미, 벌써", ex:"I already ate."},
  "yet": {kr:"아직 (~않다); 이미; 그렇지만", ex:"Not yet."},
  "still": {kr:"여전히, 아직도; 그런데도; 가만히 있는; 정지한", ex:"He is still here."},
  "almost": {kr:"거의, 하마터면", ex:"Almost done."},
  "enough": {kr:"충분한; 충분히; 충분한 양", ex:"That's enough."},
  "quite": {kr:"꽤, 상당히; 완전히", ex:"Quite good."},
  "rather": {kr:"오히려, 차라리; 꽤, 다소", ex:"I'd rather stay."},
  "really": {kr:"정말, 실제로; 매우", ex:"I really like it."},
  "together": {kr:"함께, 같이; 동시에", ex:"Work together."},
  "alone": {kr:"혼자; 홀로; ~만으로", ex:"I live alone."},
  "anymore": {kr:"이제는 (~않다); 더 이상", ex:"I don't smoke anymore."},
  "anyway": {kr:"어쨌든; 게다가", ex:"Thanks anyway."},
  "everywhere": {kr:"어디나, 도처에", ex:"I looked everywhere."},
  "somewhere": {kr:"어딘가에; 어디론가", ex:"Somewhere safe."},
  "anywhere": {kr:"어디든; 어디에도", ex:"I can't find it anywhere."},
  "nowhere": {kr:"아무 데도 ~없다; 어디에도", ex:"Nowhere to go."},
  "everyone": {kr:"모든 사람, 모두", ex:"Everyone is here."},
  "someone": {kr:"누군가, 어떤 사람", ex:"Someone called you."},
  "anyone": {kr:"누구나; (의문·부정) 아무도", ex:"Anyone can join."},
  "everything": {kr:"모든 것, 모두; 가장 중요한 것", ex:"Everything is fine."},
  "something": {kr:"무언가, 어떤 것; 중요한 것", ex:"Say something."},
  "anything": {kr:"무엇이든; (부정) 아무것도", ex:"Anything is possible."},
  "nothing": {kr:"아무것도 ~아니다; 하찮은 것; 영(零)", ex:"Nothing happened."},
  "myself": {kr:"나 자신; 나 스스로", ex:"I did it myself."},
  "yourself": {kr:"너 자신; 스스로", ex:"Help yourself."},
  "himself": {kr:"그 자신; 그 스스로", ex:"He hurt himself."},
  "herself": {kr:"그녀 자신; 그녀 스스로", ex:"She made it herself."},
  "itself": {kr:"그 자체; 그것 스스로", ex:"The door closed itself."},
  "ourselves": {kr:"우리 자신; 우리 스스로", ex:"We enjoyed ourselves."},
  "themselves": {kr:"그들 자신; 그들 스스로", ex:"They blamed themselves."},
  "another": {kr:"또 하나의; 다른; 또 다른 것", ex:"Have another cup."},
  "other": {kr:"다른; 그 밖의; 나머지의; (the other) 다른 하나", ex:"The other side."},
  "each": {kr:"각각의, 각자; 각각", ex:"Each student has a book."},
  "every": {kr:"모든, 매~; ~마다", ex:"Every day."},
  "both": {kr:"둘 다의; 양쪽; 둘 다", ex:"Both answers are right."},
  "either": {kr:"(둘 중) 어느 하나의; 양쪽의; ~도 (또한)", ex:"Either way is fine."},
  "neither": {kr:"(둘 중) 어느 것도 아닌; ~도 아니다", ex:"Neither option works."},
  "several": {kr:"몇몇의, 여럿의", ex:"Several people came."},
  "various": {kr:"여러 가지의, 다양한", ex:"For various reasons."},
  "certain": {kr:"확실한; 어떤, 일정한; 확신하는", ex:"A certain person."},
  "few": {kr:"거의 없는; (a few) 약간의; 소수", ex:"Few people know."},
  "little": {kr:"작은; 어린; 거의 없는; (a little) 조금; 조금", ex:"A little water."},
  "much": {kr:"많은; 많이; 훨씬", ex:"Too much noise."},
  "many": {kr:"많은; 다수; 다수의 사람", ex:"Many years ago."},
  "more": {kr:"더 많은; 더; 더 많은 것", ex:"I need more time."},
  "most": {kr:"가장 많은; 대부분의; 가장; 대부분", ex:"Most people agree."},
  "less": {kr:"더 적은; 덜; ~보다 적게", ex:"Less sugar, please."},
  "least": {kr:"가장 적은; 가장 덜; (at least) 적어도", ex:"The least expensive."},
  "such": {kr:"그러한, 그런; 매우 ~한; 그 정도의", ex:"Such a nice day."},
  "own": {kr:"자기 자신의; 소유하다; 인정하다", ex:"My own room."},
  "ago": {kr:"(지금부터) ~전에", ex:"Two years ago."},
  "once": {kr:"한 번; 한때; 일단 ~하면", ex:"Once a week."},
  "twice": {kr:"두 번; 두 배로", ex:"Twice a day."},
  "soon": {kr:"곧, 머지않아; 빨리", ex:"See you soon."},
  "later": {kr:"나중에, 후에; 더 늦은", ex:"Talk to you later."},
  "ever": {kr:"언젠가; 한 번이라도; 늘", ex:"Have you ever been there?"},
  "far": {kr:"먼; 멀리; 훨씬", ex:"How far is it?"},
  "near": {kr:"가까운; ~가까이; 거의", ex:"Near the station."},
  "ahead": {kr:"앞에, 앞으로; 미리; 앞선", ex:"Go straight ahead."},
  "forward": {kr:"앞으로; 전방의; 전달하다", ex:"Move forward."},
  "backward": {kr:"뒤로; 거꾸로; 뒤떨어진", ex:"Step backward."},
  "indeed": {kr:"정말로, 실로; 사실은", ex:"Thank you indeed."},

  "meeting": {kr:"회의; 모임; 만남; 마주침", ex:"A staff meeting."},
  "product": {kr:"제품, 상품; 생산물; 결과물; (수학) 곱", ex:"A new product."},
  "factory": {kr:"공장", ex:"A car factory."},
  "industry": {kr:"산업, 공업; 업계; 근면", ex:"The tourism industry."},
  "economy": {kr:"경제; 절약; 알뜰함; (좌석) 일반석", ex:"A strong economy."},
  "trade": {kr:"무역, 거래; 교역; 업종; 거래하다; 교환하다", ex:"Foreign trade."},
  "tax": {kr:"세금; 부담; 세금을 부과하다", ex:"Income tax."},
  "income": {kr:"소득, 수입", ex:"A monthly income."},
  "profit": {kr:"이익, 수익; 이득; 이익을 얻다", ex:"Make a profit."},
  "account": {kr:"계좌; 계정; 설명, 기술; 이유; (~을) 설명하다", ex:"A bank account."},
  "budget": {kr:"예산; 비용; 저가의; 예산을 세우다", ex:"A tight budget."},
  "salary": {kr:"급여, 봉급, 월급", ex:"A high salary."},
  "bill": {kr:"청구서, 계산서; 지폐; 법안; 부리; 청구하다", ex:"Pay the bill."},
  "coin": {kr:"동전, 주화; (말을) 만들어 내다", ex:"A gold coin."},
  "cash": {kr:"현금; 돈; 현금으로 바꾸다", ex:"Pay in cash."},
  "wealth": {kr:"부, 재산; 풍부함", ex:"Great wealth."},
  "goods": {kr:"상품, 물품; 화물", ex:"Household goods."},
  "quality": {kr:"질, 품질; 자질, 특성; 고급의", ex:"High quality."},
  "quantity": {kr:"양, 수량; 다량", ex:"A large quantity."},
  "process": {kr:"과정, 절차; 처리하다; 가공하다", ex:"A slow process."},
  "method": {kr:"방법, 방식; 체계", ex:"A new method."},
  "target": {kr:"목표; 표적, 과녁; 대상; 겨냥하다", ex:"Hit the target."},
  "purpose": {kr:"목적, 의도; 용도; 결단력", ex:"On purpose."},
  "task": {kr:"일, 과업; 과제; 임무", ex:"A difficult task."},
  "duty": {kr:"의무, 책무; 임무; 직무; 세금, 관세", ex:"On duty."},
  "role": {kr:"역할; 배역; 임무", ex:"An important role."},
  "position": {kr:"위치; 자세; 입장, 견해; 직위; 배치하다", ex:"A good position."},
  "situation": {kr:"상황, 처지; 위치; 사태", ex:"A difficult situation."},
  "condition": {kr:"상태, 컨디션; 조건; 질환; 길들이다", ex:"In good condition."},
  "event": {kr:"사건; 행사; 종목; 결과", ex:"A big event."},
  "activity": {kr:"활동; 움직임; 활기", ex:"Outdoor activity."},
  "action": {kr:"행동, 조치; 활동; 작용; 소송; 전투", ex:"Take action."},
  "behavior": {kr:"행동, 행위; 태도; 작용", ex:"Good behavior."},
  "attitude": {kr:"태도; 자세; 사고방식", ex:"A positive attitude."},
  "habit": {kr:"습관, 버릇; 습성", ex:"A bad habit."},
  "custom": {kr:"관습, 풍습; 습관; (customs) 세관", ex:"A local custom."},
  "tradition": {kr:"전통; 관례", ex:"A family tradition."},
  "religion": {kr:"종교; 신앙", ex:"Freedom of religion."},
  "belief": {kr:"믿음, 신념; 확신; 신앙", ex:"A strong belief."},
  "knowledge": {kr:"지식; 인식; 이해", ex:"Common knowledge."},
  "wisdom": {kr:"지혜; 현명함; 학식", ex:"Words of wisdom."},
  "truth": {kr:"진실, 사실; 진리", ex:"Tell the truth."},
  "fear": {kr:"두려움, 공포; 우려; 두려워하다; 염려하다", ex:"Fear of heights."},
  "joy": {kr:"기쁨, 환희; 즐거움", ex:"Tears of joy."},
  "anger": {kr:"분노, 화; 화나게 하다", ex:"Control your anger."},
  "sadness": {kr:"슬픔", ex:"A deep sadness."},
  "pain": {kr:"고통, 아픔; 통증; 노고; 아프게 하다", ex:"Back pain."},
  "pleasure": {kr:"기쁨, 즐거움; 쾌락; 만족", ex:"With pleasure."},
  "comfort": {kr:"편안함, 안락; 위로; 위안; 위로하다", ex:"Live in comfort."},
  "stress": {kr:"스트레스; 압박; 강조; 강세; 강조하다", ex:"Under stress."},
  "trouble": {kr:"문제, 곤란; 고생; 분쟁; 폐를 끼치다; 괴롭히다", ex:"In trouble."},
  "danger": {kr:"위험; 위협", ex:"Out of danger."},
  "safety": {kr:"안전; 안전성", ex:"For your safety."},
  "freedom": {kr:"자유; 해방; 자유로움", ex:"Freedom of speech."},
  "justice": {kr:"정의; 공정; 사법; 재판", ex:"Fight for justice."},
  "community": {kr:"공동체, 지역사회; 집단; 공유", ex:"A local community."},
  "population": {kr:"인구; 개체 수; 주민", ex:"A large population."},
  "nation": {kr:"국가, 나라; 국민; 민족", ex:"A great nation."},
  "border": {kr:"국경, 경계; 가장자리; 테두리; 접하다", ex:"Cross the border."},
  "region": {kr:"지역, 지방; 영역; 부위", ex:"A cold region."},
  "capital": {kr:"수도; 자본; 대문자; 자본의; 주요한", ex:"The capital city."},
  "crowd": {kr:"군중, 무리; 떼; 붐비다; 밀어닥치다", ex:"A huge crowd."},
  "travel": {kr:"여행하다; 이동하다; 다니다; 여행; 이동", ex:"Travel abroad."},
  "trip": {kr:"여행; 출장; (발이) 걸리다; 실수", ex:"A business trip."},
  "journey": {kr:"여행, 여정; 과정; 이동하다", ex:"A long journey."},
  "tour": {kr:"관광, 여행; 순회; 견학; 둘러보다", ex:"A city tour."},
  "flight": {kr:"비행; 항공편; 도주; 한 줄(계단)", ex:"A long flight."},
  "airport": {kr:"공항", ex:"At the airport."},
  "station": {kr:"역; 정거장; 방송국; 부서; 배치하다", ex:"A train station."},
  "ticket": {kr:"표, 입장권; 승차권; 위반 딱지", ex:"A bus ticket."},
  "passport": {kr:"여권; (~로 가는) 수단", ex:"Show your passport."},
  "luggage": {kr:"수하물, 짐", ex:"Pack your luggage."},
  "bridge": {kr:"다리, 교량; 가교; (코·안경) 다리; 다리를 놓다", ex:"Cross the bridge."},
  "corner": {kr:"모퉁이, 구석; 코너; 궁지; 궁지에 몰다", ex:"Around the corner."},
  "path": {kr:"길, 경로; 진로; 방향", ex:"A garden path."},
  "track": {kr:"길, 자취; 선로; 트랙; 추적하다; 음원", ex:"A dirt track."},
  "traffic": {kr:"교통(량); 통행; 밀거래; 거래하다", ex:"Heavy traffic."},
  "vehicle": {kr:"차량, 탈것; 수단, 매개", ex:"An electric vehicle."},
  "engine": {kr:"엔진, 기관; 기관차; 동력", ex:"A car engine."},
  "wheel": {kr:"바퀴; 핸들; 회전; 돌리다", ex:"The front wheel."},
  "speed": {kr:"속도; 빠르기; 빨리 가다; 과속하다", ex:"At high speed."},
  "distance": {kr:"거리; 간격; 먼 곳; 차이", ex:"A short distance."},
  "direction": {kr:"방향; 지시; 감독; 방면", ex:"In every direction."},
  "address": {kr:"주소; 연설; 다루다; 연설하다; (~라고) 부르다", ex:"My home address."},
  "message": {kr:"메시지; 전갈; 교훈; 메시지를 보내다", ex:"Send a message."},
  "communication": {kr:"의사소통; 통신; 전달; 연락", ex:"Good communication."},
  "media": {kr:"매체, 미디어; 언론; 매개", ex:"Social media."},
  "internet": {kr:"인터넷", ex:"Use the internet."},
  "network": {kr:"망, 네트워크; 인맥; 방송망; 연결망을 형성하다", ex:"A computer network."},
  "screen": {kr:"화면, 스크린; 가리개; 칸막이; 가리다; 선별하다", ex:"A touch screen."},
  "data": {kr:"자료, 데이터; 정보", ex:"Collect the data."},
  "file": {kr:"파일; 서류철; 줄(연장); 정리하다; 제출하다", ex:"Open the file."},
  "code": {kr:"암호; 부호; 규범; (컴퓨터) 코드; 부호화하다", ex:"A secret code."},
  "device": {kr:"장치, 기기; 방책; 고안물", ex:"A small device."},
  "object": {kr:"물체, 물건; 대상; 목적; (문법) 목적어; 반대하다", ex:"A strange object."},
  "material": {kr:"재료, 물질; 자료; 천; 물질적인", ex:"Raw material."},
  "metal": {kr:"금속", ex:"A piece of metal."},
  "wood": {kr:"나무, 목재; (woods) 숲", ex:"A piece of wood."},
  "plastic": {kr:"플라스틱; 비닐; 성형의; 유연한", ex:"A plastic bag."},
  "gold": {kr:"금; 금빛; 금메달; 황금의", ex:"Pure gold."},
  "silver": {kr:"은; 은빛; 은메달; 은색의", ex:"A silver ring."},
  "oil": {kr:"기름, 석유; 유화 물감; 기름칠하다", ex:"Olive oil."},
  "gas": {kr:"기체, 가스; 휘발유; 가스를 공급하다", ex:"Natural gas."},
  "smoke": {kr:"연기; 흡연; 담배를 피우다; (연기가) 나다", ex:"Cigarette smoke."},
  "heat": {kr:"열; 더위; 난방; 데우다; 가열하다", ex:"Turn up the heat."},
  "temperature": {kr:"온도, 기온; 체온; 열", ex:"Room temperature."},

  "kitchen": {kr:"부엌, 주방", ex:"Cook in the kitchen."},
  "bedroom": {kr:"침실", ex:"A cozy bedroom."},
  "bathroom": {kr:"욕실, 화장실", ex:"Clean the bathroom."},
  "garden": {kr:"정원, 뜰; 텃밭; 정원을 가꾸다", ex:"A flower garden."},
  "yard": {kr:"마당, 뜰; 작업장; 야드(단위)", ex:"Play in the yard."},
  "roof": {kr:"지붕; 천장; 최고점", ex:"A red roof."},
  "ceiling": {kr:"천장; 상한선, 한도", ex:"A high ceiling."},
  "stair": {kr:"계단(의 한 단); (stairs) 계단", ex:"Climb the stairs."},
  "furniture": {kr:"가구; 비품", ex:"New furniture."},
  "chair": {kr:"의자; 의장; 의장직을 맡다", ex:"Sit on the chair."},
  "desk": {kr:"책상; (호텔) 데스크, 접수처", ex:"A messy desk."},
  "bed": {kr:"침대; (강·바다) 바닥; 화단; 잠자리", ex:"Make your bed."},
  "sofa": {kr:"소파, 긴 의자", ex:"Relax on the sofa."},
  "lamp": {kr:"램프, 등; 전등", ex:"Turn on the lamp."},
  "clock": {kr:"시계; 계기판; 시간을 재다", ex:"The wall clock."},
  "mirror": {kr:"거울; 반사하다; 비추다", ex:"Look in the mirror."},
  "blanket": {kr:"담요; 뒤덮는 것; 일률적인; 뒤덮다", ex:"A warm blanket."},
  "pillow": {kr:"베개", ex:"A soft pillow."},
  "towel": {kr:"수건, 타월", ex:"A clean towel."},
  "soap": {kr:"비누", ex:"Wash with soap."},
  "plate": {kr:"접시; 판; 번호판; 도금하다", ex:"A dinner plate."},
  "bowl": {kr:"그릇, 사발; 한 그릇; (공을) 굴리다", ex:"A bowl of soup."},
  "spoon": {kr:"숟가락; 한 숟갈", ex:"Use a spoon."},
  "fork": {kr:"포크; 갈래; 갈림길; 갈라지다", ex:"A knife and fork."},
  "knife": {kr:"칼, 나이프; 칼로 베다", ex:"A sharp knife."},
  "kettle": {kr:"주전자", ex:"Boil the kettle."},
  "pot": {kr:"냄비, 솥; 항아리; 화분; 큰돈", ex:"A cooking pot."},
  "pan": {kr:"팬, 프라이팬; 냄비", ex:"A frying pan."},
  "stove": {kr:"가스레인지, 난로", ex:"Cook on the stove."},
  "fridge": {kr:"냉장고", ex:"Put it in the fridge."},
  "clothes": {kr:"옷, 의복", ex:"Wash your clothes."},
  "shirt": {kr:"셔츠", ex:"A white shirt."},
  "dress": {kr:"드레스, 원피스; 옷차림; 옷을 입다; 손질하다", ex:"A red dress."},
  "coat": {kr:"코트, 외투; (동물) 털; (페인트) 칠; 입히다", ex:"A winter coat."},
  "shoe": {kr:"신발, 구두; 편자", ex:"Tie your shoe."},
  "hat": {kr:"모자", ex:"Wear a hat."},
  "pocket": {kr:"주머니; 호주머니; 소형의; (돈을) 챙기다", ex:"In my pocket."},
  "button": {kr:"단추; 버튼; 단추를 채우다", ex:"Press the button."},
  "cotton": {kr:"면, 솜; 목화", ex:"A cotton shirt."},
  "lesson": {kr:"수업; 과; 교훈", ex:"An English lesson."},
  "class": {kr:"수업; 학급; 계층; 등급; 분류하다", ex:"Math class."},
  "subject": {kr:"과목; 주제; 대상; (문법) 주어; 국민; ~을 받게 하다", ex:"My favorite subject."},
  "exam": {kr:"시험", ex:"Pass the exam."},
  "grade": {kr:"성적, 등급; 학년; 품질; 채점하다; 등급을 매기다", ex:"A good grade."},
  "score": {kr:"점수, 득점; 악보; 득점하다; 새기다", ex:"A high score."},
  "homework": {kr:"숙제, 과제", ex:"Do your homework."},
  "pencil": {kr:"연필", ex:"Write with a pencil."},
  "notebook": {kr:"공책, 노트; 노트북 컴퓨터", ex:"Open your notebook."},
  "dictionary": {kr:"사전", ex:"Use a dictionary."},
  "library": {kr:"도서관; 서재; 장서", ex:"Study at the library."},
  "college": {kr:"대학; 단과대학", ex:"Go to college."},
  "university": {kr:"대학교, 종합대학", ex:"A famous university."},
  "degree": {kr:"학위; 정도; (온도·각도) 도; 등급", ex:"A college degree."},
  "course": {kr:"강좌, 과정; 진로; 코스; (식사) 코스; 당연히", ex:"A cooking course."},
  "topic": {kr:"주제, 화제", ex:"Change the topic."},
  "title": {kr:"제목; 직함; 칭호; 우승; 소유권; 제목을 붙이다", ex:"The book title."},
  "sentence": {kr:"문장; 형벌, 선고; 선고하다", ex:"A long sentence."},
  "meaning": {kr:"의미, 뜻; 의의", ex:"The meaning of life."},
  "spelling": {kr:"철자, 맞춤법", ex:"Check the spelling."},
  "grammar": {kr:"문법; 어법", ex:"English grammar."},
  "memory": {kr:"기억; 기억력; 추억; (컴퓨터) 메모리", ex:"A good memory."},
  "lake": {kr:"호수", ex:"Swim in the lake."},
  "pond": {kr:"연못", ex:"Fish in the pond."},
  "hill": {kr:"언덕, 야산; 경사", ex:"Climb the hill."},
  "valley": {kr:"계곡, 골짜기; 유역", ex:"A green valley."},
  "forest": {kr:"숲, 삼림", ex:"A dark forest."},
  "desert": {kr:"사막; 버리다, 저버리다", ex:"A hot desert."},
  "island": {kr:"섬; 고립된 곳", ex:"A small island."},
  "wave": {kr:"파도, 물결; (감정의) 물결; 흔들다; 손을 흔들다", ex:"A big wave."},
  "sand": {kr:"모래; (sands) 모래밭", ex:"Walk on the sand."},
  "soil": {kr:"흙, 토양; 토지; 더럽히다", ex:"Rich soil."},
  "seed": {kr:"씨, 씨앗; 종자; 근원; 씨를 뿌리다", ex:"Plant a seed."},
  "root": {kr:"뿌리; 근원; 어근; 뿌리내리다", ex:"The root of a tree."},
  "branch": {kr:"나뭇가지; 지점, 지사; 분야; 갈라지다", ex:"A tree branch."},
  "crop": {kr:"작물, 수확물; 무리; 자르다; 재배되다", ex:"A rice crop."},
  "insect": {kr:"곤충, 벌레", ex:"A small insect."},
  "bee": {kr:"벌, 꿀벌", ex:"A busy bee."},
  "butterfly": {kr:"나비; 접영", ex:"A colorful butterfly."},
  "horse": {kr:"말; 목마; (속어) 사람", ex:"Ride a horse."},
  "cow": {kr:"암소, 젖소", ex:"Milk the cow."},
  "pig": {kr:"돼지; 욕심꾸러기", ex:"A fat pig."},
  "sheep": {kr:"양; 순한 사람", ex:"A flock of sheep."},
  "chicken": {kr:"닭; 닭고기; 겁쟁이; 겁먹은", ex:"Fried chicken."},
  "duck": {kr:"오리; 오리고기; (몸을) 숙이다; 피하다", ex:"A yellow duck."},
  "rabbit": {kr:"토끼", ex:"A white rabbit."},
  "mouse": {kr:"생쥐, 쥐; (컴퓨터) 마우스", ex:"A computer mouse."},
  "lion": {kr:"사자; 용맹한 사람", ex:"A brave lion."},
  "tiger": {kr:"호랑이", ex:"A wild tiger."},
  "bear": {kr:"곰; 참다, 견디다; 지니다; (아이를) 낳다", ex:"A big bear."},
  "elephant": {kr:"코끼리", ex:"A huge elephant."},
  "monkey": {kr:"원숭이; 장난꾸러기; 까불다", ex:"A clever monkey."},
  "snake": {kr:"뱀; 교활한 사람; 구불구불 나아가다", ex:"A long snake."},
  "spider": {kr:"거미", ex:"A scary spider."},
  "wing": {kr:"날개; (건물) 동, 부속 건물; (정당) 분파", ex:"A bird's wing."},
  "tail": {kr:"꼬리; 끝부분; 미행하다", ex:"A dog's tail."},
  "feather": {kr:"깃털", ex:"A soft feather."},
  "fur": {kr:"털, 모피", ex:"Soft fur."},
  "tooth": {kr:"이, 치아; (톱니) 이", ex:"Brush your teeth."},
  "neck": {kr:"목; (옷의) 목 부분; 좁은 부분", ex:"A long neck."},
  "shoulder": {kr:"어깨; (도로) 갓길; (책임을) 떠맡다", ex:"Carry on your shoulder."},
  "knee": {kr:"무릎", ex:"Bend your knee."},
  "stomach": {kr:"위, 배; 복부; 참다", ex:"An empty stomach."},
  "brain": {kr:"뇌; 두뇌, 지능; 똑똑한 사람", ex:"Use your brain."},
  "lung": {kr:"폐, 허파", ex:"Healthy lungs."},
  "muscle": {kr:"근육; 힘, 영향력", ex:"Strong muscles."},
};
