// ── ButterFly Word Dictionary : 한국어 뜻 + 예문 (검수 코어) ──
// 직접 검수한 고빈도 핵심 단어. key=영단어, value={kr:뜻, ex:예문}.
// 발음기호는 bwd-pron.js(BWD_PRON)가 별도로 채움.
// 배치 1 — 최고빈도 핵심 어휘.
const BWD_DICT = {
  "time": {kr:"시간, 때", ex:"What time is it now?"},
  "people": {kr:"사람들", ex:"Many people came to the party."},
  "way": {kr:"방법, 길", ex:"This is the best way to learn."},
  "day": {kr:"날, 하루", ex:"Have a nice day!"},
  "man": {kr:"남자, 사람", ex:"The man is reading a book."},
  "thing": {kr:"것, 물건, 일", ex:"That is a strange thing."},
  "woman": {kr:"여자", ex:"The woman works at a hospital."},
  "life": {kr:"삶, 생명", ex:"Life is full of surprises."},
  "child": {kr:"아이, 어린이", ex:"The child is playing outside."},
  "world": {kr:"세계, 세상", ex:"She wants to travel the world."},
  "school": {kr:"학교", ex:"My son goes to school by bus."},
  "family": {kr:"가족", ex:"I love my family very much."},
  "student": {kr:"학생", ex:"She is a hard-working student."},
  "country": {kr:"나라, 시골", ex:"Korea is a beautiful country."},
  "problem": {kr:"문제", ex:"We need to solve this problem."},
  "question": {kr:"질문", ex:"Can I ask you a question?"},
  "work": {kr:"일하다; 일, 직장", ex:"I work from nine to six."},
  "place": {kr:"장소, 곳", ex:"This is a quiet place to read."},
  "week": {kr:"주, 일주일", ex:"I will see you next week."},
  "year": {kr:"해, 연도", ex:"Last year was very busy."},
  "money": {kr:"돈", ex:"He saved money for a trip."},
  "story": {kr:"이야기", ex:"She told us a funny story."},
  "month": {kr:"달, 월", ex:"It rained a lot last month."},
  "book": {kr:"책", ex:"I read a book before bed."},
  "water": {kr:"물", ex:"Please drink more water."},
  "room": {kr:"방", ex:"My room is small but cozy."},
  "friend": {kr:"친구", ex:"He is my best friend."},
  "house": {kr:"집", ex:"They live in a big house."},
  "city": {kr:"도시", ex:"Seoul is a busy city."},
  "name": {kr:"이름", ex:"What is your name?"},
  "night": {kr:"밤", ex:"We talked late into the night."},
  "food": {kr:"음식", ex:"Korean food is delicious."},
  "car": {kr:"자동차", ex:"She drives a red car."},
  "word": {kr:"단어, 말", ex:"I don't know this word."},
  "company": {kr:"회사, 동행", ex:"He works for a big company."},
  "number": {kr:"숫자, 번호", ex:"Call this number for help."},
  "group": {kr:"집단, 무리", ex:"We worked in a small group."},
  "part": {kr:"부분, 일부", ex:"This is the hardest part."},
  "case": {kr:"경우, 사건, 상자", ex:"In that case, let's wait."},
  "point": {kr:"점, 요점; 가리키다", ex:"That's a good point."},
  "government": {kr:"정부", ex:"The government raised taxes."},
  "right": {kr:"옳은, 오른쪽; 권리", ex:"You made the right choice."},
  "study": {kr:"공부하다; 연구", ex:"I study English every day."},
  "job": {kr:"일자리, 직업", ex:"She got a new job."},
  "business": {kr:"사업, 일", ex:"He started his own business."},
  "system": {kr:"체계, 시스템", ex:"The new system works well."},
  "program": {kr:"프로그램, 계획", ex:"This program is very useful."},
  "service": {kr:"서비스, 봉사", ex:"The hotel service was great."},
  "health": {kr:"건강", ex:"Exercise is good for your health."},
  "history": {kr:"역사", ex:"I enjoy reading history."},
  "music": {kr:"음악", ex:"She listens to music while running."},
  "art": {kr:"예술, 미술", ex:"He studies modern art."},
  "love": {kr:"사랑; 사랑하다", ex:"They fell in love."},
  "power": {kr:"힘, 권력, 전력", ex:"The storm cut the power."},
  "war": {kr:"전쟁", ex:"The war lasted four years."},
  "team": {kr:"팀, 단체", ex:"Our team won the game."},
  "game": {kr:"경기, 게임", ex:"Let's play a game."},
  "head": {kr:"머리; 향하다", ex:"My head hurts a little."},
  "hand": {kr:"손; 건네주다", ex:"Raise your hand to answer."},
  "eye": {kr:"눈", ex:"She has bright blue eyes."},
  "face": {kr:"얼굴; 직면하다", ex:"Wash your face in the morning."},
  "body": {kr:"몸, 신체", ex:"Stretch your body before running."},
  "heart": {kr:"심장, 마음", ex:"My heart was beating fast."},
  "mother": {kr:"어머니", ex:"My mother cooks very well."},
  "father": {kr:"아버지", ex:"His father is a teacher."},
  "parent": {kr:"부모", ex:"My parents live in Busan."},
  "baby": {kr:"아기", ex:"The baby is sleeping."},
  "girl": {kr:"소녀, 여자아이", ex:"The girl is drawing a picture."},
  "boy": {kr:"소년, 남자아이", ex:"The boy kicked the ball."},
  "morning": {kr:"아침", ex:"I drink coffee every morning."},
  "today": {kr:"오늘", ex:"Today is my birthday."},
  "tomorrow": {kr:"내일", ex:"See you tomorrow."},
  "yesterday": {kr:"어제", ex:"It rained yesterday."},
  "hour": {kr:"시간(60분)", ex:"The trip takes two hours."},
  "minute": {kr:"분, 잠깐", ex:"Wait a minute, please."},
  "light": {kr:"빛, 불; 가벼운", ex:"Turn off the light."},
  "color": {kr:"색깔", ex:"Blue is my favorite color."},
  "door": {kr:"문", ex:"Please close the door."},
  "window": {kr:"창문", ex:"Open the window for fresh air."},
  "table": {kr:"탁자, 식탁, 표", ex:"Put the dishes on the table."},
  "phone": {kr:"전화", ex:"My phone is out of battery."},
  "computer": {kr:"컴퓨터", ex:"He fixed my computer."},
  "street": {kr:"거리, 길", ex:"The street is full of cars."},
  "tree": {kr:"나무", ex:"A bird sat on the tree."},
  "animal": {kr:"동물", ex:"My favorite animal is the dog."},
  "dog": {kr:"개", ex:"The dog is barking."},
  "cat": {kr:"고양이", ex:"The cat is sleeping on the sofa."},
  "fish": {kr:"물고기, 생선; 낚시하다", ex:"We had fish for dinner."},
  "bird": {kr:"새", ex:"A bird is singing outside."},
  "flower": {kr:"꽃", ex:"She gave me a flower."},
  "sun": {kr:"태양, 해", ex:"The sun is very bright today."},
  "moon": {kr:"달", ex:"The moon is full tonight."},
  "sea": {kr:"바다", ex:"We swam in the sea."},
  "river": {kr:"강", ex:"The river flows to the sea."},
  "mountain": {kr:"산", ex:"They climbed the mountain."},
  "sky": {kr:"하늘", ex:"The sky is clear and blue."},
  "rain": {kr:"비; 비가 오다", ex:"The rain stopped at noon."},
  "snow": {kr:"눈; 눈이 오다", ex:"Children love to play in the snow."},
  "wind": {kr:"바람", ex:"The wind is very strong today."},
  "fire": {kr:"불, 화재", ex:"They sat around the fire."},
  "make": {kr:"만들다, ~하게 하다", ex:"Let's make a cake."},
  "take": {kr:"가지다, 데려가다, 걸리다", ex:"Take an umbrella with you."},
  "give": {kr:"주다", ex:"Please give me a hand."},
  "get": {kr:"얻다, 받다, ~되다", ex:"I need to get some sleep."},
  "go": {kr:"가다", ex:"Let's go to the park."},
  "come": {kr:"오다", ex:"Come here, please."},
  "see": {kr:"보다, 알다", ex:"I can see the mountain."},
  "look": {kr:"보다, ~처럼 보이다", ex:"Look at the beautiful sunset."},
  "know": {kr:"알다", ex:"I know the answer."},
  "think": {kr:"생각하다", ex:"I think you are right."},
  "want": {kr:"원하다", ex:"I want a cup of tea."},
  "need": {kr:"필요하다; 필요", ex:"You need to rest."},
  "find": {kr:"찾다, 발견하다", ex:"I can't find my keys."},
  "tell": {kr:"말하다, 알려주다", ex:"Tell me the truth."},
  "ask": {kr:"묻다, 부탁하다", ex:"May I ask a favor?"},
  "say": {kr:"말하다", ex:"What did you say?"},
  "talk": {kr:"이야기하다; 대화", ex:"Let's talk later."},
  "speak": {kr:"말하다, (언어를) 하다", ex:"Do you speak English?"},
  "read": {kr:"읽다", ex:"She reads every night."},
  "write": {kr:"쓰다", ex:"Write your name here."},
  "learn": {kr:"배우다", ex:"I want to learn Spanish."},
  "teach": {kr:"가르치다", ex:"She teaches math."},
  "play": {kr:"놀다, (운동·악기를) 하다", ex:"The kids play in the yard."},
  "run": {kr:"달리다, 운영하다", ex:"He runs every morning."},
  "walk": {kr:"걷다; 산책", ex:"Let's walk to the station."},
  "eat": {kr:"먹다", ex:"What did you eat for lunch?"},
  "drink": {kr:"마시다; 음료", ex:"Drink plenty of water."},
  "sleep": {kr:"자다; 잠", ex:"I didn't sleep well last night."},
  "buy": {kr:"사다", ex:"I want to buy a new phone."},
  "sell": {kr:"팔다", ex:"They sell fresh fruit here."},
  "pay": {kr:"지불하다; 급여", ex:"I will pay by card."},
  "open": {kr:"열다; 열린", ex:"The store opens at nine."},
  "close": {kr:"닫다; 가까운", ex:"Close the door, please."},
  "start": {kr:"시작하다; 시작", ex:"The movie starts at seven."},
  "stop": {kr:"멈추다; 정류장", ex:"The bus stopped suddenly."},
  "help": {kr:"돕다; 도움", ex:"Can you help me?"},
  "use": {kr:"사용하다; 사용", ex:"May I use your pen?"},
  "call": {kr:"부르다, 전화하다; 전화", ex:"Call me tonight."},
  "feel": {kr:"느끼다", ex:"I feel happy today."},
  "keep": {kr:"유지하다, 보관하다", ex:"Keep the change."},
  "let": {kr:"~하게 하다, 허락하다", ex:"Let me think about it."},
  "live": {kr:"살다; 살아 있는", ex:"I live near the beach."},
  "move": {kr:"움직이다, 이사하다", ex:"They moved to a new city."},
  "turn": {kr:"돌다, 바꾸다; 차례", ex:"Turn left at the corner."},
  "change": {kr:"바꾸다, 변하다; 변화, 잔돈", ex:"We need to change our plan."},
  "happen": {kr:"일어나다, 발생하다", ex:"What happened here?"},
  "meet": {kr:"만나다", ex:"Let's meet at noon."},
  "wait": {kr:"기다리다", ex:"Please wait a moment."},
  "remember": {kr:"기억하다", ex:"I can't remember her name."},
  "forget": {kr:"잊다", ex:"Don't forget your umbrella."},
  "understand": {kr:"이해하다", ex:"I understand your point."},
  "believe": {kr:"믿다", ex:"I believe you."},
  "hope": {kr:"바라다; 희망", ex:"I hope you feel better."},
  "enjoy": {kr:"즐기다", ex:"Enjoy your meal."},
  "win": {kr:"이기다", ex:"Our team will win."},
  "lose": {kr:"잃다, 지다", ex:"Don't lose your ticket."},
  "build": {kr:"짓다, 건설하다", ex:"They will build a bridge."},
  "break": {kr:"깨다, 부수다; 휴식", ex:"Be careful not to break it."},
  "carry": {kr:"나르다, 들고 다니다", ex:"Can you carry this bag?"},
  "bring": {kr:"가져오다, 데려오다", ex:"Bring your friend along."},
  "send": {kr:"보내다", ex:"I will send you an email."},
  "show": {kr:"보여주다; 쇼", ex:"Show me your photos."},
  "good": {kr:"좋은", ex:"This is a good idea."},
  "bad": {kr:"나쁜", ex:"The weather is bad today."},
  "big": {kr:"큰", ex:"That is a big house."},
  "small": {kr:"작은", ex:"I have a small car."},
  "new": {kr:"새로운", ex:"I bought a new bag."},
  "old": {kr:"늙은, 오래된", ex:"This is an old building."},
  "long": {kr:"긴, 오랜", ex:"It was a long trip."},
  "short": {kr:"짧은, 키 작은", ex:"Take a short break."},
  "high": {kr:"높은", ex:"The price is too high."},
  "low": {kr:"낮은", ex:"The shelf is very low."},
  "hot": {kr:"뜨거운, 더운", ex:"The soup is hot."},
  "cold": {kr:"차가운, 추운; 감기", ex:"It's cold outside."},
  "happy": {kr:"행복한", ex:"She looks happy."},
  "sad": {kr:"슬픈", ex:"He felt sad about the news."},
  "easy": {kr:"쉬운", ex:"The test was easy."},
  "hard": {kr:"어려운, 단단한; 열심히", ex:"This problem is hard."},
  "fast": {kr:"빠른; 빨리", ex:"He is a fast runner."},
  "slow": {kr:"느린", ex:"The internet is slow today."},
  "early": {kr:"이른; 일찍", ex:"I woke up early."},
  "late": {kr:"늦은; 늦게", ex:"Sorry, I'm late."},
  "important": {kr:"중요한", ex:"This is an important meeting."},
  "beautiful": {kr:"아름다운", ex:"What a beautiful view!"},
  "different": {kr:"다른", ex:"We have different opinions."},
  "same": {kr:"같은", ex:"We go to the same school."},
  "true": {kr:"사실인, 진실한", ex:"Is the story true?"},
  "free": {kr:"자유로운, 무료의", ex:"The event is free."},
  "full": {kr:"가득 찬, 배부른", ex:"The bus was full."},
  "empty": {kr:"빈", ex:"The box is empty."},
  "clean": {kr:"깨끗한; 청소하다", ex:"Keep your room clean."},
  "dark": {kr:"어두운", ex:"The room was dark."},
  "young": {kr:"젊은, 어린", ex:"She is still young."},
  "strong": {kr:"강한, 튼튼한", ex:"He is very strong."},
  "weak": {kr:"약한", ex:"I feel weak today."},
  "rich": {kr:"부유한, 풍부한", ex:"He is a rich man."},
  "poor": {kr:"가난한, 불쌍한", ex:"They were very poor."},
  "safe": {kr:"안전한", ex:"This area is safe at night."},
  "ready": {kr:"준비된", ex:"Are you ready to go?"},
  "sure": {kr:"확신하는", ex:"I'm not sure about that."},
  "nice": {kr:"좋은, 친절한", ex:"She is a nice person."},
  "kind": {kr:"친절한; 종류", ex:"Thank you, you're so kind."},
  "great": {kr:"훌륭한, 거대한", ex:"That's a great idea."},
  "next": {kr:"다음의", ex:"See you next time."},
  "last": {kr:"마지막의, 지난; 지속되다", ex:"This is the last chance."},
  "first": {kr:"첫 번째의; 먼저", ex:"He came first in the race."},
  "able": {kr:"~할 수 있는", ex:"She is able to speak three languages."}
};
