const DEFAULT_WORDS = {
  egg:[
    {en:'apple',kr:'사과',ph:'[ˈæpl]',meanings:['사과'],tip:'에이플 = 사과!',ex:'I eat an apple.',img:'🍎'},
    {en:'book',kr:'책',ph:'[bʊk]',meanings:['책'],tip:'북 = 책!',ex:'I read a book.',img:'📚'},
    {en:'cat',kr:'고양이',ph:'[kæt]',meanings:['고양이'],tip:'캣 = 고양이!',ex:'The cat is cute.',img:'🐱'},
    {en:'dog',kr:'개',ph:'[dɒɡ]',meanings:['개'],tip:'도그 = 개!',ex:'My dog is big.',img:'🐶'},
    {en:'egg',kr:'달걀',ph:'[eɡ]',meanings:['달걀'],tip:'에그 = 달걀!',ex:'I eat an egg.',img:'🥚'},
    {en:'fish',kr:'물고기',ph:'[fɪʃ]',meanings:['물고기'],tip:'피쉬 = 물고기!',ex:'The fish swims.',img:'🐟'},
    {en:'happy',kr:'행복한',ph:'[ˈhæpi]',meanings:['행복한'],tip:'해피 = 행복!',ex:'I am happy.',img:'😊'},
    {en:'jump',kr:'뛰다',ph:'[dʒʌmp]',meanings:['뛰다'],tip:'점프 = 뛰다!',ex:'I jump high.',img:'🦘'},
    {en:'love',kr:'사랑',ph:'[lʌv]',meanings:['사랑'],tip:'러브 = 사랑!',ex:'I love my family.',img:'❤️'},
    {en:'milk',kr:'우유',ph:'[mɪlk]',meanings:['우유'],tip:'밀크 = 우유!',ex:'I drink milk.',img:'🥛'},
    {en:'night',kr:'밤',ph:'[naɪt]',meanings:['밤'],tip:'나이트 = 밤!',ex:'Stars shine at night.',img:'🌙'},
    {en:'open',kr:'열다',ph:'[ˈəʊpən]',meanings:['열다'],tip:'오픈 = 열다!',ex:'Open the door.',img:'🚪'},
    {en:'rain',kr:'비',ph:'[reɪn]',meanings:['비'],tip:'레인 = 비!',ex:'It is raining.',img:'🌧️'},
    {en:'sun',kr:'태양',ph:'[sʌn]',meanings:['태양'],tip:'썬 = 태양!',ex:'The sun is bright.',img:'☀️'},
    {en:'tree',kr:'나무',ph:'[triː]',meanings:['나무'],tip:'트리 = 나무!',ex:'The tree is tall.',img:'🌳'},
    {en:'water',kr:'물',ph:'[ˈwɔːtər]',meanings:['물'],tip:'워터 = 물!',ex:'I drink water.',img:'💧'},
    {en:'yellow',kr:'노란',ph:'[ˈjeləʊ]',meanings:['노란'],tip:'옐로우 = 노란!',ex:'The sun is yellow.',img:'🌻'},
    {en:'zoo',kr:'동물원',ph:'[zuː]',meanings:['동물원'],tip:'주 = 동물원!',ex:'I go to the zoo.',img:'🦁'},
    {en:'kind',kr:'친절한',ph:'[kaɪnd]',meanings:['친절한'],tip:'카인드 = 친절!',ex:'She is kind.',img:'🤝'},
    {en:'play',kr:'놀다',ph:'[pleɪ]',meanings:['놀다'],tip:'플레이 = 놀다!',ex:'Children play outside.',img:'🎮'},
  ],
  baby:[
    {en:'dream',kr:'꿈',ph:'[driːm]',meanings:['꿈'],tip:'드림 = 꿈!',ex:'I have a dream.',img:'💭'},
    {en:'ocean',kr:'바다',ph:'[ˈəʊʃən]',meanings:['바다'],tip:'오션 = 바다!',ex:'The ocean is deep.',img:'🌊'},
    {en:'peace',kr:'평화',ph:'[piːs]',meanings:['평화'],tip:'피스 = 평화!',ex:'I want peace.',img:'🕊️'},
    {en:'smart',kr:'똑똑한',ph:'[smɑːt]',meanings:['똑똑한'],tip:'스마트 = 똑똑!',ex:'She is smart.',img:'🧠'},
    {en:'magic',kr:'마법',ph:'[ˈmædʒɪk]',meanings:['마법'],tip:'매직 = 마법!',ex:'It is like magic.',img:'🪄'},
    {en:'lucky',kr:'운이 좋은',ph:'[ˈlʌki]',meanings:['행운의'],tip:'럭키 = 행운!',ex:'I am lucky today.',img:'🍀'},
    {en:'fresh',kr:'신선한',ph:'[freʃ]',meanings:['신선한'],tip:'프레시 = 신선!',ex:'Fresh air is good.',img:'🌿'},
    {en:'brave',kr:'용감한',ph:'[breɪv]',meanings:['용감한'],tip:'브레이브 = 용감!',ex:'She is brave.',img:'🦁'},
    {en:'quiet',kr:'조용한',ph:'[ˈkwaɪət]',meanings:['조용한'],tip:'콰이어트 = 조용!',ex:'Be quiet.',img:'🤫'},
    {en:'world',kr:'세상',ph:'[wɜːld]',meanings:['세상'],tip:'월드 = 세상!',ex:'It is a big world.',img:'🌍'},
  ],
  crown:[
    {en:'achieve',kr:'성취하다',ph:'[əˈtʃiːv]',meanings:['성취하다'],tip:'어치브 = 성취!',ex:'Achieve your goals.',img:'🏆'},
    {en:'balance',kr:'균형',ph:'[ˈbæləns]',meanings:['균형'],tip:'밸런스 = 균형!',ex:'Keep your balance.',img:'⚖️'},
    {en:'courage',kr:'용기',ph:'[ˈkʌrɪdʒ]',meanings:['용기'],tip:'커리지 = 용기!',ex:'Have courage.',img:'💪'},
    {en:'danger',kr:'위험',ph:'[ˈdeɪndʒər]',meanings:['위험'],tip:'데인저 = 위험!',ex:'There is danger.',img:'⚠️'},
    {en:'effort',kr:'노력',ph:'[ˈefət]',meanings:['노력'],tip:'에포트 = 노력!',ex:'Make an effort.',img:'💯'},
    {en:'famous',kr:'유명한',ph:'[ˈfeɪməs]',meanings:['유명한'],tip:'페이머스 = 유명!',ex:'She is famous.',img:'⭐⭐'},
    {en:'honest',kr:'정직한',ph:'[ˈɒnɪst]',meanings:['정직한'],tip:'어니스트 = 정직!',ex:'Be honest.',img:'🤲'},
    {en:'unique',kr:'독특한',ph:'[juːˈniːk]',meanings:['독특한'],tip:'유니크 = 독특!',ex:'She is unique.',img:'🦄'},
    {en:'talent',kr:'재능',ph:'[ˈtælənt]',meanings:['재능'],tip:'탤런트 = 재능!',ex:'She has talent.',img:'🎯'},
    {en:'wisdom',kr:'지혜',ph:'[ˈwɪzdəm]',meanings:['지혜'],tip:'위즈덤 = 지혜!',ex:'He has wisdom.',img:'🦉'},
  ],
  coco:[
    {en:'ambiguous',kr:'모호한',ph:'[æmˈbɪɡjuəs]',meanings:['모호한','불분명한'],tip:'암비겨? = 모호!',ex:'The message was ambiguous.',img:'🌫️'},
    {en:'analyze',kr:'분석하다',ph:'[ˈænəlaɪz]',meanings:['분석하다'],tip:'애널라이즈 = 분석!',ex:'Analyze the data.',img:'🔬'},
    {en:'benefit',kr:'이익',ph:'[ˈbenɪfɪt]',meanings:['이익','혜택'],tip:'베네핏 = 이익!',ex:'Exercise has benefits.',img:'💰'},
    {en:'concept',kr:'개념',ph:'[ˈkɒnsept]',meanings:['개념'],tip:'컨셉트 = 개념!',ex:'Understand the concept.',img:'💡'},
    {en:'culture',kr:'문화',ph:'[ˈkʌltʃər]',meanings:['문화'],tip:'컬처 = 문화!',ex:'Respect other cultures.',img:'🎭'},
    {en:'develop',kr:'발전하다',ph:'[dɪˈveləp]',meanings:['발전하다'],tip:'디벨롭 = 발전!',ex:'Develop your skills.',img:'📈'},
    {en:'evidence',kr:'증거',ph:'[ˈevɪdəns]',meanings:['증거'],tip:'에비던스 = 증거!',ex:'Show the evidence.',img:'🔍'},
    {en:'diverse',kr:'다양한',ph:'[daɪˈvɜːs]',meanings:['다양한'],tip:'다이버스 = 다양!',ex:'A diverse group.',img:'🌈'},
    {en:'economy',kr:'경제',ph:'[ɪˈkɒnəmi]',meanings:['경제'],tip:'이코노미 = 경제!',ex:'The economy grows.',img:'📊'},
    {en:'efficient',kr:'효율적인',ph:'[ɪˈfɪʃənt]',meanings:['효율적인'],tip:'이피션트 = 효율!',ex:'Work efficiently.',img:'⚡'},
  ],
  shine:[
    {en:'perseverance',kr:'인내',ph:'[pəːrsɪˈvɪərəns]',meanings:['인내','끈기'],tip:'퍼서버티어 = 인내!',ex:'Success requires perseverance.',img:'💪'},
    {en:'eloquent',kr:'유창한',ph:'[ˈeləkwənt]',meanings:['유창한'],tip:'엘로퀀트 = 유창!',ex:'He gave an eloquent speech.',img:'🎤'},
    {en:'resilient',kr:'회복력 있는',ph:'[rɪˈzɪliənt]',meanings:['회복력 있는'],tip:'리질리언트 = 회복!',ex:'Children are resilient.',img:'🌱'},
    {en:'profound',kr:'심오한',ph:'[prəˈfaʊnd]',meanings:['심오한'],tip:'프로파운드 = 심오!',ex:'A profound impact.',img:'🌊'},
    {en:'facilitate',kr:'촉진하다',ph:'[fəˈsɪlɪteɪt]',meanings:['촉진하다'],tip:'퍼실리테이트 = 촉진!',ex:'Facilitate learning.',img:'🚀'},
    {en:'fundamental',kr:'근본적인',ph:'[ˌfʌndəˈmentl]',meanings:['근본적인'],tip:'펀더멘탈 = 근본!',ex:'A fundamental change.',img:'🏗️'},
    {en:'comprehensive',kr:'포괄적인',ph:'[ˌkɒmprɪˈhensɪv]',meanings:['포괄적인'],tip:'컴프리헨시브 = 포괄!',ex:'A comprehensive study.',img:'📚'},
    {en:'controversial',kr:'논란의',ph:'[ˌkɒntrəˈvɜːʃl]',meanings:['논란의'],tip:'컨트로버셜 = 논란!',ex:'A controversial topic.',img:'🔥'},
    {en:'illuminate',kr:'밝히다',ph:'[ɪˈluːmɪneɪt]',meanings:['밝히다'],tip:'일루미네이트 = 밝힘!',ex:'Illuminate the truth.',img:'💡'},
    {en:'enormous',kr:'거대한',ph:'[ɪˈnɔːməs]',meanings:['거대한'],tip:'이노머스 = 거대!',ex:'An enormous task.',img:'🗻'},
  ],
  small:[
    {en:'allocate',kr:'할당하다',ph:'[ˈæləkeɪt]',meanings:['할당하다'],tip:'알로케이트 = 할당!',ex:'Allocate the budget.',img:'📋'},
    {en:'paradigm',kr:'패러다임',ph:'[ˈpærədaɪm]',meanings:['패러다임'],tip:'패러다임!',ex:'A paradigm shift.',img:'🔄'},
    {en:'rhetoric',kr:'수사학',ph:'[ˈretərɪk]',meanings:['수사학'],tip:'레토릭 = 수사!',ex:'Political rhetoric.',img:'🎭'},
    {en:'viable',kr:'실행 가능한',ph:'[ˈvaɪəbl]',meanings:['실행 가능한'],tip:'바이어블 = 실행!',ex:'A viable solution.',img:'💡'},
    {en:'leverage',kr:'영향력',ph:'[ˈliːvərɪdʒ]',meanings:['영향력'],tip:'레버리지 = 영향!',ex:'Use your leverage.',img:'🏋️'},
    {en:'catalyst',kr:'촉매',ph:'[ˈkætəlɪst]',meanings:['촉매'],tip:'캐털리스트 = 촉매!',ex:'A catalyst for change.',img:'⚗️'},
    {en:'coherent',kr:'일관된',ph:'[kəʊˈhɪərənt]',meanings:['일관된'],tip:'코히런트 = 일관!',ex:'A coherent argument.',img:'🧩'},
    {en:'advocate',kr:'지지하다',ph:'[ˈædvəkeɪt]',meanings:['지지하다'],tip:'애드버킷 = 지지!',ex:'Advocate for change.',img:'✊'},
    {en:'constraint',kr:'제약',ph:'[kənˈstreɪnt]',meanings:['제약'],tip:'컨스트레인트 = 제약!',ex:'Budget constraints.',img:'⛓️'},
    {en:'benchmark',kr:'기준점',ph:'[ˈbentʃmɑːk]',meanings:['기준점'],tip:'벤치마크 = 기준!',ex:'Set a benchmark.',img:'📏'},
  ],
  big:[
    {en:'epistemology',kr:'인식론',ph:'[ɪˌpɪstɪˈmɒlədʒi]',meanings:['인식론'],tip:'인식론!',ex:'Epistemology studies knowledge.',img:'🧠'},
    {en:'empirical',kr:'경험적인',ph:'[ɪmˈpɪrɪkl]',meanings:['경험적인'],tip:'임피리컬 = 경험적!',ex:'Empirical evidence.',img:'🔬'},
    {en:'hegemony',kr:'패권',ph:'[hɪˈɡeməni]',meanings:['패권'],tip:'헤게모니 = 패권!',ex:'Cultural hegemony.',img:'👑'},
    {en:'integrity',kr:'진실성',ph:'[ɪnˈteɡrɪti]',meanings:['진실성'],tip:'인테그리티 = 진실!',ex:'Act with integrity.',img:'💎'},
    {en:'meticulous',kr:'꼼꼼한',ph:'[məˈtɪkjələs]',meanings:['꼼꼼한'],tip:'매의 눈으로 티끌!',ex:'Meticulous research.',img:'🔍'},
    {en:'nuance',kr:'미묘한 차이',ph:'[ˈnjuːɑːns]',meanings:['미묘한 차이'],tip:'뉘앙스!',ex:'Appreciate the nuance.',img:'🎨'},
    {en:'pragmatic',kr:'실용적인',ph:'[præɡˈmætɪk]',meanings:['실용적인'],tip:'프래그매틱 = 실용!',ex:'A pragmatic solution.',img:'🔧'},
    {en:'pedagogy',kr:'교육학',ph:'[ˈpedəɡɒdʒi]',meanings:['교육학'],tip:'페다고지 = 교육!',ex:'Modern pedagogy.',img:'🎓'},
    {en:'precedent',kr:'선례',ph:'[ˈpresɪdənt]',meanings:['선례'],tip:'프레시던트 = 선례!',ex:'Set a precedent.',img:'⚖️'},
    {en:'reconcile',kr:'화해시키다',ph:'[ˈrekənsaɪl]',meanings:['화해시키다'],tip:'레컨사일 = 화해!',ex:'Reconcile differences.',img:'🤝'},
  ],
  god:[
    {en:'mellifluous',kr:'감미로운',ph:'[meˈlɪfluəs]',meanings:['감미로운'],tip:'멜리플루어스 = 감미!',ex:'A mellifluous voice.',img:'🎶'},
    {en:'ephemeral',kr:'덧없는',ph:'[ɪˈfem(ə)rəl]',meanings:['덧없는'],tip:'에페머럴 = 덧없음!',ex:'Ephemeral beauty.',img:'🌸'},
    {en:'ubiquitous',kr:'어디에나 있는',ph:'[juːˈbɪkwɪtəs]',meanings:['어디에나 있는'],tip:'유비쿼터스!',ex:'Smartphones are ubiquitous.',img:'🌍'},
    {en:'perspicacious',kr:'통찰력 있는',ph:'[ˌpɜːspɪˈkeɪʃəs]',meanings:['통찰력 있는'],tip:'퍼스피케이셔스!',ex:'A perspicacious observer.',img:'👁️'},
    {en:'ineffable',kr:'형언할 수 없는',ph:'[ɪnˈefəbl]',meanings:['형언할 수 없는'],tip:'이네퍼블!',ex:'An ineffable feeling.',img:'🌌'},
    {en:'equanimity',kr:'평정심',ph:'[ˌiːkwəˈnɪmɪti]',meanings:['평정심'],tip:'에퀴니미티 = 평정!',ex:'Face it with equanimity.',img:'🧘'},
    {en:'fastidious',kr:'까다로운',ph:'[fæˈstɪdiəs]',meanings:['까다로운'],tip:'패스티디어스 = 까다!',ex:'A fastidious critic.',img:'🕵️'},
    {en:'garrulous',kr:'수다스러운',ph:'[ˈɡærələs]',meanings:['수다스러운'],tip:'개룰러스 = 수다!',ex:'A garrulous host.',img:'💬'},
    {en:'trepidation',kr:'공포',ph:'[ˌtrepɪˈdeɪʃn]',meanings:['공포'],tip:'트레피데이션 = 공포!',ex:'With great trepidation.',img:'😱'},
    {en:'zealous',kr:'열렬한',ph:'[ˈzeləs]',meanings:['열렬한'],tip:'젤러스 = 열렬!',ex:'A zealous supporter.',img:'🔥'},
  ],
};
