// ── 단어장 팩 데이터 ──
const WORD_PACKS = [
// ── 여행 ──
{id:'travel_basic',cat:'여행',name:'여행 필수',desc:'공항/호텔/식당/쇼핑 필수 표현',emoji:'✈️',basis:'트립어드바이저 리뷰 + 여행 가이드북 분석',count:1000,words:[
{en:'passport',kr:'여권',ph:'[ˈpɑːspɔːrt]',ex:'Show your passport at the border.',img:'🛂'},
{en:'boarding',kr:'탑승',ph:'[ˈbɔːrdɪŋ]',ex:'Boarding starts at gate 12.',img:'🛫'},
{en:'departure',kr:'출발',ph:'[dɪˈpɑːrtʃər]',ex:'The departure time is 9 AM.',img:'🕘'},
{en:'arrival',kr:'도착',ph:'[əˈraɪvəl]',ex:'Arrival is scheduled for noon.',img:'🛬'},
{en:'customs',kr:'세관',ph:'[ˈkʌstəmz]',ex:'Declare items at customs.',img:'📋'},
{en:'luggage',kr:'짐',ph:'[ˈlʌɡɪdʒ]',ex:'My luggage was lost.',img:'🧳'},
{en:'reservation',kr:'예약',ph:'[ˌrezərˈveɪʃən]',ex:'I have a reservation.',img:'📅'},
{en:'check-in',kr:'체크인',ph:'[ˈtʃek ɪn]',ex:'Check-in is at 3 PM.',img:'🏨'},
{en:'itinerary',kr:'여행 일정',ph:'[aɪˈtɪnəreri]',ex:'Here is my itinerary.',img:'📝'},
{en:'currency',kr:'통화',ph:'[ˈkɜːrənsi]',ex:'What is the local currency?',img:'💱'},
{en:'exchange',kr:'환전',ph:'[ɪksˈtʃeɪndʒ]',ex:'Where can I exchange money?',img:'💰'},
{en:'accommodation',kr:'숙박',ph:'[əˌkɒməˈdeɪʃən]',ex:'Book accommodation in advance.',img:'🏠'},
{en:'sightseeing',kr:'관광',ph:'[ˈsaɪtsiːɪŋ]',ex:'We went sightseeing all day.',img:'🗺️'},
{en:'souvenir',kr:'기념품',ph:'[ˌsuːvəˈnɪr]',ex:'I bought a souvenir.',img:'🎁'},
{en:'guidebook',kr:'여행 가이드',ph:'[ˈɡaɪdbʊk]',ex:'The guidebook is very helpful.',img:'📖'},
{en:'visa',kr:'비자',ph:'[ˈviːzə]',ex:'I need a visa for this country.',img:'📄'},
{en:'transit',kr:'환승',ph:'[ˈtrænsɪt]',ex:'I have a transit in Tokyo.',img:'🔄'},
{en:'turbulence',kr:'난기류',ph:'[ˈtɜːrbjələns]',ex:'We hit turbulence.',img:'✈️'},
{en:'jetlag',kr:'시차증',ph:'[ˈdʒetlæɡ]',ex:'I have bad jetlag.',img:'😴'},
{en:'hostel',kr:'호스텔',ph:'[ˈhɒstəl]',ex:'I stayed at a hostel.',img:'🏠'},
]},

// ── 비즈니스 ──
{id:'business_basic',cat:'비즈니스',name:'비즈니스 필수',desc:'이메일/회의/계약/협상 핵심',emoji:'💼',basis:'Oxford Business English + LinkedIn 분석',count:1000,words:[
{en:'agenda',kr:'안건',ph:'[əˈdʒendə]',ex:'What is on the agenda today?',img:'📋'},
{en:'deadline',kr:'마감일',ph:'[ˈdedlaɪn]',ex:'The deadline is Friday.',img:'⏰'},
{en:'proposal',kr:'제안서',ph:'[prəˈpoʊzəl]',ex:'Submit your proposal by Monday.',img:'📄'},
{en:'negotiate',kr:'협상하다',ph:'[nɪˈɡoʊʃieɪt]',ex:'We need to negotiate the terms.',img:'🤝'},
{en:'stakeholder',kr:'이해관계자',ph:'[ˈsteɪkhoʊldər]',ex:'Involve all stakeholders.',img:'👥'},
{en:'revenue',kr:'수익',ph:'[ˈrevənjuː]',ex:'Revenue increased this quarter.',img:'📈'},
{en:'budget',kr:'예산',ph:'[ˈbʌdʒɪt]',ex:'We exceeded the budget.',img:'💵'},
{en:'invoice',kr:'청구서',ph:'[ˈɪnvɔɪs]',ex:'Please send the invoice.',img:'📃'},
{en:'contract',kr:'계약',ph:'[ˈkɒntrækt]',ex:'Sign the contract today.',img:'✍️'},
{en:'merger',kr:'합병',ph:'[ˈmɜːrdʒər]',ex:'The merger was approved.',img:'🏢'},
{en:'acquisition',kr:'인수',ph:'[ˌækwɪˈzɪʃən]',ex:'The acquisition cost billions.',img:'💰'},
{en:'quarterly',kr:'분기별',ph:'[ˈkwɔːrtərli]',ex:'Quarterly results are strong.',img:'📊'},
{en:'benchmark',kr:'기준점',ph:'[ˈbentʃmɑːrk]',ex:'Set a benchmark for success.',img:'📏'},
{en:'outsource',kr:'외주하다',ph:'[ˈaʊtsɔːrs]',ex:'We outsource IT support.',img:'🔄'},
{en:'compliance',kr:'규정 준수',ph:'[kəmˈplaɪəns]',ex:'Ensure compliance with laws.',img:'⚖️'},
{en:'liability',kr:'책임',ph:'[ˌlaɪəˈbɪlɪti]',ex:'The company has no liability.',img:'🛡️'},
{en:'portfolio',kr:'포트폴리오',ph:'[pɔːrtˈfoʊlioʊ]',ex:'Review your investment portfolio.',img:'📁'},
{en:'scalable',kr:'확장 가능한',ph:'[ˈskeɪləbəl]',ex:'The model is scalable.',img:'📐'},
{en:'disruption',kr:'혼란',ph:'[dɪsˈrʌpʃən]',ex:'Digital disruption is happening.',img:'⚡'},
{en:'synergy',kr:'시너지',ph:'[ˈsɪnərdʒi]',ex:'Create synergy between teams.',img:'🔗'},
]},

// ── 학업 수능 ──
{id:'suneung',cat:'학업',name:'수능 기출 1000',desc:'수능 15개년 기출 핵심 어휘',emoji:'📝',basis:'한국교육과정평가원 수능 15개년 기출 분석',count:1000,words:[
{en:'ambivalent',kr:'양면적인',ph:'[æmˈbɪvələnt]',ex:'She felt ambivalent about leaving.',img:'🔄'},
{en:'predominant',kr:'지배적인',ph:'[prɪˈdɒmɪnənt]',ex:'One view is predominant.',img:'👑'},
{en:'instigate',kr:'선동하다',ph:'[ˈɪnstɪɡeɪt]',ex:'He tried to instigate conflict.',img:'🔥'},
{en:'apprehensive',kr:'불안한',ph:'[ˌæprɪˈhensɪv]',ex:'She was apprehensive about the exam.',img:'😰'},
{en:'benevolent',kr:'자비로운',ph:'[bəˈnevələnt]',ex:'He was a benevolent leader.',img:'🤲'},
{en:'diminish',kr:'줄어들다',ph:'[dɪˈmɪnɪʃ]',ex:'The pain began to diminish.',img:'📉'},
{en:'exacerbate',kr:'악화시키다',ph:'[ɪɡˈzæsərbeɪt]',ex:'Stress can exacerbate illness.',img:'⬆️'},
{en:'susceptible',kr:'취약한',ph:'[səˈseptɪbl]',ex:'Children are susceptible to colds.',img:'🤒'},
{en:'inevitably',kr:'필연적으로',ph:'[ɪnˈevɪtəbli]',ex:'Change inevitably occurs.',img:'➡️'},
{en:'counterpart',kr:'상대방',ph:'[ˈkaʊntərpɑːrt]',ex:'Meet your counterpart.',img:'🪞'},
{en:'imperative',kr:'필수적인',ph:'[ɪmˈperətɪv]',ex:'It is imperative to act now.',img:'❗'},
{en:'subsequent',kr:'그 다음의',ph:'[ˈsʌbsɪkwənt]',ex:'In subsequent years it grew.',img:'📅'},
{en:'discrepancy',kr:'불일치',ph:'[dɪˈskrepənsi]',ex:'There is a discrepancy here.',img:'❓'},
{en:'arbitrary',kr:'임의의',ph:'[ˈɑːrbɪtreri]',ex:'The rule seems arbitrary.',img:'🎲'},
{en:'compensate',kr:'보상하다',ph:'[ˈkɒmpənseɪt]',ex:'He was compensated for losses.',img:'💰'},
{en:'detrimental',kr:'해로운',ph:'[ˌdetrɪˈmentəl]',ex:'Stress is detrimental to health.',img:'⚠️'},
{en:'indigenous',kr:'토착의',ph:'[ɪnˈdɪdʒɪnəs]',ex:'Indigenous peoples have rights.',img:'🌍'},
{en:'simultaneously',kr:'동시에',ph:'[ˌsɪməlˈteɪniəsli]',ex:'Two events occurred simultaneously.',img:'⚡'},
{en:'deteriorate',kr:'악화되다',ph:'[dɪˈtɪəriəreɪt]',ex:'Health can deteriorate quickly.',img:'📉'},
{en:'perpetuate',kr:'영속시키다',ph:'[pərˈpetʃueɪt]',ex:'Don\'t perpetuate stereotypes.',img:'🔄'},
]},

// ── 토익 ──
{id:'toeic',cat:'학업',name:'토익 핵심 1000',desc:'ETS 공식 빈출 어휘 완전 분석',emoji:'🏢',basis:'ETS 공식 TOEIC 빈출 어휘 + 기출 분석',count:1000,words:[
{en:'allocate',kr:'할당하다',ph:'[ˈæləkeɪt]',ex:'Allocate resources carefully.',img:'📊'},
{en:'reimburse',kr:'환급하다',ph:'[ˌriːɪmˈbɜːrs]',ex:'Expenses will be reimbursed.',img:'💵'},
{en:'premises',kr:'건물/구내',ph:'[ˈpremɪsɪz]',ex:'Stay on the premises.',img:'🏢'},
{en:'merchandise',kr:'상품',ph:'[ˈmɜːrtʃəndaɪz]',ex:'The merchandise is on sale.',img:'🛍️'},
{en:'inventory',kr:'재고',ph:'[ˈɪnvəntɔːri]',ex:'Check the inventory levels.',img:'📦'},
{en:'expedite',kr:'신속히 처리하다',ph:'[ˈekspədaɪt]',ex:'Please expedite this order.',img:'🚀'},
{en:'collaborate',kr:'협력하다',ph:'[kəˈlæbəreɪt]',ex:'Teams must collaborate.',img:'🤝'},
{en:'proficient',kr:'능숙한',ph:'[prəˈfɪʃənt]',ex:'She is proficient in Excel.',img:'💻'},
{en:'adhere',kr:'준수하다',ph:'[ədˈhɪər]',ex:'Adhere to company policy.',img:'📋'},
{en:'authorize',kr:'승인하다',ph:'[ˈɔːθəraɪz]',ex:'The manager authorized it.',img:'✅'},
{en:'consecutive',kr:'연속적인',ph:'[kənˈsekjətɪv]',ex:'Three consecutive days.',img:'📅'},
{en:'provisional',kr:'임시의',ph:'[prəˈvɪʒənəl]',ex:'A provisional agreement.',img:'📝'},
{en:'coordinates',kr:'조율하다',ph:'[koʊˈɔːrdɪneɪts]',ex:'She coordinates the schedule.',img:'🗓️'},
{en:'surplus',kr:'잉여분',ph:'[ˈsɜːrpləs]',ex:'We have a budget surplus.',img:'➕'},
{en:'subsidiary',kr:'자회사',ph:'[səbˈsɪdieri]',ex:'It is our subsidiary.',img:'🏢'},
{en:'fluctuate',kr:'변동하다',ph:'[ˈflʌktʃueɪt]',ex:'Prices fluctuate daily.',img:'📊'},
{en:'stringent',kr:'엄격한',ph:'[ˈstrɪndʒənt]',ex:'Stringent rules apply.',img:'⚖️'},
{en:'tenure',kr:'재임 기간',ph:'[ˈtenjər]',ex:'During her tenure.',img:'📅'},
{en:'procurement',kr:'조달',ph:'[prəˈkjʊərmənt]',ex:'Handle procurement.',img:'🛒'},
{en:'fiscal',kr:'회계의',ph:'[ˈfɪskəl]',ex:'The fiscal year ends in March.',img:'📊'},
]},

// ── 토플 ──
{id:'toefl',cat:'학업',name:'토플 학술 1000',desc:'ETS TOEFL + AWL 학술 어휘',emoji:'🎓',basis:'ETS TOEFL 공식 어휘 + Victoria대학 AWL(Academic Word List)',count:1000,words:[
{en:'hypothesis',kr:'가설',ph:'[haɪˈpɒθəsɪs]',ex:'Test the hypothesis.',img:'🔬'},
{en:'methodology',kr:'방법론',ph:'[ˌmeθəˈdɒlədʒi]',ex:'Explain your methodology.',img:'📐'},
{en:'paradigm',kr:'패러다임',ph:'[ˈpærədaɪm]',ex:'A paradigm shift occurred.',img:'🔄'},
{en:'empirical',kr:'경험적인',ph:'[ɪmˈpɪrɪkəl]',ex:'Empirical evidence is needed.',img:'🔍'},
{en:'phenomenon',kr:'현상',ph:'[fɪˈnɒmɪnən]',ex:'A natural phenomenon.',img:'🌪️'},
{en:'inference',kr:'추론',ph:'[ˈɪnfərəns]',ex:'Draw a logical inference.',img:'🧩'},
{en:'critique',kr:'비평',ph:'[krɪˈtiːk]',ex:'Write a literary critique.',img:'✍️'},
{en:'subsidy',kr:'보조금',ph:'[ˈsʌbsɪdi]',ex:'The government gave a subsidy.',img:'💰'},
{en:'cognitive',kr:'인지적인',ph:'[ˈkɒɡnɪtɪv]',ex:'Cognitive development is key.',img:'🧠'},
{en:'indigenous',kr:'토착의',ph:'[ɪnˈdɪdʒɪnəs]',ex:'Indigenous languages are dying.',img:'🌍'},
{en:'correlation',kr:'상관관계',ph:'[ˌkɒrəˈleɪʃən]',ex:'There is a strong correlation.',img:'📊'},
{en:'constraint',kr:'제약',ph:'[kənˈstreɪnt]',ex:'Budget constraints exist.',img:'⛓️'},
{en:'implication',kr:'함의',ph:'[ˌɪmplɪˈkeɪʃən]',ex:'Consider the implications.',img:'💭'},
{en:'excerpt',kr:'발췌',ph:'[ˈeksɜːrpt]',ex:'Read this excerpt carefully.',img:'📖'},
{en:'comprise',kr:'구성되다',ph:'[kəmˈpraɪz]',ex:'The team comprises five people.',img:'👥'},
{en:'contention',kr:'주장',ph:'[kənˈtenʃən]',ex:'My contention is this.',img:'🗣️'},
{en:'alleviate',kr:'완화하다',ph:'[əˈliːvieɪt]',ex:'Medicine alleviates pain.',img:'💊'},
{en:'proliferate',kr:'급증하다',ph:'[prəˈlɪfəreɪt]',ex:'Social media proliferates.',img:'📈'},
{en:'exemplify',kr:'예시하다',ph:'[ɪɡˈzemplɪfaɪ]',ex:'This exemplifies the point.',img:'💡'},
{en:'subordinate',kr:'하위의',ph:'[səˈbɔːrdɪnɪt]',ex:'A subordinate clause.',img:'📝'},
]},

// ── 영화/드라마 ──
{id:'media_drama',cat:'미디어',name:'영화/드라마 1000',desc:'넷플릭스 자막 고빈출 어휘',emoji:'🎬',basis:'넷플릭스/HBO 자막 빈도 분석 + 영어 드라마 스크립트',count:1000,words:[
{en:'hesitate',kr:'망설이다',ph:'[ˈhezɪteɪt]',ex:'Don\'t hesitate to call me.',img:'🤔'},
{en:'confront',kr:'맞서다',ph:'[kənˈfrʌnt]',ex:'Confront your fears.',img:'😤'},
{en:'betray',kr:'배신하다',ph:'[bɪˈtreɪ]',ex:'She betrayed his trust.',img:'💔'},
{en:'obsessed',kr:'집착하는',ph:'[əbˈsest]',ex:'He was obsessed with her.',img:'😵'},
{en:'desperate',kr:'절박한',ph:'[ˈdespərɪt]',ex:'A desperate situation.',img:'😰'},
{en:'confrontation',kr:'대결',ph:'[ˌkɒnfrʌnˈteɪʃən]',ex:'A final confrontation.',img:'⚔️'},
{en:'suspicion',kr:'의심',ph:'[səˈspɪʃən]',ex:'She had her suspicions.',img:'🔍'},
{en:'manipulate',kr:'조종하다',ph:'[məˈnɪpjʊleɪt]',ex:'He manipulated everyone.',img:'🎭'},
{en:'revelation',kr:'폭로',ph:'[ˌrevəˈleɪʃən]',ex:'A shocking revelation.',img:'😱'},
{en:'redemption',kr:'구원',ph:'[rɪˈdempʃən]',ex:'He sought redemption.',img:'✨'},
{en:'villain',kr:'악당',ph:'[ˈvɪlən]',ex:'The villain escaped.',img:'😈'},
{en:'cliffhanger',kr:'절박한 상황',ph:'[ˈklɪfhæŋər]',ex:'The episode ended on a cliffhanger.',img:'😮'},
{en:'plot twist',kr:'반전',ph:'[plɒt twɪst]',ex:'There was a plot twist.',img:'🌀'},
{en:'sequel',kr:'속편',ph:'[ˈsiːkwəl]',ex:'The sequel is better.',img:'🎬'},
{en:'protagonist',kr:'주인공',ph:'[prəˈtæɡənɪst]',ex:'The protagonist is brave.',img:'🦸'},
{en:'antagonist',kr:'적대자',ph:'[ænˈtæɡənɪst]',ex:'The antagonist is evil.',img:'🦹'},
{en:'flashback',kr:'회상 장면',ph:'[ˈflæʃbæk]',ex:'A dramatic flashback.',img:'⏪'},
{en:'alibi',kr:'알리바이',ph:'[ˈælɪbaɪ]',ex:'He had an alibi.',img:'🕵️'},
{en:'vendetta',kr:'복수',ph:'[venˈdetə]',ex:'A personal vendetta.',img:'⚔️'},
{en:'foreshadow',kr:'암시하다',ph:'[fɔːrˈʃædoʊ]',ex:'This scene foreshadows.',img:'🌑'},
]},

// ── 취미/문화 ──
{id:'food_cooking',cat:'취미문화',name:'요리/베이킹 1000',desc:'레시피/식재료/조리법 어휘',emoji:'🍳',basis:'MasterChef + BBC Good Food + 요리 레시피 사이트 분석',count:1000,words:[
{en:'simmer',kr:'뭉근히 끓이다',ph:'[ˈsɪmər]',ex:'Simmer for 20 minutes.',img:'🍲'},
{en:'whisk',kr:'거품기로 젓다',ph:'[wɪsk]',ex:'Whisk the eggs.',img:'🥚'},
{en:'marinate',kr:'재우다',ph:'[ˈmærɪneɪt]',ex:'Marinate overnight.',img:'🥩'},
{en:'sauté',kr:'볶다',ph:'[soʊˈteɪ]',ex:'Sauté the garlic.',img:'🧄'},
{en:'drizzle',kr:'살짝 뿌리다',ph:'[ˈdrɪzəl]',ex:'Drizzle with olive oil.',img:'🫒'},
{en:'garnish',kr:'장식하다',ph:'[ˈɡɑːrnɪʃ]',ex:'Garnish with parsley.',img:'🌿'},
{en:'knead',kr:'반죽하다',ph:'[niːd]',ex:'Knead the dough.',img:'🍞'},
{en:'caramelize',kr:'캐러멜화하다',ph:'[ˈkærəməlaɪz]',ex:'Caramelize the onions.',img:'🧅'},
{en:'mince',kr:'잘게 다지다',ph:'[mɪns]',ex:'Mince the garlic finely.',img:'🔪'},
{en:'blanch',kr:'데치다',ph:'[blæntʃ]',ex:'Blanch the vegetables.',img:'🥦'},
{en:'zest',kr:'겉껍질',ph:'[zest]',ex:'Add lemon zest.',img:'🍋'},
{en:'infuse',kr:'우려내다',ph:'[ɪnˈfjuːz]',ex:'Infuse the tea for 5 minutes.',img:'🍵'},
{en:'consistency',kr:'농도',ph:'[kənˈsɪstənsi]',ex:'The right consistency.',img:'🥄'},
{en:'seasoning',kr:'양념',ph:'[ˈsiːzənɪŋ]',ex:'Adjust the seasoning.',img:'🧂'},
{en:'appetizer',kr:'전채 요리',ph:'[ˈæpɪtaɪzər]',ex:'Start with an appetizer.',img:'🥗'},
{en:'entrée',kr:'주요리',ph:'[ˈɒntreɪ]',ex:'The entrée was delicious.',img:'🍽️'},
{en:'al dente',kr:'알덴테',ph:'[æl ˈdenti]',ex:'Cook pasta al dente.',img:'🍝'},
{en:'gluten',kr:'글루텐',ph:'[ˈɡluːtən]',ex:'Gluten-free options available.',img:'🌾'},
{en:'ferment',kr:'발효하다',ph:'[ˈfɜːrment]',ex:'Ferment for two weeks.',img:'🧫'},
{en:'emulsify',kr:'유화하다',ph:'[ɪˈmʌlsɪfaɪ]',ex:'Emulsify oil and vinegar.',img:'🫙'},
]},

// ── 건강/피트니스 ──
{id:'health_fitness',cat:'취미문화',name:'건강/피트니스 1000',desc:'운동/헬스/영양 핵심 어휘',emoji:'💪',basis:'WebMD + Men\'s Health + NHS 건강 정보 분석',count:1000,words:[
{en:'metabolism',kr:'신진대사',ph:'[məˈtæbəlɪzəm]',ex:'Boost your metabolism.',img:'🔥'},
{en:'cardiovascular',kr:'심혈관의',ph:'[ˌkɑːrdioʊˈvæskjʊlər]',ex:'Cardiovascular exercise is key.',img:'❤️'},
{en:'flexibility',kr:'유연성',ph:'[ˌfleksɪˈbɪlɪti]',ex:'Improve your flexibility.',img:'🧘'},
{en:'endurance',kr:'지구력',ph:'[ɪnˈdjʊərəns]',ex:'Build your endurance.',img:'🏃'},
{en:'nutrition',kr:'영양',ph:'[njuːˈtrɪʃən]',ex:'Good nutrition matters.',img:'🥗'},
{en:'hydration',kr:'수분 보충',ph:'[haɪˈdreɪʃən]',ex:'Stay hydrated.',img:'💧'},
{en:'immune',kr:'면역의',ph:'[ɪˈmjuːn]',ex:'Boost your immune system.',img:'🛡️'},
{en:'calorie',kr:'칼로리',ph:'[ˈkæləri]',ex:'Count your calories.',img:'🔢'},
{en:'protein',kr:'단백질',ph:'[ˈproʊtiːn]',ex:'Eat enough protein.',img:'🥩'},
{en:'interval',kr:'인터벌',ph:'[ˈɪntərvəl]',ex:'Interval training burns fat.',img:'⏱️'},
{en:'posture',kr:'자세',ph:'[ˈpɒstʃər]',ex:'Correct your posture.',img:'🧍'},
{en:'repetition',kr:'반복',ph:'[ˌrepɪˈtɪʃən]',ex:'Three sets of 12 repetitions.',img:'🔄'},
{en:'inflammation',kr:'염증',ph:'[ˌɪnfləˈmeɪʃən]',ex:'Reduce inflammation.',img:'🔴'},
{en:'supplement',kr:'보충제',ph:'[ˈsʌplɪmənt]',ex:'Take vitamin supplements.',img:'💊'},
{en:'aerobic',kr:'유산소의',ph:'[eəˈroʊbɪk]',ex:'Aerobic exercise is healthy.',img:'🚴'},
{en:'anaerobic',kr:'무산소의',ph:'[ˌæneəˈroʊbɪk]',ex:'Anaerobic training builds muscle.',img:'🏋️'},
{en:'cholesterol',kr:'콜레스테롤',ph:'[kəˈlestərɒl]',ex:'Lower your cholesterol.',img:'🩺'},
{en:'fiber',kr:'섬유질',ph:'[ˈfaɪbər]',ex:'Eat more dietary fiber.',img:'🥦'},
{en:'wellness',kr:'건강한 상태',ph:'[ˈwelnəs]',ex:'Focus on overall wellness.',img:'✨'},
{en:'rehabilitation',kr:'재활',ph:'[ˌriːhəˌbɪlɪˈteɪʃən]',ex:'Physical rehabilitation takes time.',img:'🏥'},
]},

// ── 패션/뷰티 ──
{id:'fashion_beauty',cat:'취미문화',name:'패션/뷰티 1000',desc:'의류/뷰티/스킨케어 핵심 어휘',emoji:'👗',basis:'Vogue + InStyle + Allure 잡지 어휘 분석',count:1000,words:[
{en:'aesthetic',kr:'미학적인',ph:'[esˈθetɪk]',ex:'The aesthetic is minimal.',img:'✨'},
{en:'silhouette',kr:'실루엣',ph:'[ˌsɪluˈet]',ex:'A flattering silhouette.',img:'👗'},
{en:'accessory',kr:'액세서리',ph:'[əkˈsesəri]',ex:'Add a bold accessory.',img:'💍'},
{en:'moisturizer',kr:'보습제',ph:'[ˈmɔɪstʃəraɪzər]',ex:'Apply moisturizer daily.',img:'🧴'},
{en:'exfoliate',kr:'각질 제거하다',ph:'[eksˈfoʊlieɪt]',ex:'Exfoliate twice a week.',img:'✨'},
{en:'complexion',kr:'안색',ph:'[kəmˈplekʃən]',ex:'She has a clear complexion.',img:'🌟'},
{en:'wardrobe',kr:'옷장',ph:'[ˈwɔːrdroʊb]',ex:'Update your wardrobe.',img:'👔'},
{en:'tailored',kr:'맞춤의',ph:'[ˈteɪlərd]',ex:'A tailored suit.',img:'🪡'},
{en:'vintage',kr:'빈티지',ph:'[ˈvɪntɪdʒ]',ex:'A vintage dress.',img:'👒'},
{en:'trendy',kr:'유행하는',ph:'[ˈtrendi]',ex:'A trendy outfit.',img:'💅'},
{en:'palette',kr:'팔레트',ph:'[ˈpælɪt]',ex:'A neutral color palette.',img:'🎨'},
{en:'serum',kr:'세럼',ph:'[ˈsɪərəm]',ex:'Apply vitamin C serum.',img:'💧'},
{en:'collagen',kr:'콜라겐',ph:'[ˈkɒlədʒən]',ex:'Collagen keeps skin firm.',img:'✨'},
{en:'contour',kr:'윤곽',ph:'[ˈkɒntʊər]',ex:'Contour your cheekbones.',img:'💄'},
{en:'minimalist',kr:'미니멀한',ph:'[ˈmɪnɪməlɪst]',ex:'A minimalist style.',img:'⬜'},
{en:'haute couture',kr:'고급 맞춤복',ph:'[ˌoʊt kuːˈtʊər]',ex:'Wearing haute couture.',img:'👑'},
{en:'sustainable',kr:'지속 가능한',ph:'[səˈsteɪnəbəl]',ex:'Sustainable fashion brands.',img:'♻️'},
{en:'pigmentation',kr:'색소침착',ph:'[ˌpɪɡmənˈteɪʃən]',ex:'Reduce pigmentation.',img:'🔬'},
{en:'SPF',kr:'자외선 차단지수',ph:'[es piː ef]',ex:'Use SPF 50 sunscreen.',img:'☀️'},
{en:'hypoallergenic',kr:'저자극성',ph:'[ˌhaɪpoʊˌælərˈdʒenɪk]',ex:'Use hypoallergenic products.',img:'🌿'},
]},

// ── IT/개발 ──
{id:'it_tech',cat:'비즈니스',name:'IT/개발 1000',desc:'프로그래밍/소프트웨어 개발 필수 어휘',emoji:'💻',basis:'Stack Overflow + GitHub + 기술 문서 어휘 분석',count:1000,words:[
{en:'algorithm',kr:'알고리즘',ph:'[ˈælɡərɪðəm]',ex:'Optimize the algorithm.',img:'🔄'},
{en:'debugging',kr:'디버깅',ph:'[diːˈbʌɡɪŋ]',ex:'Debugging takes time.',img:'🐛'},
{en:'repository',kr:'저장소',ph:'[rɪˈpɒzɪtɔːri]',ex:'Clone the repository.',img:'📁'},
{en:'deployment',kr:'배포',ph:'[dɪˈplɔɪmənt]',ex:'The deployment failed.',img:'🚀'},
{en:'iteration',kr:'반복',ph:'[ˌɪtəˈreɪʃən]',ex:'Next iteration of the product.',img:'🔄'},
{en:'scalability',kr:'확장성',ph:'[ˌskeɪləˈbɪlɪti]',ex:'Ensure scalability.',img:'📈'},
{en:'latency',kr:'지연 시간',ph:'[ˈleɪtənsi]',ex:'Reduce network latency.',img:'⏱️'},
{en:'encryption',kr:'암호화',ph:'[ɪnˈkrɪpʃən]',ex:'Data encryption is vital.',img:'🔐'},
{en:'authentication',kr:'인증',ph:'[ɔːˌθentɪˈkeɪʃən]',ex:'Two-factor authentication.',img:'🔑'},
{en:'bandwidth',kr:'대역폭',ph:'[ˈbændwɪdθ]',ex:'Limited bandwidth.',img:'📡'},
{en:'cache',kr:'캐시',ph:'[kæʃ]',ex:'Clear your cache.',img:'💾'},
{en:'middleware',kr:'미들웨어',ph:'[ˈmɪdlweər]',ex:'Use middleware.',img:'🔗'},
{en:'refactor',kr:'리팩토링하다',ph:'[riːˈfæktər]',ex:'Refactor the code.',img:'🔧'},
{en:'dependency',kr:'의존성',ph:'[dɪˈpendənsi]',ex:'Resolve dependencies.',img:'📦'},
{en:'prototype',kr:'프로토타입',ph:'[ˈproʊtətaɪp]',ex:'Build a prototype.',img:'🏗️'},
{en:'agile',kr:'애자일',ph:'[ˈædʒaɪl]',ex:'We use agile methodology.',img:'🏃'},
{en:'sprint',kr:'스프린트',ph:'[sprɪnt]',ex:'Two-week sprint.',img:'⚡'},
{en:'syntax',kr:'문법',ph:'[ˈsɪntæks]',ex:'Check the syntax.',img:'📝'},
{en:'recursive',kr:'재귀적인',ph:'[rɪˈkɜːrsɪv]',ex:'A recursive function.',img:'🔄'},
{en:'asynchronous',kr:'비동기의',ph:'[eɪˈsɪŋkrənəs]',ex:'Asynchronous programming.',img:'⚡'},
]},

// ── 뉴스 영어 ──
{id:'news_english',cat:'미디어',name:'뉴스 영어 1000',desc:'CNN/BBC/NYT 고빈출 시사 어휘',emoji:'📰',basis:'CNN/BBC/NYT/Washington Post 뉴스 어휘 빈도 분석',count:1000,words:[
{en:'sanction',kr:'제재',ph:'[ˈsæŋkʃən]',ex:'Economic sanctions were imposed.',img:'⚖️'},
{en:'geopolitical',kr:'지정학적인',ph:'[ˌdʒiːoʊpəˈlɪtɪkəl]',ex:'Geopolitical tensions rise.',img:'🌍'},
{en:'diplomacy',kr:'외교',ph:'[dɪˈploʊməsi]',ex:'Diplomacy is needed.',img:'🕊️'},
{en:'inflation',kr:'인플레이션',ph:'[ɪnˈfleɪʃən]',ex:'Inflation hit a record high.',img:'📈'},
{en:'recession',kr:'경기 침체',ph:'[rɪˈseʃən]',ex:'A global recession looms.',img:'📉'},
{en:'referendum',kr:'국민투표',ph:'[ˌrefəˈrendəm]',ex:'A referendum was held.',img:'🗳️'},
{en:'legislation',kr:'법률',ph:'[ˌledʒɪsˈleɪʃən]',ex:'New legislation passed.',img:'📜'},
{en:'coalition',kr:'연립',ph:'[ˌkoʊəˈlɪʃən]',ex:'A coalition government.',img:'🤝'},
{en:'humanitarian',kr:'인도주의적',ph:'[hjuːˌmænɪˈteəriən]',ex:'Humanitarian aid needed.',img:'❤️'},
{en:'sovereignty',kr:'주권',ph:'[ˈsɒvrənti]',ex:'National sovereignty.',img:'🏳️'},
{en:'incumbent',kr:'현직의',ph:'[ɪnˈkʌmbənt]',ex:'The incumbent president.',img:'🏛️'},
{en:'controversy',kr:'논란',ph:'[ˈkɒntrəvɜːrsi]',ex:'The decision caused controversy.',img:'🔥'},
{en:'allegation',kr:'혐의',ph:'[ˌæləˈɡeɪʃən]',ex:'Serious allegations emerged.',img:'⚠️'},
{en:'transparency',kr:'투명성',ph:'[trænsˈpærənsi]',ex:'Demand transparency.',img:'🔍'},
{en:'bureaucracy',kr:'관료주의',ph:'[bjʊˈrɒkrəsi]',ex:'Cut through bureaucracy.',img:'🏛️'},
{en:'bilateral',kr:'양자간의',ph:'[ˌbaɪˈlætərəl]',ex:'A bilateral agreement.',img:'🤝'},
{en:'austerity',kr:'긴축',ph:'[ɒˈsterɪti]',ex:'Austerity measures.',img:'✂️'},
{en:'populism',kr:'포퓰리즘',ph:'[ˈpɒpjʊlɪzəm]',ex:'Rise of populism.',img:'👥'},
{en:'whistleblower',kr:'내부고발자',ph:'[ˈwɪsəlbloʊər]',ex:'The whistleblower spoke out.',img:'🔔'},
{en:'polarization',kr:'양극화',ph:'[ˌpoʊlərɪˈzeɪʃən]',ex:'Social polarization increases.',img:'↔️'},
]},

// ── 심리학/자기계발 ──
{id:'psychology',cat:'취미문화',name:'심리학/자기계발 1000',desc:'심리학 기초 + 자기계발 핵심 어휘',emoji:'🧠',basis:'Psychology Today + 자기계발 베스트셀러 어휘 분석',count:1000,words:[
{en:'cognitive',kr:'인지적인',ph:'[ˈkɒɡnɪtɪv]',ex:'Cognitive bias affects decisions.',img:'🧠'},
{en:'resilience',kr:'회복력',ph:'[rɪˈzɪliəns]',ex:'Build your resilience.',img:'💪'},
{en:'mindfulness',kr:'마음챙김',ph:'[ˈmaɪndfʊlnəs]',ex:'Practice mindfulness daily.',img:'🧘'},
{en:'procrastinate',kr:'미루다',ph:'[prəˈkræstɪneɪt]',ex:'Stop procrastinating.',img:'⏰'},
{en:'empathy',kr:'공감',ph:'[ˈempəθi]',ex:'Show empathy to others.',img:'❤️'},
{en:'burnout',kr:'번아웃',ph:'[ˈbɜːrnaʊt]',ex:'Avoid burnout.',img:'🔥'},
{en:'introspection',kr:'자기성찰',ph:'[ˌɪntrəˈspekʃən]',ex:'Introspection helps growth.',img:'🪞'},
{en:'gratitude',kr:'감사',ph:'[ˈɡrætɪtjuːd]',ex:'Practice gratitude.',img:'🙏'},
{en:'subconscious',kr:'잠재의식',ph:'[ˌsʌbˈkɒnʃəs]',ex:'The subconscious mind.',img:'💭'},
{en:'validation',kr:'인정',ph:'[ˌvælɪˈdeɪʃən]',ex:'Seek validation from within.',img:'✅'},
{en:'attachment',kr:'애착',ph:'[əˈtætʃmənt]',ex:'Secure attachment style.',img:'🔗'},
{en:'trigger',kr:'유발 요인',ph:'[ˈtrɪɡər]',ex:'Identify your triggers.',img:'⚡'},
{en:'affirmation',kr:'확언',ph:'[ˌæfɜːrˈmeɪʃən]',ex:'Daily affirmations help.',img:'✨'},
{en:'boundaries',kr:'경계',ph:'[ˈbaʊndriz]',ex:'Set healthy boundaries.',img:'🚧'},
{en:'vulnerability',kr:'취약성',ph:'[ˌvʌlnərəˈbɪlɪti]',ex:'Embrace vulnerability.',img:'💙'},
{en:'accountability',kr:'책임감',ph:'[əˌkaʊntəˈbɪlɪti]',ex:'Take accountability.',img:'🎯'},
{en:'catastrophize',kr:'최악을 상상하다',ph:'[kəˈtæstrəfaɪz]',ex:'Don\'t catastrophize.',img:'😰'},
{en:'stoic',kr:'금욕주의적인',ph:'[ˈstoʊɪk]',ex:'A stoic approach to pain.',img:'🗿'},
{en:'neuroplasticity',kr:'신경가소성',ph:'[ˌnjʊərəplæˈstɪsɪti]',ex:'Neuroplasticity allows change.',img:'🧠'},
{en:'self-efficacy',kr:'자기효능감',ph:'[self ˈefɪkəsi]',ex:'Build self-efficacy.',img:'💪'},
]},

// ── 환경/ESG ──
{id:'environment',cat:'학업',name:'환경/ESG 1000',desc:'기후변화/탄소중립/환경 핵심 어휘',emoji:'🌍',basis:'UN IPCC 보고서 + BBC Climate + ESG 보고서 어휘 분석',count:1000,words:[
{en:'sustainability',kr:'지속가능성',ph:'[səˌsteɪnəˈbɪlɪti]',ex:'Focus on sustainability.',img:'♻️'},
{en:'carbon footprint',kr:'탄소발자국',ph:'[ˈkɑːrbən ˈfʊtprɪnt]',ex:'Reduce your carbon footprint.',img:'👣'},
{en:'biodiversity',kr:'생물다양성',ph:'[ˌbaɪoʊdaɪˈvɜːrsɪti]',ex:'Protect biodiversity.',img:'🦋'},
{en:'renewable',kr:'재생 가능한',ph:'[rɪˈnjuːəbəl]',ex:'Renewable energy sources.',img:'☀️'},
{en:'emission',kr:'배출',ph:'[ɪˈmɪʃən]',ex:'Reduce carbon emissions.',img:'🏭'},
{en:'deforestation',kr:'산림 벌채',ph:'[ˌdiːˌfɒrɪˈsteɪʃən]',ex:'Deforestation must stop.',img:'🌳'},
{en:'ecosystem',kr:'생태계',ph:'[ˈiːkəʊsɪstəm]',ex:'Protect the ecosystem.',img:'🌿'},
{en:'glacier',kr:'빙하',ph:'[ˈɡlæsiər]',ex:'Glaciers are melting.',img:'🧊'},
{en:'drought',kr:'가뭄',ph:'[draʊt]',ex:'A severe drought hit.',img:'🌵'},
{en:'fossil fuel',kr:'화석 연료',ph:'[ˈfɒsəl fjuːəl]',ex:'Phase out fossil fuels.',img:'⛽'},
{en:'net zero',kr:'탄소중립',ph:'[net zɪərəʊ]',ex:'Achieve net zero by 2050.',img:'0️⃣'},
{en:'habitat',kr:'서식지',ph:'[ˈhæbɪtæt]',ex:'Protect natural habitats.',img:'🌲'},
{en:'pollution',kr:'오염',ph:'[pəˈluːʃən]',ex:'Air pollution is harmful.',img:'💨'},
{en:'compost',kr:'퇴비',ph:'[ˈkɒmpɒst]',ex:'Use compost for gardens.',img:'🌱'},
{en:'carbon neutral',kr:'탄소 중립의',ph:'[ˈkɑːrbən ˈnjuːtrəl]',ex:'Become carbon neutral.',img:'⚖️'},
{en:'reforestation',kr:'재조림',ph:'[riːˌfɒrɪˈsteɪʃən]',ex:'Reforestation programs work.',img:'🌳'},
{en:'microplastic',kr:'미세플라스틱',ph:'[ˈmaɪkrəʊplæstɪk]',ex:'Microplastics in oceans.',img:'🌊'},
{en:'photovoltaic',kr:'태양광의',ph:'[ˌfoʊtəʊvɒlˈteɪɪk]',ex:'Photovoltaic panels.',img:'☀️'},
{en:'tipping point',kr:'임계점',ph:'[ˈtɪpɪŋ pɔɪnt]',ex:'We are near the tipping point.',img:'⚠️'},
{en:'stewardship',kr:'관리책임',ph:'[ˈstjuːərdʃɪp]',ex:'Environmental stewardship.',img:'🛡️'},
]},

// ── 이디엄 ──
{id:'idioms',cat:'취미문화',name:'영어 이디엄 1000',desc:'원어민이 자주 쓰는 관용구 모음',emoji:'🗣️',basis:'Merriam-Webster + 원어민 대화 코퍼스 + 드라마 스크립트 분석',count:1000,words:[
{en:'break a leg',kr:'행운을 빌어',ph:'[breɪk ə leɡ]',ex:'Break a leg tonight!',img:'🦵'},
{en:'hit the nail on the head',kr:'정확히 맞히다',ph:'[hɪt ðə neɪl]',ex:'You hit the nail on the head.',img:'🔨'},
{en:'bite the bullet',kr:'참고 견디다',ph:'[baɪt ðə ˈbʊlɪt]',ex:'Just bite the bullet.',img:'💪'},
{en:'under the weather',kr:'몸이 좋지 않은',ph:'[ˈʌndər ðə ˈweðər]',ex:'I\'m a bit under the weather.',img:'🤒'},
{en:'costs an arm and a leg',kr:'매우 비싸다',ph:'[kɒsts æn ɑːrm]',ex:'This car costs an arm and a leg.',img:'💸'},
{en:'spill the beans',kr:'비밀을 누설하다',ph:'[spɪl ðə biːnz]',ex:'Don\'t spill the beans!',img:'🫘'},
{en:'let the cat out of the bag',kr:'실수로 누설하다',ph:'[let ðə kæt]',ex:'She let the cat out of the bag.',img:'🐱'},
{en:'once in a blue moon',kr:'아주 드물게',ph:'[wʌns ɪn ə bluː]',ex:'He calls once in a blue moon.',img:'🌙'},
{en:'hit the sack',kr:'잠자리에 들다',ph:'[hɪt ðə sæk]',ex:'Time to hit the sack.',img:'😴'},
{en:'piece of cake',kr:'식은 죽 먹기',ph:'[piːs əv keɪk]',ex:'This test is a piece of cake.',img:'🎂'},
{en:'beat around the bush',kr:'핵심을 피하다',ph:'[biːt əˈraʊnd]',ex:'Stop beating around the bush.',img:'🌿'},
{en:'burn bridges',kr:'관계를 끊다',ph:'[bɜːrn ˈbrɪdʒɪz]',ex:'Don\'t burn your bridges.',img:'🌉'},
{en:'cold turkey',kr:'갑자기 끊다',ph:'[koʊld ˈtɜːrki]',ex:'He quit cold turkey.',img:'🦃'},
{en:'catch someone off guard',kr:'불시에 당하다',ph:'[kætʃ ɒf ɡɑːrd]',ex:'It caught me off guard.',img:'😲'},
{en:'the ball is in your court',kr:'이제 네 차례야',ph:'[ðə bɔːl ɪz]',ex:'The ball is in your court.',img:'🎾'},
{en:'go back to square one',kr:'원점으로 돌아가다',ph:'[ɡoʊ bæk]',ex:'We had to go back to square one.',img:'1️⃣'},
{en:'see eye to eye',kr:'의견이 일치하다',ph:'[siː aɪ tuː aɪ]',ex:'We don\'t see eye to eye.',img:'👁️'},
{en:'bite off more than you can chew',kr:'감당 못 할 일을 하다',ph:'[baɪt ɒf mɔːr]',ex:'Don\'t bite off more than you can chew.',img:'😬'},
{en:'throw in the towel',kr:'포기하다',ph:'[θroʊ ɪn ðə]',ex:'Never throw in the towel.',img:'🏳️'},
{en:'get out of hand',kr:'손에서 벗어나다',ph:'[ɡet aʊt əv]',ex:'Things got out of hand.',img:'🙈'},
]},
];
// 마켓 추천 팩 (추가 제안)
const MARKET_SUGGESTIONS = [
  {id:'slang',cat:'미디어',name:'유튜브/SNS 슬랭',emoji:'📱',desc:'Gen Z 슬랭 + 인터넷 밈 표현'},
  {id:'sports',cat:'취미문화',name:'스포츠 영어',emoji:'⚽',desc:'ESPN/스포츠 중계 + 종목별 전문 용어'},
  {id:'music',cat:'취미문화',name:'음악/악기',emoji:'🎵',desc:'악기/장르/이론 + 음악 리뷰 어휘'},
  {id:'medical',cat:'학업',name:'의학/간호',emoji:'🏥',desc:'의학 라틴어원 + 증상/진단/치료'},
  {id:'legal',cat:'학업',name:'법률 영어',emoji:'⚖️',desc:'계약/소송/판례 + Legal English 핵심'},
  {id:'finance',cat:'비즈니스',name:'금융/투자',emoji:'📊',desc:'주식/채권/경제지표 + Bloomberg 빈출'},
  {id:'proverbs',cat:'취미문화',name:'영어 속담',emoji:'📜',desc:'자주 쓰이는 영어 속담 + 비유 표현'},
  {id:'etymology',cat:'학업',name:'어원으로 외우기',emoji:'🌱',desc:'라틴/그리스 어원 + 접두사/접미사 패턴'},
];
if(typeof module!=='undefined') module.exports={WORD_PACKS,MARKET_SUGGESTIONS};
